	.align 2
DirectSoundWaveData_bw_sampletank_string_orchestra_60::
	.incbin "sound/direct_sound_samples/bw_sampletank_string_orchestra_60.bin"

	.align 2
DirectSoundWaveData_bw_sampletank_string_orchestra_69::
	.incbin "sound/direct_sound_samples/bw_sampletank_string_orchestra_69.bin"

	.align 2
DirectSoundWaveData_bw_sampletank_string_orchestra_77::
	.incbin "sound/direct_sound_samples/bw_sampletank_string_orchestra_77.bin"

	.align 2
DirectSoundWaveData_bw_sampletank_string_orchestra_84::
	.incbin "sound/direct_sound_samples/bw_sampletank_string_orchestra_84.bin"

	.align 2
DirectSoundWaveData_bw_kfl_trumpet_ensemble_60::
	.incbin "sound/direct_sound_samples/bw_kfl_trumpet_ensemble_60.bin"

	.align 2
DirectSoundWaveData_bw_kfl_trumpet_ensemble_69::
	.incbin "sound/direct_sound_samples/bw_kfl_trumpet_ensemble_69.bin"

	.align 2
DirectSoundWaveData_bw_kfl_trumpet_ensemble_79::
	.incbin "sound/direct_sound_samples/bw_kfl_trumpet_ensemble_79.bin"

	.align 2
DirectSoundWaveData_bw_battery3_chinese_cymbal::
	.incbin "sound/direct_sound_samples/bw_battery3_chinese_cymbal.bin"

	.align 2
DirectSoundWaveData_bw_battery3_rock_cymbal2::
	.incbin "sound/direct_sound_samples/bw_battery3_rock_cymbal2.bin"

	.align 2
DirectSoundWaveData_bw_zg_of_tutti_hit_major::
	.incbin "sound/direct_sound_samples/bw_zg_of_tutti_hit_major.bin"

	.align 2
DirectSoundWaveData_bw_zg_of_tutti_hit_minor_60::
	.incbin "sound/direct_sound_samples/bw_zg_of_tutti_hit_minor_60.bin"

	.align 2
DirectSoundWaveData_bw_kfl_french_horn_ensemble_48::
	.incbin "sound/direct_sound_samples/bw_kfl_french_horn_ensemble_48.bin"

	.align 2
DirectSoundWaveData_bw_kfl_french_horn_ensemble_53::
	.incbin "sound/direct_sound_samples/bw_kfl_french_horn_ensemble_53.bin"

	.align 2
DirectSoundWaveData_bw_kfl_french_horn_ensemble_62::
	.incbin "sound/direct_sound_samples/bw_kfl_french_horn_ensemble_62.bin"

	.align 2
DirectSoundWaveData_bw_kfl_french_horn_ensemble_71::
	.incbin "sound/direct_sound_samples/bw_kfl_french_horn_ensemble_71.bin"

	.align 2
DirectSoundWaveData_bw_independence_pro_khso_trombones_stc::
	.incbin "sound/direct_sound_samples/bw_independence_pro_khso_trombones_stc.bin"

	.align 2
DirectSoundWaveData_bw_independence_pro_khso_all_strings_spc_up::
	.incbin "sound/direct_sound_samples/bw_independence_pro_khso_all_strings_spc_up.bin"

	.align 2
DirectSoundWaveData_bw_kfl_cymbals_a_due::
	.incbin "sound/direct_sound_samples/bw_kfl_cymbals_a_due.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_cello_sus_43::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_cello_sus_43.bin"

	.align 2
DirectSoundWaveData_bw_unknown_snare_roll::
	.incbin "sound/direct_sound_samples/bw_unknown_snare_roll.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_flute_sus_69::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_flute_sus_69.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_flute_sus_77::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_flute_sus_77.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_flute_sus_84::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_flute_sus_84.bin"

	.align 2
DirectSoundWaveData_bw_kfl_harp_55::
	.incbin "sound/direct_sound_samples/bw_kfl_harp_55.bin"

	.align 2
DirectSoundWaveData_bw_kfl_harp_67::
	.incbin "sound/direct_sound_samples/bw_kfl_harp_67.bin"

	.align 2
DirectSoundWaveData_bw_kfl_harp_76::
	.incbin "sound/direct_sound_samples/bw_kfl_harp_76.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_acoustic_grand_piano_72::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_acoustic_grand_piano_72.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_acoustic_grand_piano_84::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_acoustic_grand_piano_84.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_glockenspiel_72::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_glockenspiel_72.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_elastik_36::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_elastik_36.bin"

	.align 2
DirectSoundWaveData_bw_halionone_hard_sync_solo_35::
	.incbin "sound/direct_sound_samples/bw_halionone_hard_sync_solo_35.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_timpani_55::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_timpani_55.bin"

	.align 2
DirectSoundWaveData_bw_kfl_oboe_64::
	.incbin "sound/direct_sound_samples/bw_kfl_oboe_64.bin"

	.align 2
DirectSoundWaveData_bw_kfl_oboe_72::
	.incbin "sound/direct_sound_samples/bw_kfl_oboe_72.bin"

	.align 2
DirectSoundWaveData_bw_ewso_6fh_rips_f::
	.incbin "sound/direct_sound_samples/bw_ewso_6fh_rips_f.bin"

	.align 2
DirectSoundWaveData_bw_ewso_6fh_rips_s::
	.incbin "sound/direct_sound_samples/bw_ewso_6fh_rips_s.bin"

	.align 2
DirectSoundWaveData_bw_ps15_hihat20::
	.incbin "sound/direct_sound_samples/bw_ps15_hihat20.bin"

	.align 2
DirectSoundWaveData_bw_ps15_hihat21::
	.incbin "sound/direct_sound_samples/bw_ps15_hihat21.bin"

	.align 2
DirectSoundWaveData_bw_ps15_kick66::
	.incbin "sound/direct_sound_samples/bw_ps15_kick66.bin"

	.align 2
DirectSoundWaveData_bw_ps15_kick120::
	.incbin "sound/direct_sound_samples/bw_ps15_kick120.bin"

	.align 2
DirectSoundWaveData_bw_ps55_flute_81_22::
	.incbin "sound/direct_sound_samples/bw_ps55_flute_81_22.bin"

	.align 2
DirectSoundWaveData_bw_ps55_flute_89_22::
	.incbin "sound/direct_sound_samples/bw_ps55_flute_89_22.bin"

	.align 2
DirectSoundWaveData_bw_ps19_trumpet_sus_f_72::
	.incbin "sound/direct_sound_samples/bw_ps19_trumpet_sus_f_72.bin"

	.align 2
DirectSoundWaveData_bw_sfx_reshiram_flame::
	.incbin "sound/direct_sound_samples/bw_sfx_reshiram_flame.bin"

	.align 2
DirectSoundWaveData_bw_sfx_zekrom_zap::
	.incbin "sound/direct_sound_samples/bw_sfx_zekrom_zap.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_fend_slap1_pull_43::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_fend_slap1_pull_43.bin"

	.align 2
DirectSoundWaveData_bw_sd90_mg303_bass_42::
	.incbin "sound/direct_sound_samples/bw_sd90_mg303_bass_42.bin"

	.align 2
DirectSoundWaveData_bw_sd90_mg303_bass_66::
	.incbin "sound/direct_sound_samples/bw_sd90_mg303_bass_66.bin"

	.align 2
DirectSoundWaveData_bw_sd90_saw_wave_66::
	.incbin "sound/direct_sound_samples/bw_sd90_saw_wave_66.bin"

	.align 2
DirectSoundWaveData_bw_sd90_saw_wave_85::
	.incbin "sound/direct_sound_samples/bw_sd90_saw_wave_85.bin"

	.align 2
DirectSoundWaveData_bw_sd90_orch_hit2::
	.incbin "sound/direct_sound_samples/bw_sd90_orch_hit2.bin"

	.align 2
DirectSoundWaveData_bw_sd90_car_stop::
	.incbin "sound/direct_sound_samples/bw_sd90_car_stop.bin"

	.align 2
DirectSoundWaveData_bw_sd90_car_crash::
	.incbin "sound/direct_sound_samples/bw_sd90_car_crash.bin"

	.align 2
DirectSoundWaveData_bw_halionone_t9_analog_clap::
	.incbin "sound/direct_sound_samples/bw_halionone_t9_analog_clap.bin"

	.align 2
DirectSoundWaveData_bw_zg_cb_fx_loop6_kick::
	.incbin "sound/direct_sound_samples/bw_zg_cb_fx_loop6_kick.bin"

	.align 2
DirectSoundWaveData_bw_zg_cb_fx_loop6_snare::
	.incbin "sound/direct_sound_samples/bw_zg_cb_fx_loop6_snare.bin"

	.align 2
DirectSoundWaveData_bw_sd90_power2_snare_chorused::
	.incbin "sound/direct_sound_samples/bw_sd90_power2_snare_chorused.bin"

	.align 2
DirectSoundWaveData_bw_sd90_standard2_splash::
	.incbin "sound/direct_sound_samples/bw_sd90_standard2_splash.bin"

	.align 2
DirectSoundWaveData_bw_sd90_timpani2_37::
	.incbin "sound/direct_sound_samples/bw_sd90_timpani2_37.bin"

	.align 2
DirectSoundWaveData_bw_sd90_timpani2_49::
	.incbin "sound/direct_sound_samples/bw_sd90_timpani2_49.bin"

	.align 2
DirectSoundWaveData_bw_sd90_timpani2_61::
	.incbin "sound/direct_sound_samples/bw_sd90_timpani2_61.bin"

	.align 2
DirectSoundWaveData_bw_sd90_analog_snare_reverb::
	.incbin "sound/direct_sound_samples/bw_sd90_analog_snare_reverb.bin"

	.align 2
DirectSoundWaveData_bw_kfl_mark_i_classic_72::
	.incbin "sound/direct_sound_samples/bw_kfl_mark_i_classic_72.bin"

	.align 2
DirectSoundWaveData_bw_ps55_flute_81_32::
	.incbin "sound/direct_sound_samples/bw_ps55_flute_81_32.bin"

	.align 2
DirectSoundWaveData_bw_ps55_flute_89_32::
	.incbin "sound/direct_sound_samples/bw_ps55_flute_89_32.bin"

	.align 2
DirectSoundWaveData_bw_kfl_trombone_ensemble_43::
	.incbin "sound/direct_sound_samples/bw_kfl_trombone_ensemble_43.bin"

	.align 2
DirectSoundWaveData_bw_kfl_trombone_ensemble_52::
	.incbin "sound/direct_sound_samples/bw_kfl_trombone_ensemble_52.bin"

	.align 2
DirectSoundWaveData_bw_ewsc_full_chorus_ah_43::
	.incbin "sound/direct_sound_samples/bw_ewsc_full_chorus_ah_43.bin"

	.align 2
DirectSoundWaveData_bw_ewsc_full_chorus_ah_52::
	.incbin "sound/direct_sound_samples/bw_ewsc_full_chorus_ah_52.bin"

	.align 2
DirectSoundWaveData_bw_ewsc_full_chorus_ah_60::
	.incbin "sound/direct_sound_samples/bw_ewsc_full_chorus_ah_60.bin"

	.align 2
DirectSoundWaveData_bw_zg_cb_guitar_squeal::
	.incbin "sound/direct_sound_samples/bw_zg_cb_guitar_squeal.bin"

	.align 2
DirectSoundWaveData_bw_sd90_power2_snare::
	.incbin "sound/direct_sound_samples/bw_sd90_power2_snare.bin"

	.align 2
DirectSoundWaveData_bw_unknown_suspended_cymbal_40::
	.incbin "sound/direct_sound_samples/bw_unknown_suspended_cymbal_40.bin"

	.align 2
DirectSoundWaveData_bw_zg_total_drum_bass_160_leonora::
	.incbin "sound/direct_sound_samples/bw_zg_total_drum_bass_160_leonora.bin"

	.align 2
DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02::
	.incbin "sound/direct_sound_samples/bw_zg_dpt_orch_snare_16_18_02.bin"

	.align 2
DirectSoundWaveData_bw_unknown_synth_kick_wcs::
	.incbin "sound/direct_sound_samples/bw_unknown_synth_kick_wcs.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_analog_snare_e2::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_analog_snare_e2.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_analog_hihat_closed::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_analog_hihat_closed.bin"

	.align 2
DirectSoundWaveData_bw_plugsound_pro_analog_hihat_open::
	.incbin "sound/direct_sound_samples/bw_plugsound_pro_analog_hihat_open.bin"

	.align 2
DirectSoundWaveData_b2_halion_t9_analog_kick::
	.incbin "sound/direct_sound_samples/b2_halion_t9_analog_kick.bin"

	.align 2
DirectSoundWaveData_b2_halionone_t9_analog_snare::
	.incbin "sound/direct_sound_samples/b2_halionone_t9_analog_snare.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_reso_bass_33::
	.incbin "sound/direct_sound_samples/b2_independence_pro_reso_bass_33.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_reso_bass_38::
	.incbin "sound/direct_sound_samples/b2_independence_pro_reso_bass_38.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_power_chords_combi_1::
	.incbin "sound/direct_sound_samples/b2_independence_pro_power_chords_combi_1.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_power_chords_combi_2::
	.incbin "sound/direct_sound_samples/b2_independence_pro_power_chords_combi_2.bin"

	.align 2
DirectSoundWaveData_b2_independence_pro_power_chords_combi_3::
	.incbin "sound/direct_sound_samples/b2_independence_pro_power_chords_combi_3.bin"

	.align 2
DirectSoundWaveData_b2_omnisphere_aggressive_tendencies::
	.incbin "sound/direct_sound_samples/b2_omnisphere_aggressive_tendencies.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_1::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_1.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_2::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_2.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_3::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_3.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_4::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_4.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_5::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_5.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_6::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_6.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_7::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_7.bin"

	.align 2
DirectSoundWaveData_b2_stylus_rmx_groove106_8::
	.incbin "sound/direct_sound_samples/b2_stylus_rmx_groove106_8.bin"

	.align 2
DirectSoundWaveData_b2_ewso_suspense_string_fx::
	.incbin "sound/direct_sound_samples/b2_ewso_suspense_string_fx.bin"

	.align 2
DirectSoundWaveData_b2_ew_ra_chinese_gong_vs::
	.incbin "sound/direct_sound_samples/b2_ew_ra_chinese_gong_vs.bin"

	.align 2
DirectSoundWaveData_b2_ewso_3_snares::
	.incbin "sound/direct_sound_samples/b2_ewso_3_snares.bin"

	.align 2
DirectSoundWaveData_b2_halionone_t9_analog_hihat_closed::
	.incbin "sound/direct_sound_samples/b2_halionone_t9_analog_hihat_closed.bin"

	.align 2
DirectSoundWaveData_b2_halionone_t9_analog_hihat_open::
	.incbin "sound/direct_sound_samples/b2_halionone_t9_analog_hihat_open.bin"

	.align 2
DirectSoundWaveData_undertale_vanish::
	.incbin "sound/direct_sound_samples/undertale_vanish.bin"

	.align 2
DirectSoundWaveData_vineboom::
	.incbin "sound/direct_sound_samples/cries/notcries/vineboom.bin"

	.align 2
DirectSoundWaveData_americano::
	.incbin "sound/direct_sound_samples/cries/notcries/americano.bin"

	.align 2
DirectSoundWaveData_smwbass::
	.incbin "sound/direct_sound_samples/smwbass.bin"

	.align 2
DirectSoundWaveData_smwbrass1::
	.incbin "sound/direct_sound_samples/smwbrass1.bin"

	.align 2
DirectSoundWaveData_smwbrass2::
	.incbin "sound/direct_sound_samples/smwbrass2.bin"

	.align 2
DirectSoundWaveData_smwchime::
	.incbin "sound/direct_sound_samples/smwchime.bin"

	.align 2
DirectSoundWaveData_smwclar::
	.incbin "sound/direct_sound_samples/smwclar.bin"

	.align 2
DirectSoundWaveData_smwflute::
	.incbin "sound/direct_sound_samples/smwflute.bin"

	.align 2
DirectSoundWaveData_smwhat::
	.incbin "sound/direct_sound_samples/smwhat.bin"

	.align 2
DirectSoundWaveData_smwhatp::
	.incbin "sound/direct_sound_samples/smwhatp.bin"

	.align 2
DirectSoundWaveData_smwkick::
	.incbin "sound/direct_sound_samples/smwkick.bin"

	.align 2
DirectSoundWaveData_smwrhode::
	.incbin "sound/direct_sound_samples/smwrhode.bin"

	.align 2
DirectSoundWaveData_smwstring1::
	.incbin "sound/direct_sound_samples/smwstring1.bin"

	.align 2
DirectSoundWaveData_smwstring2::
	.incbin "sound/direct_sound_samples/smwstring2.bin"

	.align 2
Cry_Turtwig::
	.incbin "sound/direct_sound_samples/cries/turtwig.bin"

	.align 2
Cry_Grotle::
	.incbin "sound/direct_sound_samples/cries/grotle.bin"

	.align 2
Cry_Torterra::
	.incbin "sound/direct_sound_samples/cries/torterra.bin"

	.align 2
Cry_Chimchar::
	.incbin "sound/direct_sound_samples/cries/chimchar.bin"

	.align 2
Cry_Monferno::
	.incbin "sound/direct_sound_samples/cries/monferno.bin"

	.align 2
Cry_Infernape::
	.incbin "sound/direct_sound_samples/cries/infernape.bin"

	.align 2
Cry_Piplup::
	.incbin "sound/direct_sound_samples/cries/piplup.bin"

	.align 2
Cry_Prinplup::
	.incbin "sound/direct_sound_samples/cries/prinplup.bin"

	.align 2
Cry_Empoleon::
	.incbin "sound/direct_sound_samples/cries/empoleon.bin"

	.align 2
Cry_Starly::
	.incbin "sound/direct_sound_samples/cries/starly.bin"

	.align 2
Cry_Staravia::
	.incbin "sound/direct_sound_samples/cries/staravia.bin"

	.align 2
Cry_Staraptor::
	.incbin "sound/direct_sound_samples/cries/staraptor.bin"

	.align 2
Cry_Bidoof::
	.incbin "sound/direct_sound_samples/cries/bidoof.bin"

	.align 2
Cry_Bibarel::
	.incbin "sound/direct_sound_samples/cries/bibarel.bin"

	.align 2
Cry_Kricketot::
	.incbin "sound/direct_sound_samples/cries/kricketot.bin"

	.align 2
Cry_Kricketune::
	.incbin "sound/direct_sound_samples/cries/kricketune.bin"

	.align 2
Cry_Shinx::
	.incbin "sound/direct_sound_samples/cries/shinx.bin"

	.align 2
Cry_Luxio::
	.incbin "sound/direct_sound_samples/cries/luxio.bin"

	.align 2
Cry_Luxray::
	.incbin "sound/direct_sound_samples/cries/luxray.bin"

	.align 2
Cry_Budew::
	.incbin "sound/direct_sound_samples/cries/budew.bin"

	.align 2
Cry_Roserade::
	.incbin "sound/direct_sound_samples/cries/roserade.bin"

	.align 2
Cry_Cranidos::
	.incbin "sound/direct_sound_samples/cries/cranidos.bin"

	.align 2
Cry_Rampardos::
	.incbin "sound/direct_sound_samples/cries/rampardos.bin"

	.align 2
Cry_Shieldon::
	.incbin "sound/direct_sound_samples/cries/shieldon.bin"

	.align 2
Cry_Bastiodon::
	.incbin "sound/direct_sound_samples/cries/bastiodon.bin"

	.align 2
Cry_Burmy::
	.incbin "sound/direct_sound_samples/cries/burmy.bin"

	.align 2
Cry_Wormadam::
	.incbin "sound/direct_sound_samples/cries/wormadam.bin"

	.align 2
Cry_Mothim::
	.incbin "sound/direct_sound_samples/cries/mothim.bin"

	.align 2
Cry_Combee::
	.incbin "sound/direct_sound_samples/cries/combee.bin"

	.align 2
Cry_Vespiquen::
	.incbin "sound/direct_sound_samples/cries/vespiquen.bin"

	.align 2
Cry_Pachirisu::
	.incbin "sound/direct_sound_samples/cries/pachirisu.bin"

	.align 2
Cry_Buizel::
	.incbin "sound/direct_sound_samples/cries/buizel.bin"

	.align 2
Cry_Floatzel::
	.incbin "sound/direct_sound_samples/cries/floatzel.bin"

	.align 2
Cry_Cherubi::
	.incbin "sound/direct_sound_samples/cries/cherubi.bin"

	.align 2
Cry_Cherrim::
	.incbin "sound/direct_sound_samples/cries/cherrim.bin"

	.align 2
Cry_Shellos::
	.incbin "sound/direct_sound_samples/cries/shellos.bin"

	.align 2
Cry_Gastrodon::
	.incbin "sound/direct_sound_samples/cries/gastrodon.bin"

	.align 2
Cry_Ambipom::
	.incbin "sound/direct_sound_samples/cries/ambipom.bin"

	.align 2
Cry_Drifloon::
	.incbin "sound/direct_sound_samples/cries/drifloon.bin"

	.align 2
Cry_Drifblim::
	.incbin "sound/direct_sound_samples/cries/drifblim.bin"

	.align 2
Cry_Buneary::
	.incbin "sound/direct_sound_samples/cries/buneary.bin"

	.align 2
Cry_Lopunny::
	.incbin "sound/direct_sound_samples/cries/lopunny.bin"

	.align 2
Cry_Mismagius::
	.incbin "sound/direct_sound_samples/cries/mismagius.bin"

	.align 2
Cry_Honchkrow::
	.incbin "sound/direct_sound_samples/cries/honchkrow.bin"

	.align 2
Cry_Glameow::
	.incbin "sound/direct_sound_samples/cries/glameow.bin"

	.align 2
Cry_Purugly::
	.incbin "sound/direct_sound_samples/cries/purugly.bin"

	.align 2
Cry_Chingling::
	.incbin "sound/direct_sound_samples/cries/chingling.bin"

	.align 2
Cry_Stunky::
	.incbin "sound/direct_sound_samples/cries/stunky.bin"

	.align 2
Cry_Skuntank::
	.incbin "sound/direct_sound_samples/cries/skuntank.bin"

	.align 2
Cry_Bronzor::
	.incbin "sound/direct_sound_samples/cries/bronzor.bin"

	.align 2
Cry_Bronzong::
	.incbin "sound/direct_sound_samples/cries/bronzong.bin"

	.align 2
Cry_Bonsly::
	.incbin "sound/direct_sound_samples/cries/bonsly.bin"

	.align 2
Cry_MimeJr::
	.incbin "sound/direct_sound_samples/cries/mime_jr.bin"

	.align 2
Cry_Happiny::
	.incbin "sound/direct_sound_samples/cries/happiny.bin"

	.align 2
Cry_Chatot::
	.incbin "sound/direct_sound_samples/cries/chatot.bin"

	.align 2
Cry_Spiritomb::
	.incbin "sound/direct_sound_samples/cries/spiritomb.bin"

	.align 2
Cry_Gible::
	.incbin "sound/direct_sound_samples/cries/gible.bin"

	.align 2
Cry_Gabite::
	.incbin "sound/direct_sound_samples/cries/gabite.bin"

	.align 2
Cry_Garchomp::
	.incbin "sound/direct_sound_samples/cries/garchomp.bin"

	.align 2
Cry_Munchlax::
	.incbin "sound/direct_sound_samples/cries/munchlax.bin"

	.align 2
Cry_Riolu::
	.incbin "sound/direct_sound_samples/cries/riolu.bin"

	.align 2
Cry_Lucario::
	.incbin "sound/direct_sound_samples/cries/lucario.bin"

	.align 2
Cry_Hippopotas::
	.incbin "sound/direct_sound_samples/cries/hippopotas.bin"

	.align 2
Cry_Hippowdon::
	.incbin "sound/direct_sound_samples/cries/hippowdon.bin"

	.align 2
Cry_Skorupi::
	.incbin "sound/direct_sound_samples/cries/skorupi.bin"

	.align 2
Cry_Drapion::
	.incbin "sound/direct_sound_samples/cries/drapion.bin"

	.align 2
Cry_Croagunk::
	.incbin "sound/direct_sound_samples/cries/croagunk.bin"

	.align 2
Cry_Toxicroak::
	.incbin "sound/direct_sound_samples/cries/toxicroak.bin"

	.align 2
Cry_Carnivine::
	.incbin "sound/direct_sound_samples/cries/carnivine.bin"

	.align 2
Cry_Finneon::
	.incbin "sound/direct_sound_samples/cries/finneon.bin"

	.align 2
Cry_Lumineon::
	.incbin "sound/direct_sound_samples/cries/lumineon.bin"

	.align 2
Cry_Mantyke::
	.incbin "sound/direct_sound_samples/cries/mantyke.bin"

	.align 2
Cry_Snover::
	.incbin "sound/direct_sound_samples/cries/snover.bin"

	.align 2
Cry_Abomasnow::
	.incbin "sound/direct_sound_samples/cries/abomasnow.bin"

	.align 2
Cry_Weavile::
	.incbin "sound/direct_sound_samples/cries/weavile.bin"

	.align 2
Cry_Magnezone::
	.incbin "sound/direct_sound_samples/cries/magnezone.bin"

	.align 2
Cry_Lickilicky::
	.incbin "sound/direct_sound_samples/cries/lickilicky.bin"

	.align 2
Cry_Rhyperior::
	.incbin "sound/direct_sound_samples/cries/rhyperior.bin"

	.align 2
Cry_Tangrowth::
	.incbin "sound/direct_sound_samples/cries/tangrowth.bin"

	.align 2
Cry_Electivire::
	.incbin "sound/direct_sound_samples/cries/electivire.bin"

	.align 2
Cry_Magmortar::
	.incbin "sound/direct_sound_samples/cries/magmortar.bin"

	.align 2
Cry_Togekiss::
	.incbin "sound/direct_sound_samples/cries/togekiss.bin"

	.align 2
Cry_Yanmega::
	.incbin "sound/direct_sound_samples/cries/yanmega.bin"

	.align 2
Cry_Leafeon::
	.incbin "sound/direct_sound_samples/cries/leafeon.bin"

	.align 2
Cry_Glaceon::
	.incbin "sound/direct_sound_samples/cries/glaceon.bin"

	.align 2
Cry_Gliscor::
	.incbin "sound/direct_sound_samples/cries/gliscor.bin"

	.align 2
Cry_Mamoswine::
	.incbin "sound/direct_sound_samples/cries/mamoswine.bin"

	.align 2
Cry_PorygonZ::
	.incbin "sound/direct_sound_samples/cries/porygon_z.bin"

	.align 2
Cry_Gallade::
	.incbin "sound/direct_sound_samples/cries/gallade.bin"

	.align 2
Cry_Probopass::
	.incbin "sound/direct_sound_samples/cries/probopass.bin"

	.align 2
Cry_Dusknoir::
	.incbin "sound/direct_sound_samples/cries/dusknoir.bin"

	.align 2
Cry_Froslass::
	.incbin "sound/direct_sound_samples/cries/froslass.bin"

	.align 2
Cry_Rotom::
	.incbin "sound/direct_sound_samples/cries/rotom.bin"

	.align 2
Cry_Uxie::
	.incbin "sound/direct_sound_samples/cries/uxie.bin"

	.align 2
Cry_Mesprit::
	.incbin "sound/direct_sound_samples/cries/mesprit.bin"

	.align 2
Cry_Azelf::
	.incbin "sound/direct_sound_samples/cries/azelf.bin"

	.align 2
Cry_Dialga::
	.incbin "sound/direct_sound_samples/cries/dialga.bin"

	.align 2
Cry_Palkia::
	.incbin "sound/direct_sound_samples/cries/palkia.bin"

	.align 2
Cry_Heatran::
	.incbin "sound/direct_sound_samples/cries/heatran.bin"

	.align 2
Cry_Regigigas::
	.incbin "sound/direct_sound_samples/cries/regigigas.bin"

	.align 2
Cry_Giratina::
	.incbin "sound/direct_sound_samples/cries/giratina.bin"

	.align 2
Cry_Cresselia::
	.incbin "sound/direct_sound_samples/cries/cresselia.bin"

	.align 2
Cry_Phione::
	.incbin "sound/direct_sound_samples/cries/phione.bin"

	.align 2
Cry_Manaphy::
	.incbin "sound/direct_sound_samples/cries/manaphy.bin"

	.align 2
Cry_Darkrai::
	.incbin "sound/direct_sound_samples/cries/darkrai.bin"

	.align 2
Cry_Shaymin::
	.incbin "sound/direct_sound_samples/cries/shaymin.bin"

	.align 2
Cry_Arceus::
	.incbin "sound/direct_sound_samples/cries/arceus.bin"

	.align 2
Cry_Victini::
	.incbin "sound/direct_sound_samples/cries/victini.bin"

	.align 2
Cry_Snivy::
	.incbin "sound/direct_sound_samples/cries/snivy.bin"

	.align 2
Cry_Servine::
	.incbin "sound/direct_sound_samples/cries/servine.bin"

	.align 2
Cry_Serperior::
	.incbin "sound/direct_sound_samples/cries/serperior.bin"

	.align 2
Cry_Tepig::
	.incbin "sound/direct_sound_samples/cries/tepig.bin"

	.align 2
Cry_Pignite::
	.incbin "sound/direct_sound_samples/cries/pignite.bin"

	.align 2
Cry_Emboar::
	.incbin "sound/direct_sound_samples/cries/emboar.bin"

	.align 2
Cry_Oshawott::
	.incbin "sound/direct_sound_samples/cries/oshawott.bin"

	.align 2
Cry_Dewott::
	.incbin "sound/direct_sound_samples/cries/dewott.bin"

	.align 2
Cry_Samurott::
	.incbin "sound/direct_sound_samples/cries/samurott.bin"

	.align 2
Cry_Patrat::
	.incbin "sound/direct_sound_samples/cries/patrat.bin"

	.align 2
Cry_Watchog::
	.incbin "sound/direct_sound_samples/cries/watchog.bin"

	.align 2
Cry_Lillipup::
	.incbin "sound/direct_sound_samples/cries/lillipup.bin"

	.align 2
Cry_Herdier::
	.incbin "sound/direct_sound_samples/cries/herdier.bin"

	.align 2
Cry_Stoutland::
	.incbin "sound/direct_sound_samples/cries/stoutland.bin"

	.align 2
Cry_Purrloin::
	.incbin "sound/direct_sound_samples/cries/purrloin.bin"

	.align 2
Cry_Liepard::
	.incbin "sound/direct_sound_samples/cries/liepard.bin"

	.align 2
Cry_Pansage::
	.incbin "sound/direct_sound_samples/cries/pansage.bin"

	.align 2
Cry_Simisage::
	.incbin "sound/direct_sound_samples/cries/simisage.bin"

	.align 2
Cry_Pansear::
	.incbin "sound/direct_sound_samples/cries/pansear.bin"

	.align 2
Cry_Simisear::
	.incbin "sound/direct_sound_samples/cries/simisear.bin"

	.align 2
Cry_Panpour::
	.incbin "sound/direct_sound_samples/cries/panpour.bin"

	.align 2
Cry_Simipour::
	.incbin "sound/direct_sound_samples/cries/simipour.bin"

	.align 2
Cry_Munna::
	.incbin "sound/direct_sound_samples/cries/munna.bin"

	.align 2
Cry_Musharna::
	.incbin "sound/direct_sound_samples/cries/musharna.bin"

	.align 2
Cry_Pidove::
	.incbin "sound/direct_sound_samples/cries/pidove.bin"

	.align 2
Cry_Tranquill::
	.incbin "sound/direct_sound_samples/cries/tranquill.bin"

	.align 2
Cry_Unfezant::
	.incbin "sound/direct_sound_samples/cries/unfezant.bin"

	.align 2
Cry_Blitzle::
	.incbin "sound/direct_sound_samples/cries/blitzle.bin"

	.align 2
Cry_Zebstrika::
	.incbin "sound/direct_sound_samples/cries/zebstrika.bin"

	.align 2
Cry_Roggenrola::
	.incbin "sound/direct_sound_samples/cries/roggenrola.bin"

	.align 2
Cry_Boldore::
	.incbin "sound/direct_sound_samples/cries/boldore.bin"

	.align 2
Cry_Gigalith::
	.incbin "sound/direct_sound_samples/cries/gigalith.bin"

	.align 2
Cry_Woobat::
	.incbin "sound/direct_sound_samples/cries/woobat.bin"

	.align 2
Cry_Swoobat::
	.incbin "sound/direct_sound_samples/cries/swoobat.bin"

	.align 2
Cry_Drilbur::
	.incbin "sound/direct_sound_samples/cries/drilbur.bin"

	.align 2
Cry_Excadrill::
	.incbin "sound/direct_sound_samples/cries/excadrill.bin"

	.align 2
Cry_Audino::
	.incbin "sound/direct_sound_samples/cries/audino.bin"

	.align 2
Cry_Timburr::
	.incbin "sound/direct_sound_samples/cries/timburr.bin"

	.align 2
Cry_Gurdurr::
	.incbin "sound/direct_sound_samples/cries/gurdurr.bin"

	.align 2
Cry_Conkeldurr::
	.incbin "sound/direct_sound_samples/cries/conkeldurr.bin"

	.align 2
Cry_Tympole::
	.incbin "sound/direct_sound_samples/cries/tympole.bin"

	.align 2
Cry_Palpitoad::
	.incbin "sound/direct_sound_samples/cries/palpitoad.bin"

	.align 2
Cry_Seismitoad::
	.incbin "sound/direct_sound_samples/cries/seismitoad.bin"

	.align 2
Cry_Throh::
	.incbin "sound/direct_sound_samples/cries/throh.bin"

	.align 2
Cry_Sawk::
	.incbin "sound/direct_sound_samples/cries/sawk.bin"

	.align 2
Cry_Sewaddle::
	.incbin "sound/direct_sound_samples/cries/sewaddle.bin"

	.align 2
Cry_Swadloon::
	.incbin "sound/direct_sound_samples/cries/swadloon.bin"

	.align 2
Cry_Leavanny::
	.incbin "sound/direct_sound_samples/cries/leavanny.bin"

	.align 2
Cry_Venipede::
	.incbin "sound/direct_sound_samples/cries/venipede.bin"

	.align 2
Cry_Whirlipede::
	.incbin "sound/direct_sound_samples/cries/whirlipede.bin"

	.align 2
Cry_Scolipede::
	.incbin "sound/direct_sound_samples/cries/scolipede.bin"

	.align 2
Cry_Cottonee::
	.incbin "sound/direct_sound_samples/cries/cottonee.bin"

	.align 2
Cry_Whimsicott::
	.incbin "sound/direct_sound_samples/cries/whimsicott.bin"

	.align 2
Cry_Petilil::
	.incbin "sound/direct_sound_samples/cries/petilil.bin"

	.align 2
Cry_Lilligant::
	.incbin "sound/direct_sound_samples/cries/lilligant.bin"

	.align 2
Cry_Basculin::
	.incbin "sound/direct_sound_samples/cries/basculin.bin"

	.align 2
Cry_Sandile::
	.incbin "sound/direct_sound_samples/cries/sandile.bin"

	.align 2
Cry_Krokorok::
	.incbin "sound/direct_sound_samples/cries/krokorok.bin"

	.align 2
Cry_Krookodile::
	.incbin "sound/direct_sound_samples/cries/krookodile.bin"

	.align 2
Cry_Darumaka::
	.incbin "sound/direct_sound_samples/cries/darumaka.bin"

	.align 2
Cry_Darmanitan::
	.incbin "sound/direct_sound_samples/cries/darmanitan.bin"

	.align 2
Cry_Maractus::
	.incbin "sound/direct_sound_samples/cries/maractus.bin"

	.align 2
Cry_Dwebble::
	.incbin "sound/direct_sound_samples/cries/dwebble.bin"

	.align 2
Cry_Crustle::
	.incbin "sound/direct_sound_samples/cries/crustle.bin"

	.align 2
Cry_Scraggy::
	.incbin "sound/direct_sound_samples/cries/scraggy.bin"

	.align 2
Cry_Scrafty::
	.incbin "sound/direct_sound_samples/cries/scrafty.bin"

	.align 2
Cry_Sigilyph::
	.incbin "sound/direct_sound_samples/cries/sigilyph.bin"

	.align 2
Cry_Yamask::
	.incbin "sound/direct_sound_samples/cries/yamask.bin"

	.align 2
Cry_Cofagrigus::
	.incbin "sound/direct_sound_samples/cries/cofagrigus.bin"

	.align 2
Cry_Tirtouga::
	.incbin "sound/direct_sound_samples/cries/tirtouga.bin"

	.align 2
Cry_Carracosta::
	.incbin "sound/direct_sound_samples/cries/carracosta.bin"

	.align 2
Cry_Archen::
	.incbin "sound/direct_sound_samples/cries/archen.bin"

	.align 2
Cry_Archeops::
	.incbin "sound/direct_sound_samples/cries/archeops.bin"

	.align 2
Cry_Trubbish::
	.incbin "sound/direct_sound_samples/cries/trubbish.bin"

	.align 2
Cry_Garbodor::
	.incbin "sound/direct_sound_samples/cries/garbodor.bin"

	.align 2
Cry_Zorua::
	.incbin "sound/direct_sound_samples/cries/zorua.bin"

	.align 2
Cry_Zoroark::
	.incbin "sound/direct_sound_samples/cries/zoroark.bin"

	.align 2
Cry_Minccino::
	.incbin "sound/direct_sound_samples/cries/minccino.bin"

	.align 2
Cry_Cinccino::
	.incbin "sound/direct_sound_samples/cries/cinccino.bin"

	.align 2
Cry_Gothita::
	.incbin "sound/direct_sound_samples/cries/gothita.bin"

	.align 2
Cry_Gothorita::
	.incbin "sound/direct_sound_samples/cries/gothorita.bin"

	.align 2
Cry_Gothitelle::
	.incbin "sound/direct_sound_samples/cries/gothitelle.bin"

	.align 2
Cry_Solosis::
	.incbin "sound/direct_sound_samples/cries/solosis.bin"

	.align 2
Cry_Duosion::
	.incbin "sound/direct_sound_samples/cries/duosion.bin"

	.align 2
Cry_Reuniclus::
	.incbin "sound/direct_sound_samples/cries/reuniclus.bin"

	.align 2
Cry_Ducklett::
	.incbin "sound/direct_sound_samples/cries/ducklett.bin"

	.align 2
Cry_Swanna::
	.incbin "sound/direct_sound_samples/cries/swanna.bin"

	.align 2
Cry_Vanillite::
	.incbin "sound/direct_sound_samples/cries/vanillite.bin"

	.align 2
Cry_Vanillish::
	.incbin "sound/direct_sound_samples/cries/vanillish.bin"

	.align 2
Cry_Vanilluxe::
	.incbin "sound/direct_sound_samples/cries/vanilluxe.bin"

	.align 2
Cry_Deerling::
	.incbin "sound/direct_sound_samples/cries/deerling.bin"

	.align 2
Cry_Sawsbuck::
	.incbin "sound/direct_sound_samples/cries/sawsbuck.bin"

	.align 2
Cry_Emolga::
	.incbin "sound/direct_sound_samples/cries/emolga.bin"

	.align 2
Cry_Karrablast::
	.incbin "sound/direct_sound_samples/cries/karrablast.bin"

	.align 2
Cry_Escavalier::
	.incbin "sound/direct_sound_samples/cries/escavalier.bin"

	.align 2
Cry_Foongus::
	.incbin "sound/direct_sound_samples/cries/foongus.bin"

	.align 2
Cry_Amoonguss::
	.incbin "sound/direct_sound_samples/cries/amoonguss.bin"

	.align 2
Cry_Frillish::
	.incbin "sound/direct_sound_samples/cries/frillish.bin"

	.align 2
Cry_Jellicent::
	.incbin "sound/direct_sound_samples/cries/jellicent.bin"

	.align 2
Cry_Alomomola::
	.incbin "sound/direct_sound_samples/cries/alomomola.bin"

	.align 2
Cry_Joltik::
	.incbin "sound/direct_sound_samples/cries/joltik.bin"

	.align 2
Cry_Galvantula::
	.incbin "sound/direct_sound_samples/cries/galvantula.bin"

	.align 2
Cry_Ferroseed::
	.incbin "sound/direct_sound_samples/cries/ferroseed.bin"

	.align 2
Cry_Ferrothorn::
	.incbin "sound/direct_sound_samples/cries/ferrothorn.bin"

	.align 2
Cry_Klink::
	.incbin "sound/direct_sound_samples/cries/klink.bin"

	.align 2
Cry_Klang::
	.incbin "sound/direct_sound_samples/cries/klang.bin"

	.align 2
Cry_Klinklang::
	.incbin "sound/direct_sound_samples/cries/klinklang.bin"

	.align 2
Cry_Tynamo::
	.incbin "sound/direct_sound_samples/cries/tynamo.bin"

	.align 2
Cry_Eelektrik::
	.incbin "sound/direct_sound_samples/cries/eelektrik.bin"

	.align 2
Cry_Eelektross::
	.incbin "sound/direct_sound_samples/cries/eelektross.bin"

	.align 2
Cry_Elgyem::
	.incbin "sound/direct_sound_samples/cries/elgyem.bin"

	.align 2
Cry_Beheeyem::
	.incbin "sound/direct_sound_samples/cries/beheeyem.bin"

	.align 2
Cry_Litwick::
	.incbin "sound/direct_sound_samples/cries/litwick.bin"

	.align 2
Cry_Lampent::
	.incbin "sound/direct_sound_samples/cries/lampent.bin"

	.align 2
Cry_Chandelure::
	.incbin "sound/direct_sound_samples/cries/chandelure.bin"

	.align 2
Cry_Axew::
	.incbin "sound/direct_sound_samples/cries/axew.bin"

	.align 2
Cry_Fraxure::
	.incbin "sound/direct_sound_samples/cries/fraxure.bin"

	.align 2
Cry_Haxorus::
	.incbin "sound/direct_sound_samples/cries/haxorus.bin"

	.align 2
Cry_Cubchoo::
	.incbin "sound/direct_sound_samples/cries/cubchoo.bin"

	.align 2
Cry_Beartic::
	.incbin "sound/direct_sound_samples/cries/beartic.bin"

	.align 2
Cry_Cryogonal::
	.incbin "sound/direct_sound_samples/cries/cryogonal.bin"

	.align 2
Cry_Shelmet::
	.incbin "sound/direct_sound_samples/cries/shelmet.bin"

	.align 2
Cry_Accelgor::
	.incbin "sound/direct_sound_samples/cries/accelgor.bin"

	.align 2
Cry_Stunfisk::
	.incbin "sound/direct_sound_samples/cries/stunfisk.bin"

	.align 2
Cry_Mienfoo::
	.incbin "sound/direct_sound_samples/cries/mienfoo.bin"

	.align 2
Cry_Mienshao::
	.incbin "sound/direct_sound_samples/cries/mienshao.bin"

	.align 2
Cry_Druddigon::
	.incbin "sound/direct_sound_samples/cries/druddigon.bin"

	.align 2
Cry_Golett::
	.incbin "sound/direct_sound_samples/cries/golett.bin"

	.align 2
Cry_Golurk::
	.incbin "sound/direct_sound_samples/cries/golurk.bin"

	.align 2
Cry_Pawniard::
	.incbin "sound/direct_sound_samples/cries/pawniard.bin"

	.align 2
Cry_Bisharp::
	.incbin "sound/direct_sound_samples/cries/bisharp.bin"

	.align 2
Cry_Bouffalant::
	.incbin "sound/direct_sound_samples/cries/bouffalant.bin"

	.align 2
Cry_Rufflet::
	.incbin "sound/direct_sound_samples/cries/rufflet.bin"

	.align 2
Cry_Braviary::
	.incbin "sound/direct_sound_samples/cries/braviary.bin"

	.align 2
Cry_Vullaby::
	.incbin "sound/direct_sound_samples/cries/vullaby.bin"

	.align 2
Cry_Mandibuzz::
	.incbin "sound/direct_sound_samples/cries/mandibuzz.bin"

	.align 2
Cry_Heatmor::
	.incbin "sound/direct_sound_samples/cries/heatmor.bin"

	.align 2
Cry_Durant::
	.incbin "sound/direct_sound_samples/cries/durant.bin"

	.align 2
Cry_Deino::
	.incbin "sound/direct_sound_samples/cries/deino.bin"

	.align 2
Cry_Zweilous::
	.incbin "sound/direct_sound_samples/cries/zweilous.bin"

	.align 2
Cry_Hydreigon::
	.incbin "sound/direct_sound_samples/cries/hydreigon.bin"

	.align 2
Cry_Larvesta::
	.incbin "sound/direct_sound_samples/cries/larvesta.bin"

	.align 2
Cry_Volcarona::
	.incbin "sound/direct_sound_samples/cries/volcarona.bin"

	.align 2
Cry_Cobalion::
	.incbin "sound/direct_sound_samples/cries/cobalion.bin"

	.align 2
Cry_Terrakion::
	.incbin "sound/direct_sound_samples/cries/terrakion.bin"

	.align 2
Cry_Virizion::
	.incbin "sound/direct_sound_samples/cries/virizion.bin"

	.align 2
Cry_Tornadus::
	.incbin "sound/direct_sound_samples/cries/tornadus.bin"

	.align 2
Cry_Thundurus::
	.incbin "sound/direct_sound_samples/cries/thundurus.bin"

	.align 2
Cry_Reshiram::
	.incbin "sound/direct_sound_samples/cries/reshiram.bin"

	.align 2
Cry_Zekrom::
	.incbin "sound/direct_sound_samples/cries/zekrom.bin"

	.align 2
Cry_Landorus::
	.incbin "sound/direct_sound_samples/cries/landorus.bin"

	.align 2
Cry_Kyurem::
	.incbin "sound/direct_sound_samples/cries/kyurem.bin"

	.align 2
Cry_Keldeo::
	.incbin "sound/direct_sound_samples/cries/keldeo.bin"

	.align 2
Cry_Meloetta::
	.incbin "sound/direct_sound_samples/cries/meloetta.bin"

	.align 2
Cry_Genesect::
	.incbin "sound/direct_sound_samples/cries/genesect.bin"

	.align 2
Cry_Chespin::
	.incbin "sound/direct_sound_samples/cries/chespin.bin"

	.align 2
Cry_Quilladin::
	.incbin "sound/direct_sound_samples/cries/quilladin.bin"

	.align 2
Cry_Chesnaught::
	.incbin "sound/direct_sound_samples/cries/chesnaught.bin"

	.align 2
Cry_Fennekin::
	.incbin "sound/direct_sound_samples/cries/fennekin.bin"

	.align 2
Cry_Braixen::
	.incbin "sound/direct_sound_samples/cries/braixen.bin"

	.align 2
Cry_Delphox::
	.incbin "sound/direct_sound_samples/cries/delphox.bin"

	.align 2
Cry_Froakie::
	.incbin "sound/direct_sound_samples/cries/froakie.bin"

	.align 2
Cry_Frogadier::
	.incbin "sound/direct_sound_samples/cries/frogadier.bin"

	.align 2
Cry_Greninja::
	.incbin "sound/direct_sound_samples/cries/greninja.bin"

	.align 2
Cry_Bunnelby::
	.incbin "sound/direct_sound_samples/cries/bunnelby.bin"

	.align 2
Cry_Diggersby::
	.incbin "sound/direct_sound_samples/cries/diggersby.bin"

	.align 2
Cry_Fletchling::
	.incbin "sound/direct_sound_samples/cries/fletchling.bin"

	.align 2
Cry_Fletchinder::
	.incbin "sound/direct_sound_samples/cries/fletchinder.bin"

	.align 2
Cry_Talonflame::
	.incbin "sound/direct_sound_samples/cries/talonflame.bin"

	.align 2
Cry_Scatterbug::
	.incbin "sound/direct_sound_samples/cries/scatterbug.bin"

	.align 2
Cry_Spewpa::
	.incbin "sound/direct_sound_samples/cries/spewpa.bin"

	.align 2
Cry_Vivillon::
	.incbin "sound/direct_sound_samples/cries/vivillon.bin"

	.align 2
Cry_Litleo::
	.incbin "sound/direct_sound_samples/cries/litleo.bin"

	.align 2
Cry_Pyroar::
	.incbin "sound/direct_sound_samples/cries/pyroar.bin"

	.align 2
Cry_Flabebe::
	.incbin "sound/direct_sound_samples/cries/flabebe.bin"

	.align 2
Cry_Floette::
	.incbin "sound/direct_sound_samples/cries/floette.bin"

	.align 2
Cry_Florges::
	.incbin "sound/direct_sound_samples/cries/florges.bin"

	.align 2
Cry_Skiddo::
	.incbin "sound/direct_sound_samples/cries/skiddo.bin"

	.align 2
Cry_Gogoat::
	.incbin "sound/direct_sound_samples/cries/gogoat.bin"

	.align 2
Cry_Pancham::
	.incbin "sound/direct_sound_samples/cries/pancham.bin"

	.align 2
Cry_Pangoro::
	.incbin "sound/direct_sound_samples/cries/pangoro.bin"

	.align 2
Cry_Furfrou::
	.incbin "sound/direct_sound_samples/cries/furfrou.bin"

	.align 2
Cry_Espurr::
	.incbin "sound/direct_sound_samples/cries/espurr.bin"

	.align 2
Cry_Meowstic::
	.incbin "sound/direct_sound_samples/cries/meowstic.bin"

	.align 2
Cry_Honedge::
	.incbin "sound/direct_sound_samples/cries/honedge.bin"

	.align 2
Cry_Doublade::
	.incbin "sound/direct_sound_samples/cries/doublade.bin"

	.align 2
Cry_Aegislash::
	.incbin "sound/direct_sound_samples/cries/aegislash.bin"

	.align 2
Cry_Spritzee::
	.incbin "sound/direct_sound_samples/cries/spritzee.bin"

	.align 2
Cry_Aromatisse::
	.incbin "sound/direct_sound_samples/cries/aromatisse.bin"

	.align 2
Cry_Swirlix::
	.incbin "sound/direct_sound_samples/cries/swirlix.bin"

	.align 2
Cry_Slurpuff::
	.incbin "sound/direct_sound_samples/cries/slurpuff.bin"

	.align 2
Cry_Inkay::
	.incbin "sound/direct_sound_samples/cries/inkay.bin"

	.align 2
Cry_Malamar::
	.incbin "sound/direct_sound_samples/cries/malamar.bin"

	.align 2
Cry_Binacle::
	.incbin "sound/direct_sound_samples/cries/binacle.bin"

	.align 2
Cry_Barbaracle::
	.incbin "sound/direct_sound_samples/cries/barbaracle.bin"

	.align 2
Cry_Skrelp::
	.incbin "sound/direct_sound_samples/cries/skrelp.bin"

	.align 2
Cry_Dragalge::
	.incbin "sound/direct_sound_samples/cries/dragalge.bin"

	.align 2
Cry_Clauncher::
	.incbin "sound/direct_sound_samples/cries/clauncher.bin"

	.align 2
Cry_Clawitzer::
	.incbin "sound/direct_sound_samples/cries/clawitzer.bin"

	.align 2
Cry_Helioptile::
	.incbin "sound/direct_sound_samples/cries/helioptile.bin"

	.align 2
Cry_Heliolisk::
	.incbin "sound/direct_sound_samples/cries/heliolisk.bin"

	.align 2
Cry_Tyrunt::
	.incbin "sound/direct_sound_samples/cries/tyrunt.bin"

	.align 2
Cry_Tyrantrum::
	.incbin "sound/direct_sound_samples/cries/tyrantrum.bin"

	.align 2
Cry_Amaura::
	.incbin "sound/direct_sound_samples/cries/amaura.bin"

	.align 2
Cry_Aurorus::
	.incbin "sound/direct_sound_samples/cries/aurorus.bin"

	.align 2
Cry_Sylveon::
	.incbin "sound/direct_sound_samples/cries/sylveon.bin"

	.align 2
Cry_Hawlucha::
	.incbin "sound/direct_sound_samples/cries/hawlucha.bin"

	.align 2
Cry_Dedenne::
	.incbin "sound/direct_sound_samples/cries/dedenne.bin"

	.align 2
Cry_Carbink::
	.incbin "sound/direct_sound_samples/cries/carbink.bin"

	.align 2
Cry_Goomy::
	.incbin "sound/direct_sound_samples/cries/goomy.bin"

	.align 2
Cry_Sliggoo::
	.incbin "sound/direct_sound_samples/cries/sliggoo.bin"

	.align 2
Cry_Goodra::
	.incbin "sound/direct_sound_samples/cries/goodra.bin"

	.align 2
Cry_Klefki::
	.incbin "sound/direct_sound_samples/cries/klefki.bin"

	.align 2
Cry_Phantump::
	.incbin "sound/direct_sound_samples/cries/phantump.bin"

	.align 2
Cry_Trevenant::
	.incbin "sound/direct_sound_samples/cries/trevenant.bin"

	.align 2
Cry_Pumpkaboo::
	.incbin "sound/direct_sound_samples/cries/pumpkaboo.bin"

	.align 2
Cry_PumpkabooSuper::
	.incbin "sound/direct_sound_samples/cries/pumpkaboo_super.bin"

	.align 2
Cry_Gourgeist::
	.incbin "sound/direct_sound_samples/cries/gourgeist.bin"

	.align 2
Cry_GourgeistSuper::
	.incbin "sound/direct_sound_samples/cries/gourgeist_super.bin"

	.align 2
Cry_Bergmite::
	.incbin "sound/direct_sound_samples/cries/bergmite.bin"

	.align 2
Cry_Avalugg::
	.incbin "sound/direct_sound_samples/cries/avalugg.bin"

	.align 2
Cry_Noibat::
	.incbin "sound/direct_sound_samples/cries/noibat.bin"

	.align 2
Cry_Noivern::
	.incbin "sound/direct_sound_samples/cries/noivern.bin"

	.align 2
Cry_Xerneas::
	.incbin "sound/direct_sound_samples/cries/xerneas.bin"

	.align 2
Cry_Yveltal::
	.incbin "sound/direct_sound_samples/cries/yveltal.bin"

	.align 2
Cry_Zygarde::
	.incbin "sound/direct_sound_samples/cries/zygarde.bin"

	.align 2
Cry_Diancie::
	.incbin "sound/direct_sound_samples/cries/diancie.bin"

	.align 2
Cry_Hoopa::
	.incbin "sound/direct_sound_samples/cries/hoopa.bin"

	.align 2
Cry_Volcanion::
	.incbin "sound/direct_sound_samples/cries/volcanion.bin"

	.align 2
Cry_Rowlet::
	.incbin "sound/direct_sound_samples/cries/rowlet.bin"

	.align 2
Cry_Dartrix::
	.incbin "sound/direct_sound_samples/cries/dartrix.bin"

	.align 2
Cry_Decidueye::
	.incbin "sound/direct_sound_samples/cries/decidueye.bin"

	.align 2
Cry_Litten::
	.incbin "sound/direct_sound_samples/cries/litten.bin"

	.align 2
Cry_Torracat::
	.incbin "sound/direct_sound_samples/cries/torracat.bin"

	.align 2
Cry_Incineroar::
	.incbin "sound/direct_sound_samples/cries/incineroar.bin"

	.align 2
Cry_Popplio::
	.incbin "sound/direct_sound_samples/cries/popplio.bin"

	.align 2
Cry_Brionne::
	.incbin "sound/direct_sound_samples/cries/brionne.bin"

	.align 2
Cry_Primarina::
	.incbin "sound/direct_sound_samples/cries/primarina.bin"

	.align 2
Cry_Pikipek::
	.incbin "sound/direct_sound_samples/cries/pikipek.bin"

	.align 2
Cry_Trumbeak::
	.incbin "sound/direct_sound_samples/cries/trumbeak.bin"

	.align 2
Cry_Toucannon::
	.incbin "sound/direct_sound_samples/cries/toucannon.bin"

	.align 2
Cry_Yungoos::
	.incbin "sound/direct_sound_samples/cries/yungoos.bin"

	.align 2
Cry_Gumshoos::
	.incbin "sound/direct_sound_samples/cries/gumshoos.bin"

	.align 2
Cry_Grubbin::
	.incbin "sound/direct_sound_samples/cries/grubbin.bin"

	.align 2
Cry_Charjabug::
	.incbin "sound/direct_sound_samples/cries/charjabug.bin"

	.align 2
Cry_Vikavolt::
	.incbin "sound/direct_sound_samples/cries/vikavolt.bin"

	.align 2
Cry_Crabrawler::
	.incbin "sound/direct_sound_samples/cries/crabrawler.bin"

	.align 2
Cry_Crabominable::
	.incbin "sound/direct_sound_samples/cries/crabominable.bin"

	.align 2
Cry_Oricorio::
	.incbin "sound/direct_sound_samples/cries/oricorio.bin"

	.align 2
Cry_Cutiefly::
	.incbin "sound/direct_sound_samples/cries/cutiefly.bin"

	.align 2
Cry_Ribombee::
	.incbin "sound/direct_sound_samples/cries/ribombee.bin"

	.align 2
Cry_Rockruff::
	.incbin "sound/direct_sound_samples/cries/rockruff.bin"

	.align 2
Cry_Lycanroc::
	.incbin "sound/direct_sound_samples/cries/lycanroc.bin"

	.align 2
Cry_Wishiwashi::
	.incbin "sound/direct_sound_samples/cries/wishiwashi.bin"

	.align 2
Cry_Mareanie::
	.incbin "sound/direct_sound_samples/cries/mareanie.bin"

	.align 2
Cry_Toxapex::
	.incbin "sound/direct_sound_samples/cries/toxapex.bin"

	.align 2
Cry_Mudbray::
	.incbin "sound/direct_sound_samples/cries/mudbray.bin"

	.align 2
Cry_Mudsdale::
	.incbin "sound/direct_sound_samples/cries/mudsdale.bin"

	.align 2
Cry_Dewpider::
	.incbin "sound/direct_sound_samples/cries/dewpider.bin"

	.align 2
Cry_Araquanid::
	.incbin "sound/direct_sound_samples/cries/araquanid.bin"

	.align 2
Cry_Fomantis::
	.incbin "sound/direct_sound_samples/cries/fomantis.bin"

	.align 2
Cry_Lurantis::
	.incbin "sound/direct_sound_samples/cries/lurantis.bin"

	.align 2
Cry_Morelull::
	.incbin "sound/direct_sound_samples/cries/morelull.bin"

	.align 2
Cry_Shiinotic::
	.incbin "sound/direct_sound_samples/cries/shiinotic.bin"

	.align 2
Cry_Salandit::
	.incbin "sound/direct_sound_samples/cries/salandit.bin"

	.align 2
Cry_Salazzle::
	.incbin "sound/direct_sound_samples/cries/salazzle.bin"

	.align 2
Cry_Stufful::
	.incbin "sound/direct_sound_samples/cries/stufful.bin"

	.align 2
Cry_Bewear::
	.incbin "sound/direct_sound_samples/cries/bewear.bin"

	.align 2
Cry_Bounsweet::
	.incbin "sound/direct_sound_samples/cries/bounsweet.bin"

	.align 2
Cry_Steenee::
	.incbin "sound/direct_sound_samples/cries/steenee.bin"

	.align 2
Cry_Tsareena::
	.incbin "sound/direct_sound_samples/cries/tsareena.bin"

	.align 2
Cry_Comfey::
	.incbin "sound/direct_sound_samples/cries/comfey.bin"

	.align 2
Cry_Oranguru::
	.incbin "sound/direct_sound_samples/cries/oranguru.bin"

	.align 2
Cry_Passimian::
	.incbin "sound/direct_sound_samples/cries/passimian.bin"

	.align 2
Cry_Wimpod::
	.incbin "sound/direct_sound_samples/cries/wimpod.bin"

	.align 2
Cry_Golisopod::
	.incbin "sound/direct_sound_samples/cries/golisopod.bin"

	.align 2
Cry_Sandygast::
	.incbin "sound/direct_sound_samples/cries/sandygast.bin"

	.align 2
Cry_Palossand::
	.incbin "sound/direct_sound_samples/cries/palossand.bin"

	.align 2
Cry_Pyukumuku::
	.incbin "sound/direct_sound_samples/cries/pyukumuku.bin"

	.align 2
Cry_TypeNull::
	.incbin "sound/direct_sound_samples/cries/type_null.bin"

	.align 2
Cry_Silvally::
	.incbin "sound/direct_sound_samples/cries/silvally.bin"

	.align 2
Cry_Minior::
	.incbin "sound/direct_sound_samples/cries/minior.bin"

	.align 2
Cry_Komala::
	.incbin "sound/direct_sound_samples/cries/komala.bin"

	.align 2
Cry_Turtonator::
	.incbin "sound/direct_sound_samples/cries/turtonator.bin"

	.align 2
Cry_Togedemaru::
	.incbin "sound/direct_sound_samples/cries/togedemaru.bin"

	.align 2
Cry_Mimikyu::
	.incbin "sound/direct_sound_samples/cries/mimikyu.bin"

	.align 2
Cry_Bruxish::
	.incbin "sound/direct_sound_samples/cries/bruxish.bin"

	.align 2
Cry_Drampa::
	.incbin "sound/direct_sound_samples/cries/drampa.bin"

	.align 2
Cry_Dhelmise::
	.incbin "sound/direct_sound_samples/cries/dhelmise.bin"

	.align 2
Cry_JangmoO::
	.incbin "sound/direct_sound_samples/cries/jangmo_o.bin"

	.align 2
Cry_HakamoO::
	.incbin "sound/direct_sound_samples/cries/hakamo_o.bin"

	.align 2
Cry_KommoO::
	.incbin "sound/direct_sound_samples/cries/kommo_o.bin"

	.align 2
Cry_TapuKoko::
	.incbin "sound/direct_sound_samples/cries/tapu_koko.bin"

	.align 2
Cry_TapuLele::
	.incbin "sound/direct_sound_samples/cries/tapu_lele.bin"

	.align 2
Cry_TapuBulu::
	.incbin "sound/direct_sound_samples/cries/tapu_bulu.bin"

	.align 2
Cry_TapuFini::
	.incbin "sound/direct_sound_samples/cries/tapu_fini.bin"

	.align 2
Cry_Cosmog::
	.incbin "sound/direct_sound_samples/cries/cosmog.bin"

	.align 2
Cry_Cosmoem::
	.incbin "sound/direct_sound_samples/cries/cosmoem.bin"

	.align 2
Cry_Solgaleo::
	.incbin "sound/direct_sound_samples/cries/solgaleo.bin"

	.align 2
Cry_Lunala::
	.incbin "sound/direct_sound_samples/cries/lunala.bin"

	.align 2
Cry_Nihilego::
	.incbin "sound/direct_sound_samples/cries/nihilego.bin"

	.align 2
Cry_Buzzwole::
	.incbin "sound/direct_sound_samples/cries/buzzwole.bin"

	.align 2
Cry_Pheromosa::
	.incbin "sound/direct_sound_samples/cries/pheromosa.bin"

	.align 2
Cry_Xurkitree::
	.incbin "sound/direct_sound_samples/cries/xurkitree.bin"

	.align 2
Cry_Celesteela::
	.incbin "sound/direct_sound_samples/cries/celesteela.bin"

	.align 2
Cry_Kartana::
	.incbin "sound/direct_sound_samples/cries/kartana.bin"

	.align 2
Cry_Guzzlord::
	.incbin "sound/direct_sound_samples/cries/guzzlord.bin"

	.align 2
Cry_Necrozma::
	.incbin "sound/direct_sound_samples/cries/necrozma.bin"

	.align 2
Cry_Magearna::
	.incbin "sound/direct_sound_samples/cries/magearna.bin"

	.align 2
Cry_Marshadow::
	.incbin "sound/direct_sound_samples/cries/marshadow.bin"

	.align 2
Cry_Poipole::
	.incbin "sound/direct_sound_samples/cries/poipole.bin"

	.align 2
Cry_Naganadel::
	.incbin "sound/direct_sound_samples/cries/naganadel.bin"

	.align 2
Cry_Stakataka::
	.incbin "sound/direct_sound_samples/cries/stakataka.bin"

	.align 2
Cry_Blacephalon::
	.incbin "sound/direct_sound_samples/cries/blacephalon.bin"

	.align 2
Cry_Zeraora::
	.incbin "sound/direct_sound_samples/cries/zeraora.bin"

	.align 2
Cry_Meltan::
	.incbin "sound/direct_sound_samples/cries/meltan.bin"

	.align 2
Cry_Melmetal::
	.incbin "sound/direct_sound_samples/cries/melmetal.bin"

	.align 2
Cry_Grookey::
	.incbin "sound/direct_sound_samples/cries/grookey.bin"

	.align 2
Cry_Thwackey::
	.incbin "sound/direct_sound_samples/cries/thwackey.bin"

	.align 2
Cry_Rillaboom::
	.incbin "sound/direct_sound_samples/cries/rillaboom.bin"

	.align 2
Cry_Scorbunny::
	.incbin "sound/direct_sound_samples/cries/scorbunny.bin"

	.align 2
Cry_Raboot::
	.incbin "sound/direct_sound_samples/cries/raboot.bin"

	.align 2
Cry_Cinderace::
	.incbin "sound/direct_sound_samples/cries/cinderace.bin"

	.align 2
Cry_Sobble::
	.incbin "sound/direct_sound_samples/cries/sobble.bin"

	.align 2
Cry_Drizzile::
	.incbin "sound/direct_sound_samples/cries/drizzile.bin"

	.align 2
Cry_Inteleon::
	.incbin "sound/direct_sound_samples/cries/inteleon.bin"

	.align 2
Cry_Skwovet::
	.incbin "sound/direct_sound_samples/cries/skwovet.bin"

	.align 2
Cry_Greedent::
	.incbin "sound/direct_sound_samples/cries/greedent.bin"

	.align 2
Cry_Rookidee::
	.incbin "sound/direct_sound_samples/cries/rookidee.bin"

	.align 2
Cry_Corvisquire::
	.incbin "sound/direct_sound_samples/cries/corvisquire.bin"

	.align 2
Cry_Corviknight::
	.incbin "sound/direct_sound_samples/cries/corviknight.bin"

	.align 2
Cry_Blipbug::
	.incbin "sound/direct_sound_samples/cries/blipbug.bin"

	.align 2
Cry_Dottler::
	.incbin "sound/direct_sound_samples/cries/dottler.bin"

	.align 2
Cry_Orbeetle::
	.incbin "sound/direct_sound_samples/cries/orbeetle.bin"

	.align 2
Cry_Nickit::
	.incbin "sound/direct_sound_samples/cries/nickit.bin"

	.align 2
Cry_Thievul::
	.incbin "sound/direct_sound_samples/cries/thievul.bin"

	.align 2
Cry_Gossifleur::
	.incbin "sound/direct_sound_samples/cries/gossifleur.bin"

	.align 2
Cry_Eldegoss::
	.incbin "sound/direct_sound_samples/cries/eldegoss.bin"

	.align 2
Cry_Wooloo::
	.incbin "sound/direct_sound_samples/cries/wooloo.bin"

	.align 2
Cry_Dubwool::
	.incbin "sound/direct_sound_samples/cries/dubwool.bin"

	.align 2
Cry_Chewtle::
	.incbin "sound/direct_sound_samples/cries/chewtle.bin"

	.align 2
Cry_Drednaw::
	.incbin "sound/direct_sound_samples/cries/drednaw.bin"

	.align 2
Cry_Yamper::
	.incbin "sound/direct_sound_samples/cries/yamper.bin"

	.align 2
Cry_Boltund::
	.incbin "sound/direct_sound_samples/cries/boltund.bin"

	.align 2
Cry_Rolycoly::
	.incbin "sound/direct_sound_samples/cries/rolycoly.bin"

	.align 2
Cry_Carkol::
	.incbin "sound/direct_sound_samples/cries/carkol.bin"

	.align 2
Cry_Coalossal::
	.incbin "sound/direct_sound_samples/cries/coalossal.bin"

	.align 2
Cry_Applin::
	.incbin "sound/direct_sound_samples/cries/applin.bin"

	.align 2
Cry_Flapple::
	.incbin "sound/direct_sound_samples/cries/flapple.bin"

	.align 2
Cry_Appletun::
	.incbin "sound/direct_sound_samples/cries/appletun.bin"

	.align 2
Cry_Silicobra::
	.incbin "sound/direct_sound_samples/cries/silicobra.bin"

	.align 2
Cry_Sandaconda::
	.incbin "sound/direct_sound_samples/cries/sandaconda.bin"

	.align 2
Cry_Cramorant::
	.incbin "sound/direct_sound_samples/cries/cramorant.bin"

	.align 2
Cry_Arrokuda::
	.incbin "sound/direct_sound_samples/cries/arrokuda.bin"

	.align 2
Cry_Barraskewda::
	.incbin "sound/direct_sound_samples/cries/barraskewda.bin"

	.align 2
Cry_Toxel::
	.incbin "sound/direct_sound_samples/cries/toxel.bin"

	.align 2
Cry_Toxtricity::
	.incbin "sound/direct_sound_samples/cries/toxtricity.bin"

	.align 2
Cry_Sizzlipede::
	.incbin "sound/direct_sound_samples/cries/sizzlipede.bin"

	.align 2
Cry_Centiskorch::
	.incbin "sound/direct_sound_samples/cries/centiskorch.bin"

	.align 2
Cry_Clobbopus::
	.incbin "sound/direct_sound_samples/cries/clobbopus.bin"

	.align 2
Cry_Grapploct::
	.incbin "sound/direct_sound_samples/cries/grapploct.bin"

	.align 2
Cry_Sinistea::
	.incbin "sound/direct_sound_samples/cries/sinistea.bin"

	.align 2
Cry_Polteageist::
	.incbin "sound/direct_sound_samples/cries/polteageist.bin"

	.align 2
Cry_Hatenna::
	.incbin "sound/direct_sound_samples/cries/hatenna.bin"

	.align 2
Cry_Hattrem::
	.incbin "sound/direct_sound_samples/cries/hattrem.bin"

	.align 2
Cry_Hatterene::
	.incbin "sound/direct_sound_samples/cries/hatterene.bin"

	.align 2
Cry_Impidimp::
	.incbin "sound/direct_sound_samples/cries/impidimp.bin"

	.align 2
Cry_Morgrem::
	.incbin "sound/direct_sound_samples/cries/morgrem.bin"

	.align 2
Cry_Grimmsnarl::
	.incbin "sound/direct_sound_samples/cries/grimmsnarl.bin"

	.align 2
Cry_Obstagoon::
	.incbin "sound/direct_sound_samples/cries/obstagoon.bin"

	.align 2
Cry_Perrserker::
	.incbin "sound/direct_sound_samples/cries/perrserker.bin"

	.align 2
Cry_Cursola::
	.incbin "sound/direct_sound_samples/cries/cursola.bin"

	.align 2
Cry_Sirfetchd::
	.incbin "sound/direct_sound_samples/cries/sirfetchd.bin"

	.align 2
Cry_MrRime::
	.incbin "sound/direct_sound_samples/cries/mr_rime.bin"

	.align 2
Cry_Runerigus::
	.incbin "sound/direct_sound_samples/cries/runerigus.bin"

	.align 2
Cry_Milcery::
	.incbin "sound/direct_sound_samples/cries/milcery.bin"

	.align 2
Cry_Alcremie::
	.incbin "sound/direct_sound_samples/cries/alcremie.bin"

	.align 2
Cry_Falinks::
	.incbin "sound/direct_sound_samples/cries/falinks.bin"

	.align 2
Cry_Pincurchin::
	.incbin "sound/direct_sound_samples/cries/pincurchin.bin"

	.align 2
Cry_Snom::
	.incbin "sound/direct_sound_samples/cries/snom.bin"

	.align 2
Cry_Frosmoth::
	.incbin "sound/direct_sound_samples/cries/frosmoth.bin"

	.align 2
Cry_Stonjourner::
	.incbin "sound/direct_sound_samples/cries/stonjourner.bin"

	.align 2
Cry_Eiscue::
	.incbin "sound/direct_sound_samples/cries/eiscue.bin"

	.align 2
Cry_Indeedee::
	.incbin "sound/direct_sound_samples/cries/indeedee.bin"

	.align 2
Cry_Morpeko::
	.incbin "sound/direct_sound_samples/cries/morpeko.bin"

	.align 2
Cry_Cufant::
	.incbin "sound/direct_sound_samples/cries/cufant.bin"

	.align 2
Cry_Copperajah::
	.incbin "sound/direct_sound_samples/cries/copperajah.bin"

	.align 2
Cry_Dracozolt::
	.incbin "sound/direct_sound_samples/cries/dracozolt.bin"

	.align 2
Cry_Arctozolt::
	.incbin "sound/direct_sound_samples/cries/arctozolt.bin"

	.align 2
Cry_Dracovish::
	.incbin "sound/direct_sound_samples/cries/dracovish.bin"

	.align 2
Cry_Arctovish::
	.incbin "sound/direct_sound_samples/cries/arctovish.bin"

	.align 2
Cry_Duraludon::
	.incbin "sound/direct_sound_samples/cries/duraludon.bin"

	.align 2
Cry_Dreepy::
	.incbin "sound/direct_sound_samples/cries/dreepy.bin"

	.align 2
Cry_Drakloak::
	.incbin "sound/direct_sound_samples/cries/drakloak.bin"

	.align 2
Cry_Dragapult::
	.incbin "sound/direct_sound_samples/cries/dragapult.bin"

	.align 2
Cry_Zacian::
	.incbin "sound/direct_sound_samples/cries/zacian.bin"

	.align 2
Cry_Zamazenta::
	.incbin "sound/direct_sound_samples/cries/zamazenta.bin"

	.align 2
Cry_Eternatus::
	.incbin "sound/direct_sound_samples/cries/eternatus.bin"

	.align 2
Cry_Kubfu::
	.incbin "sound/direct_sound_samples/cries/kubfu.bin"

	.align 2
Cry_Urshifu::
	.incbin "sound/direct_sound_samples/cries/urshifu.bin"

	.align 2
Cry_Zarude::
	.incbin "sound/direct_sound_samples/cries/zarude.bin"

	.align 2
Cry_Regieleki::
	.incbin "sound/direct_sound_samples/cries/regieleki.bin"

	.align 2
Cry_Regidrago::
	.incbin "sound/direct_sound_samples/cries/regidrago.bin"

	.align 2
Cry_Glastrier::
	.incbin "sound/direct_sound_samples/cries/glastrier.bin"

	.align 2
Cry_Spectrier::
	.incbin "sound/direct_sound_samples/cries/spectrier.bin"

	.align 2
Cry_Calyrex::
	.incbin "sound/direct_sound_samples/cries/calyrex.bin"

	.align 2
Cry_Wyrdeer::
	.incbin "sound/direct_sound_samples/cries/wyrdeer.bin"

	.align 2
Cry_Kleavor::
	.incbin "sound/direct_sound_samples/cries/kleavor.bin"

	.align 2
Cry_Ursaluna::
	.incbin "sound/direct_sound_samples/cries/ursaluna.bin"

	.align 2
Cry_Basculegion::
	.incbin "sound/direct_sound_samples/cries/basculegion.bin"

	.align 2
Cry_Sneasler::
	.incbin "sound/direct_sound_samples/cries/sneasler.bin"

	.align 2
Cry_Overqwil::
	.incbin "sound/direct_sound_samples/cries/overqwil.bin"

	.align 2
Cry_Enamorus::
	.incbin "sound/direct_sound_samples/cries/enamorus.bin"

	.align 2
Cry_SlowpokeGalarian::
	.incbin "sound/direct_sound_samples/cries/slowpoke_galarian.bin"

	.align 2
Cry_ShayminSky::
	.incbin "sound/direct_sound_samples/cries/shaymin_sky.bin"

	.align 2
Cry_TornadusTherian::
	.incbin "sound/direct_sound_samples/cries/tornadus_therian.bin"

	.align 2
Cry_ThundurusTherian::
	.incbin "sound/direct_sound_samples/cries/thundurus_therian.bin"

	.align 2
Cry_LandorusTherian::
	.incbin "sound/direct_sound_samples/cries/landorus_therian.bin"

	.align 2
Cry_EnamorusTherian::
	.incbin "sound/direct_sound_samples/cries/enamorus_therian.bin"

	.align 2
Cry_KyuremWhite::
	.incbin "sound/direct_sound_samples/cries/kyurem_white.bin"

	.align 2
Cry_KyuremBlack::
	.incbin "sound/direct_sound_samples/cries/kyurem_black.bin"

	.align 2
Cry_Zygarde10::
	.incbin "sound/direct_sound_samples/cries/zygarde_10.bin"

	.align 2
Cry_ZygardeComplete::
	.incbin "sound/direct_sound_samples/cries/zygarde_complete.bin"

	.align 2
Cry_HoopaUnbound::
	.incbin "sound/direct_sound_samples/cries/hoopa_unbound.bin"

	.align 2
Cry_OricorioPomPom::
	.incbin "sound/direct_sound_samples/cries/oricorio_pom_pom.bin"

	.align 2
Cry_OricorioPau::
	.incbin "sound/direct_sound_samples/cries/oricorio_pau.bin"

	.align 2
Cry_OricorioSensu::
	.incbin "sound/direct_sound_samples/cries/oricorio_sensu.bin"

	.align 2
Cry_LycanrocMidnight::
	.incbin "sound/direct_sound_samples/cries/lycanroc_midnight.bin"

	.align 2
Cry_LycanrocDusk::
	.incbin "sound/direct_sound_samples/cries/lycanroc_dusk.bin"

	.align 2
Cry_NecrozmaDuskMane::
	.incbin "sound/direct_sound_samples/cries/necrozma_dusk_mane.bin"

	.align 2
Cry_NecrozmaDawnWings::
	.incbin "sound/direct_sound_samples/cries/necrozma_dawn_wings.bin"

	.align 2
Cry_NecrozmaUltra::
	.incbin "sound/direct_sound_samples/cries/necrozma_ultra.bin"

	.align 2
Cry_ZacianCrownedSword::
	.incbin "sound/direct_sound_samples/cries/zacian_crowned_sword.bin"

	.align 2
Cry_ZamazentaCrownedShield::
	.incbin "sound/direct_sound_samples/cries/zamazenta_crowned_shield.bin"

	.align 2
Cry_UrshifuRapidStrikeStyle::
	.incbin "sound/direct_sound_samples/cries/urshifu_rapid_strike_style.bin"

	.align 2
Cry_CalyrexIceRider::
	.incbin "sound/direct_sound_samples/cries/calyrex_ice_rider.bin"

	.align 2
Cry_CalyrexShadowRider::
	.incbin "sound/direct_sound_samples/cries/calyrex_shadow_rider.bin"

	.align 2
Cry_EiscueNoiceFace::
	.incbin "sound/direct_sound_samples/cries/eiscue_noice_face.bin"

	.align 2
Cry_FloetteEternalFlower::
	.incbin "sound/direct_sound_samples/cries/floette_eternal_flower.bin"

	.align 2
Cry_IndeedeeFemale::
	.incbin "sound/direct_sound_samples/cries/indeedee_female.bin"

	.align 2
Cry_WishiwashiSchool::
	.incbin "sound/direct_sound_samples/cries/wishiwashi_school.bin"

    .align 2
Cry_Sprigatito::
    .incbin "sound/direct_sound_samples/cries/sprigatito.bin"

    .align 2
Cry_Floragato::
    .incbin "sound/direct_sound_samples/cries/floragato.bin"

    .align 2
Cry_Meowscarada::
    .incbin "sound/direct_sound_samples/cries/meowscarada.bin"

    .align 2
Cry_Fuecoco::
    .incbin "sound/direct_sound_samples/cries/fuecoco.bin"

    .align 2
Cry_Crocalor::
    .incbin "sound/direct_sound_samples/cries/crocalor.bin"

    .align 2
Cry_Skeledirge::
    .incbin "sound/direct_sound_samples/cries/skeledirge.bin"

    .align 2
Cry_Quaxly::
    .incbin "sound/direct_sound_samples/cries/quaxly.bin"

    .align 2
Cry_Quaxwell::
    .incbin "sound/direct_sound_samples/cries/quaxwell.bin"

    .align 2
Cry_Quaquaval::
    .incbin "sound/direct_sound_samples/cries/quaquaval.bin"

    .align 2
Cry_Lechonk::
    .incbin "sound/direct_sound_samples/cries/lechonk.bin"

    .align 2
Cry_Oinkologne::
    .incbin "sound/direct_sound_samples/cries/oinkologne.bin"

    .align 2
Cry_Tarountula::
    .incbin "sound/direct_sound_samples/cries/tarountula.bin"

    .align 2
Cry_Spidops::
    .incbin "sound/direct_sound_samples/cries/spidops.bin"

    .align 2
Cry_Nymble::
    .incbin "sound/direct_sound_samples/cries/nymble.bin"

    .align 2
Cry_Lokix::
    .incbin "sound/direct_sound_samples/cries/lokix.bin"

    .align 2
Cry_Pawmi::
    .incbin "sound/direct_sound_samples/cries/pawmi.bin"

    .align 2
Cry_Pawmo::
    .incbin "sound/direct_sound_samples/cries/pawmo.bin"

    .align 2
Cry_Pawmot::
    .incbin "sound/direct_sound_samples/cries/pawmot.bin"

    .align 2
Cry_Tandemaus::
    .incbin "sound/direct_sound_samples/cries/tandemaus.bin"

    .align 2
Cry_Maushold::
    .incbin "sound/direct_sound_samples/cries/maushold.bin"

    .align 2
Cry_Fidough::
    .incbin "sound/direct_sound_samples/cries/fidough.bin"

    .align 2
Cry_Dachsbun::
    .incbin "sound/direct_sound_samples/cries/dachsbun.bin"

    .align 2
Cry_Smoliv::
    .incbin "sound/direct_sound_samples/cries/smoliv.bin"

    .align 2
Cry_Dolliv::
    .incbin "sound/direct_sound_samples/cries/dolliv.bin"

    .align 2
Cry_Arboliva::
    .incbin "sound/direct_sound_samples/cries/arboliva.bin"

    .align 2
Cry_Squawkabilly::
    .incbin "sound/direct_sound_samples/cries/squawkabilly.bin"

    .align 2
Cry_Nacli::
    .incbin "sound/direct_sound_samples/cries/nacli.bin"

    .align 2
Cry_Naclstack::
    .incbin "sound/direct_sound_samples/cries/naclstack.bin"

    .align 2
Cry_Garganacl::
    .incbin "sound/direct_sound_samples/cries/garganacl.bin"

    .align 2
Cry_Charcadet::
    .incbin "sound/direct_sound_samples/cries/charcadet.bin"

    .align 2
Cry_Armarouge::
    .incbin "sound/direct_sound_samples/cries/armarouge.bin"

    .align 2
Cry_Ceruledge::
    .incbin "sound/direct_sound_samples/cries/ceruledge.bin"

    .align 2
Cry_Tadbulb::
    .incbin "sound/direct_sound_samples/cries/tadbulb.bin"

    .align 2
Cry_Bellibolt::
    .incbin "sound/direct_sound_samples/cries/bellibolt.bin"

    .align 2
Cry_Wattrel::
    .incbin "sound/direct_sound_samples/cries/wattrel.bin"

    .align 2
Cry_Kilowattrel::
    .incbin "sound/direct_sound_samples/cries/kilowattrel.bin"

    .align 2
Cry_Maschiff::
    .incbin "sound/direct_sound_samples/cries/maschiff.bin"

    .align 2
Cry_Mabosstiff::
    .incbin "sound/direct_sound_samples/cries/mabosstiff.bin"

    .align 2
Cry_Shroodle::
    .incbin "sound/direct_sound_samples/cries/shroodle.bin"

    .align 2
Cry_Grafaiai::
    .incbin "sound/direct_sound_samples/cries/grafaiai.bin"

    .align 2
Cry_Bramblin::
    .incbin "sound/direct_sound_samples/cries/bramblin.bin"

    .align 2
Cry_Brambleghast::
    .incbin "sound/direct_sound_samples/cries/brambleghast.bin"

    .align 2
Cry_Toedscool::
    .incbin "sound/direct_sound_samples/cries/toedscool.bin"

    .align 2
Cry_Toedscruel::
    .incbin "sound/direct_sound_samples/cries/toedscruel.bin"

    .align 2
Cry_Klawf::
    .incbin "sound/direct_sound_samples/cries/klawf.bin"

    .align 2
Cry_Capsakid::
    .incbin "sound/direct_sound_samples/cries/capsakid.bin"

    .align 2
Cry_Scovillain::
    .incbin "sound/direct_sound_samples/cries/scovillain.bin"

    .align 2
Cry_Rellor::
    .incbin "sound/direct_sound_samples/cries/rellor.bin"

    .align 2
Cry_Rabsca::
    .incbin "sound/direct_sound_samples/cries/rabsca.bin"

    .align 2
Cry_Flittle::
    .incbin "sound/direct_sound_samples/cries/flittle.bin"

    .align 2
Cry_Espathra::
    .incbin "sound/direct_sound_samples/cries/espathra.bin"

    .align 2
Cry_Tinkatink::
    .incbin "sound/direct_sound_samples/cries/tinkatink.bin"

    .align 2
Cry_Tinkatuff::
    .incbin "sound/direct_sound_samples/cries/tinkatuff.bin"

    .align 2
Cry_Tinkaton::
    .incbin "sound/direct_sound_samples/cries/tinkaton.bin"

    .align 2
Cry_Wiglett::
    .incbin "sound/direct_sound_samples/cries/wiglett.bin"

    .align 2
Cry_Wugtrio::
    .incbin "sound/direct_sound_samples/cries/wugtrio.bin"

    .align 2
Cry_Bombirdier::
    .incbin "sound/direct_sound_samples/cries/bombirdier.bin"

    .align 2
Cry_Finizen::
    .incbin "sound/direct_sound_samples/cries/finizen.bin"

    .align 2
Cry_Palafin::
    .incbin "sound/direct_sound_samples/cries/palafin.bin"

    .align 2
Cry_Varoom::
    .incbin "sound/direct_sound_samples/cries/varoom.bin"

    .align 2
Cry_Revavroom::
    .incbin "sound/direct_sound_samples/cries/revavroom.bin"

    .align 2
Cry_Cyclizar::
    .incbin "sound/direct_sound_samples/cries/cyclizar.bin"

    .align 2
Cry_Orthworm::
    .incbin "sound/direct_sound_samples/cries/orthworm.bin"

    .align 2
Cry_Glimmet::
    .incbin "sound/direct_sound_samples/cries/glimmet.bin"

    .align 2
Cry_Glimmora::
    .incbin "sound/direct_sound_samples/cries/glimmora.bin"

    .align 2
Cry_Greavard::
    .incbin "sound/direct_sound_samples/cries/greavard.bin"

    .align 2
Cry_Houndstone::
    .incbin "sound/direct_sound_samples/cries/houndstone.bin"

    .align 2
Cry_Flamigo::
    .incbin "sound/direct_sound_samples/cries/flamigo.bin"

    .align 2
Cry_Cetoddle::
    .incbin "sound/direct_sound_samples/cries/cetoddle.bin"

    .align 2
Cry_Cetitan::
    .incbin "sound/direct_sound_samples/cries/cetitan.bin"

    .align 2
Cry_Veluza::
    .incbin "sound/direct_sound_samples/cries/veluza.bin"

    .align 2
Cry_Dondozo::
    .incbin "sound/direct_sound_samples/cries/dondozo.bin"

    .align 2
Cry_Tatsugiri::
    .incbin "sound/direct_sound_samples/cries/tatsugiri.bin"

    .align 2
Cry_Annihilape::
    .incbin "sound/direct_sound_samples/cries/annihilape.bin"

    .align 2
Cry_Clodsire::
    .incbin "sound/direct_sound_samples/cries/clodsire.bin"

    .align 2
Cry_Farigiraf::
    .incbin "sound/direct_sound_samples/cries/farigiraf.bin"

    .align 2
Cry_Dudunsparce::
    .incbin "sound/direct_sound_samples/cries/dudunsparce.bin"

    .align 2
Cry_Kingambit::
    .incbin "sound/direct_sound_samples/cries/kingambit.bin"

    .align 2
Cry_GreatTusk::
    .incbin "sound/direct_sound_samples/cries/greattusk.bin"

    .align 2
Cry_ScreamTail::
    .incbin "sound/direct_sound_samples/cries/screamtail.bin"

    .align 2
Cry_BruteBonnet::
    .incbin "sound/direct_sound_samples/cries/brutebonnet.bin"

    .align 2
Cry_FlutterMane::
    .incbin "sound/direct_sound_samples/cries/fluttermane.bin"

    .align 2
Cry_SlitherWing::
    .incbin "sound/direct_sound_samples/cries/slitherwing.bin"

    .align 2
Cry_SandyShocks::
    .incbin "sound/direct_sound_samples/cries/sandyshocks.bin"

    .align 2
Cry_IronTreads::
    .incbin "sound/direct_sound_samples/cries/irontreads.bin"

    .align 2
Cry_IronBundle::
    .incbin "sound/direct_sound_samples/cries/ironbundle.bin"

    .align 2
Cry_IronHands::
    .incbin "sound/direct_sound_samples/cries/ironhands.bin"

    .align 2
Cry_IronJugulis::
    .incbin "sound/direct_sound_samples/cries/ironjugulis.bin"

    .align 2
Cry_IronMoth::
    .incbin "sound/direct_sound_samples/cries/ironmoth.bin"

    .align 2
Cry_IronThorns::
    .incbin "sound/direct_sound_samples/cries/ironthorns.bin"

    .align 2
Cry_Frigibax::
    .incbin "sound/direct_sound_samples/cries/frigibax.bin"

    .align 2
Cry_Arctibax::
    .incbin "sound/direct_sound_samples/cries/arctibax.bin"

    .align 2
Cry_Baxcalibur::
    .incbin "sound/direct_sound_samples/cries/baxcalibur.bin"

    .align 2
Cry_Gimmighoul::
    .incbin "sound/direct_sound_samples/cries/gimmighoul.bin"

    .align 2
Cry_Gholdengo::
    .incbin "sound/direct_sound_samples/cries/gholdengo.bin"

    .align 2
Cry_WoChien::
    .incbin "sound/direct_sound_samples/cries/wochien.bin"

    .align 2
Cry_ChienPao::
    .incbin "sound/direct_sound_samples/cries/chienpao.bin"

    .align 2
Cry_TingLu::
    .incbin "sound/direct_sound_samples/cries/tinglu.bin"

    .align 2
Cry_ChiYu::
    .incbin "sound/direct_sound_samples/cries/chiyu.bin"

    .align 2
Cry_RoaringMoon::
    .incbin "sound/direct_sound_samples/cries/roaringmoon.bin"

    .align 2
Cry_IronValiant::
    .incbin "sound/direct_sound_samples/cries/ironvaliant.bin"

    .align 2
Cry_Koraidon::
    .incbin "sound/direct_sound_samples/cries/koraidon.bin"

    .align 2
Cry_Miraidon::
    .incbin "sound/direct_sound_samples/cries/miraidon.bin"

    .align 2
Cry_WalkingWake::
    .incbin "sound/direct_sound_samples/cries/walkingwake.bin"

    .align 2
Cry_IronLeaves::
    .incbin "sound/direct_sound_samples/cries/ironleaves.bin"

    .align 2
Cry_OinkologneFemale::
    .incbin "sound/direct_sound_samples/cries/oinkologne_female.bin"

    .align 2
Cry_Dipplin::
    .incbin "sound/direct_sound_samples/cries/dipplin.bin"

    .align 2
Cry_Poltchageist::
    .incbin "sound/direct_sound_samples/cries/poltchageist.bin"

    .align 2
Cry_Sinistcha::
    .incbin "sound/direct_sound_samples/cries/sinistcha.bin"

    .align 2
Cry_Okidogi::
    .incbin "sound/direct_sound_samples/cries/okidogi.bin"

    .align 2
Cry_Munkidori::
    .incbin "sound/direct_sound_samples/cries/munkidori.bin"

    .align 2
Cry_Fezandipiti::
    .incbin "sound/direct_sound_samples/cries/fezandipiti.bin"

    .align 2
Cry_Ogerpon::
    .incbin "sound/direct_sound_samples/cries/ogerpon.bin"

    .align 2
Cry_UrsalunaBloodmoon::
    .incbin "sound/direct_sound_samples/cries/ursaluna_bloodmoon.bin"

	.align 2
Cry_VenusaurMega::
	.incbin "sound/direct_sound_samples/cries/mega_venusaur.bin"

	.align 2
Cry_CharizardMegaX::
	.incbin "sound/direct_sound_samples/cries/mega_charizard_x.bin"

	.align 2
Cry_CharizardMegaY::
	.incbin "sound/direct_sound_samples/cries/mega_charizard_y.bin"

	.align 2
Cry_BlastoiseMega::
	.incbin "sound/direct_sound_samples/cries/mega_blastoise.bin"

	.align 2
Cry_BeedrillMega::
	.incbin "sound/direct_sound_samples/cries/mega_beedrill.bin"

	.align 2
Cry_PidgeotMega::
	.incbin "sound/direct_sound_samples/cries/mega_pidgeot.bin"

	.align 2
Cry_AlakazamMega::
	.incbin "sound/direct_sound_samples/cries/mega_alakazam.bin"

	.align 2
Cry_SlowbroMega::
	.incbin "sound/direct_sound_samples/cries/mega_slowbro.bin"

	.align 2
Cry_GengarMega::
	.incbin "sound/direct_sound_samples/cries/mega_gengar.bin"

	.align 2
Cry_KangaskhanMega::
	.incbin "sound/direct_sound_samples/cries/mega_kangaskhan.bin"

	.align 2
Cry_PinsirMega::
	.incbin "sound/direct_sound_samples/cries/mega_pinsir.bin"

	.align 2
Cry_GyaradosMega::
	.incbin "sound/direct_sound_samples/cries/mega_gyarados.bin"

	.align 2
Cry_AerodactylMega::
	.incbin "sound/direct_sound_samples/cries/mega_aerodactyl.bin"

	.align 2
Cry_MewtwoMegaX::
	.incbin "sound/direct_sound_samples/cries/mega_mewtwo_x.bin"

	.align 2
Cry_MewtwoMegaY::
	.incbin "sound/direct_sound_samples/cries/mega_mewtwo_y.bin"

	.align 2
Cry_AmpharosMega::
	.incbin "sound/direct_sound_samples/cries/mega_ampharos.bin"

	.align 2
Cry_SteelixMega::
	.incbin "sound/direct_sound_samples/cries/mega_steelix.bin"

	.align 2
Cry_ScizorMega::
	.incbin "sound/direct_sound_samples/cries/mega_scizor.bin"

	.align 2
Cry_HeracrossMega::
	.incbin "sound/direct_sound_samples/cries/mega_heracross.bin"

	.align 2
Cry_HoundoomMega::
	.incbin "sound/direct_sound_samples/cries/mega_houndoom.bin"

	.align 2
Cry_TyranitarMega::
	.incbin "sound/direct_sound_samples/cries/mega_tyranitar.bin"

	.align 2
Cry_SceptileMega::
	.incbin "sound/direct_sound_samples/cries/mega_sceptile.bin"

	.align 2
Cry_BlazikenMega::
	.incbin "sound/direct_sound_samples/cries/mega_blaziken.bin"

	.align 2
Cry_SwampertMega::
	.incbin "sound/direct_sound_samples/cries/mega_swampert.bin"

	.align 2
Cry_GardevoirMega::
	.incbin "sound/direct_sound_samples/cries/mega_gardevoir.bin"

	.align 2
Cry_SableyeMega::
	.incbin "sound/direct_sound_samples/cries/mega_sableye.bin"

	.align 2
Cry_MawileMega::
	.incbin "sound/direct_sound_samples/cries/mega_mawile.bin"

	.align 2
Cry_AggronMega::
	.incbin "sound/direct_sound_samples/cries/mega_aggron.bin"

	.align 2
Cry_MedichamMega::
	.incbin "sound/direct_sound_samples/cries/mega_medicham.bin"

	.align 2
Cry_ManectricMega::
	.incbin "sound/direct_sound_samples/cries/mega_manectric.bin"

	.align 2
Cry_SharpedoMega::
	.incbin "sound/direct_sound_samples/cries/mega_sharpedo.bin"

	.align 2
Cry_CameruptMega::
	.incbin "sound/direct_sound_samples/cries/mega_camerupt.bin"

	.align 2
Cry_AltariaMega::
	.incbin "sound/direct_sound_samples/cries/mega_altaria.bin"

	.align 2
Cry_BanetteMega::
	.incbin "sound/direct_sound_samples/cries/mega_banette.bin"

	.align 2
Cry_AbsolMega::
	.incbin "sound/direct_sound_samples/cries/mega_absol.bin"

	.align 2
Cry_GlalieMega::
	.incbin "sound/direct_sound_samples/cries/mega_glalie.bin"

	.align 2
Cry_SalamenceMega::
	.incbin "sound/direct_sound_samples/cries/mega_salamence.bin"

	.align 2
Cry_MetagrossMega::
	.incbin "sound/direct_sound_samples/cries/mega_metagross.bin"

	.align 2
Cry_LatiasMega::
	.incbin "sound/direct_sound_samples/cries/mega_latias.bin"

	.align 2
Cry_LatiosMega::
	.incbin "sound/direct_sound_samples/cries/mega_latios.bin"

	.align 2
Cry_LopunnyMega::
	.incbin "sound/direct_sound_samples/cries/mega_lopunny.bin"

	.align 2
Cry_GarchompMega::
	.incbin "sound/direct_sound_samples/cries/mega_garchomp.bin"

	.align 2
Cry_LucarioMega::
	.incbin "sound/direct_sound_samples/cries/mega_lucario.bin"

	.align 2
Cry_AbomasnowMega::
	.incbin "sound/direct_sound_samples/cries/mega_abomasnow.bin"

	.align 2
Cry_GalladeMega::
	.incbin "sound/direct_sound_samples/cries/mega_gallade.bin"

	.align 2
Cry_AudinoMega::
	.incbin "sound/direct_sound_samples/cries/mega_audino.bin"

	.align 2
Cry_DiancieMega::
	.incbin "sound/direct_sound_samples/cries/mega_diancie.bin"

	.align 2
Cry_RayquazaMega::
	.incbin "sound/direct_sound_samples/cries/mega_rayquaza.bin"

	.align 2
Cry_KyogrePrimal::
	.incbin "sound/direct_sound_samples/cries/primal_kyogre.bin"

	.align 2
Cry_GroudonPrimal::
	.incbin "sound/direct_sound_samples/cries/primal_groudon.bin"

	.align 2
Cry_ToxtricityLowKey::
	.incbin "sound/direct_sound_samples/cries/toxtricity-lowkey.bin"

	.align 2
Cry_MorpekoHangry::
	.incbin "sound/direct_sound_samples/cries/morpeko-hangry.bin"

	.align 2
Cry_EternatusEternamax::
	.incbin "sound/direct_sound_samples/cries/eternatus-eternamax.bin"

	.align 2
Cry_Archaludon::
	.incbin "sound/direct_sound_samples/cries/archaludon.bin"

	.align 2
Cry_Hydrapple::
	.incbin "sound/direct_sound_samples/cries/hydrapple.bin"

	.align 2
Cry_GougingFire::
	.incbin "sound/direct_sound_samples/cries/gougingfire.bin"

	.align 2
Cry_RagingBolt::
	.incbin "sound/direct_sound_samples/cries/ragingbolt.bin"

	.align 2
Cry_IronBoulder::
	.incbin "sound/direct_sound_samples/cries/ironboulder.bin"

	.align 2
Cry_IronCrown::
	.incbin "sound/direct_sound_samples/cries/ironcrown.bin"

	.align 2
Cry_Terapagos::
	.incbin "sound/direct_sound_samples/cries/terapagos.bin"

	.align 2
Cry_Pecharunt::
	.incbin "sound/direct_sound_samples/cries/pecharunt.bin"

	.align 2
Cry_GimmighoulRoaming::
	.incbin "sound/direct_sound_samples/cries/gimmighoul-roaming.bin"
