.include "sound/voicegroups/voicegroup000.inc"
.include "sound/voicegroups/voicegroup001.inc"
.include "sound/voicegroups/voicegroup002.inc"
.include "sound/voicegroups/voicegroup003.inc"
.include "sound/voicegroups/voicegroup004.inc"
.include "sound/voicegroups/voicegroup005.inc"
.include "sound/voicegroups/voicegroup006.inc"
.include "sound/voicegroups/voicegroup007.inc"
.include "sound/voicegroups/voicegroup008.inc"
.include "sound/voicegroups/voicegroup009.inc"
.include "sound/voicegroups/voicegroup010.inc"
.include "sound/voicegroups/voicegroup011.inc"
.include "sound/voicegroups/voicegroup012.inc"
.include "sound/voicegroups/voicegroup127.inc"
.include "sound/voicegroups/voicegroup128.inc"
.include "sound/cry_tables.inc"
.include "sound/voicegroups/voicegroup129.inc"
.include "sound/voicegroups/voicegroup130.inc"
.include "sound/voicegroups/voicegroup131.inc"
.include "sound/voicegroups/voicegroup132.inc"
.include "sound/voicegroups/voicegroup133.inc"
.include "sound/voicegroups/voicegroup134.inc"
.include "sound/voicegroups/voicegroup135.inc"
.include "sound/voicegroups/voicegroup136.inc"
.include "sound/voicegroups/voicegroup137.inc"
.include "sound/voicegroups/voicegroup138.inc"
.include "sound/voicegroups/voicegroup139.inc"
.include "sound/voicegroups/voicegroup140.inc"
.include "sound/voicegroups/voicegroup141.inc"
.include "sound/voicegroups/voicegroup142.inc"
.include "sound/voicegroups/voicegroup143.inc"
.include "sound/voicegroups/voicegroup144.inc"
.include "sound/voicegroups/voicegroup145.inc"
.include "sound/voicegroups/voicegroup146.inc"
.include "sound/voicegroups/voicegroup147.inc"
.include "sound/voicegroups/voicegroup148.inc"
.include "sound/voicegroups/voicegroup149.inc"
.include "sound/voicegroups/voicegroup150.inc"
.include "sound/voicegroups/voicegroup151.inc"
.include "sound/voicegroups/voicegroup152.inc"
.include "sound/voicegroups/voicegroup153.inc"
.include "sound/voicegroups/voicegroup154.inc"
.include "sound/voicegroups/voicegroup155.inc"
.include "sound/voicegroups/voicegroup156.inc"
.include "sound/voicegroups/voicegroup157.inc"
.include "sound/voicegroups/voicegroup158.inc"
.include "sound/voicegroups/voicegroup159.inc"
.include "sound/voicegroups/voicegroup160.inc"
.include "sound/voicegroups/voicegroup161.inc"
.include "sound/voicegroups/voicegroup162.inc"
.include "sound/voicegroups/voicegroup163.inc"
.include "sound/voicegroups/voicegroup164.inc"
.include "sound/voicegroups/voicegroup165.inc"
.include "sound/voicegroups/voicegroup166.inc"
.include "sound/voicegroups/voicegroup167.inc"
.include "sound/voicegroups/voicegroup168.inc"
.include "sound/voicegroups/voicegroup169.inc"
.include "sound/voicegroups/voicegroup170.inc"
.include "sound/voicegroups/voicegroup171.inc"
.include "sound/voicegroups/voicegroup172.inc"
.include "sound/voicegroups/voicegroup173.inc"
.include "sound/voicegroups/voicegroup174.inc"
.include "sound/voicegroups/voicegroup175.inc"
.include "sound/voicegroups/voicegroup176.inc"
.include "sound/voicegroups/voicegroup177.inc"
.include "sound/voicegroups/voicegroup178.inc"
.include "sound/voicegroups/voicegroup179.inc"
.include "sound/voicegroups/voicegroup180.inc"
.include "sound/voicegroups/voicegroup181.inc"
.include "sound/voicegroups/voicegroup182.inc"
.include "sound/voicegroups/voicegroup183.inc"
.include "sound/voicegroups/voicegroup184.inc"
.include "sound/voicegroups/voicegroup185.inc"
.include "sound/voicegroups/voicegroup186.inc"
.include "sound/voicegroups/voicegroup187.inc"
.include "sound/voicegroups/voicegroup188.inc"
.include "sound/voicegroups/voicegroup189.inc"
.include "sound/voicegroups/voicegroup190.inc"

.include "sound/voicegroups/HGSS_Inst.inc"
.include "sound/voicegroups/voicegroup191.inc" @ HGSS BANK_BASIC
.include "sound/voicegroups/voicegroup192.inc" @ HGSS BANK_BGM_FIELD5
.include "sound/voicegroups/voicegroup193.inc" @ HGSS BANK_BGM_BATTLE1
.include "sound/voicegroups/voicegroup194.inc" @ HGSS BANK_BGM_BATTLE2
.include "sound/voicegroups/voicegroup195.inc" @ HGSS BANK_BGM_BATTLE3
.include "sound/voicegroups/voicegroup196.inc" @ HGSS BANK_BGM_BATTLE4
.include "sound/voicegroups/voicegroup197.inc" @ HGSS BANK_BGM_BATTLE5
.include "sound/voicegroups/voicegroup198.inc" @ HGSS BANK_BGM_BATTLE6
.include "sound/voicegroups/voicegroup199.inc" @ HGSS BANK_BGM_BATTLE7
.include "sound/voicegroups/voicegroup200.inc" @ HGSS BANK_BGM_BATTLE8
.include "sound/voicegroups/voicegroup201.inc" @ HGSS BANK_BGM_DUNGEON1
.include "sound/voicegroups/voicegroup202.inc" @ HGSS BANK_BGM_DUNGEON2
.include "sound/voicegroups/voicegroup203.inc" @ HGSS BANK_BGM_DUNGEON3
.include "sound/voicegroups/voicegroup204.inc" @ HGSS BANK_BGM_DUNGEON4
.include "sound/voicegroups/voicegroup205.inc" @ HGSS BANK_BGM_DUNGEON5
.include "sound/voicegroups/voicegroup206.inc" @ HGSS BANK_BGM_OPEND
.include "sound/voicegroups/voicegroup207.inc" @ HGSS BANK_BGM_ARCEUS

.include "sound/voicegroups/BW_Inst.inc"
.include "sound/voicegroups/voicegroup208.inc" @ BW intro fight
.include "sound/voicegroups/voicegroup209.inc" @ BW title
.include "sound/voicegroups/voicegroup210.inc" @ BW route 4
.include "sound/voicegroups/voicegroup211.inc" @ BW aspertia
.include "sound/voicegroups/voicegroup212.inc" @ BW lab
.include "sound/voicegroups/voicegroup213.inc" @ BW key item fanfare
.include "sound/voicegroups/voicegroup214.inc" @ BW evolution complete fanfare
.include "sound/voicegroups/voicegroup215.inc" @ BW level up fanfare
.include "sound/voicegroups/voicegroup216.inc" @ BW egg fanfare
.include "sound/voicegroups/voicegroup217.inc" @ BW item fanfare
.include "sound/voicegroups/voicegroup218.inc" @ BW n encounter
.include "sound/voicegroups/voicegroup219.inc" @ BW trainer victory
.include "sound/voicegroups/voicegroup220.inc" @ BW heal fanfare
.include "sound/voicegroups/voicegroup221.inc" @ BW badge fanfare
.include "sound/voicegroups/voicegroup222.inc" @ BW tm fanfare
.include "sound/voicegroups/voicegroup223.inc" @ BW berry fanfare
.include "sound/voicegroups/voicegroup224.inc" @ BW move deleter fanfare
.include "sound/voicegroups/voicegroup225.inc" @ BW dex rating 2 fanfare
.include "sound/voicegroups/voicegroup226.inc" @ BW evolution intro
.include "sound/voicegroups/voicegroup227.inc" @ BW evolution
.include "sound/voicegroups/voicegroup228.inc" @ BW trainer battle
.include "sound/voicegroups/voicegroup229.inc" @ BW low health
.include "sound/voicegroups/voicegroup230.inc" @ BW wild battle
.include "sound/voicegroups/voicegroup231.inc" @ BW wild victory
.include "sound/voicegroups/voicegroup232.inc" @ BW route 1
.include "sound/voicegroups/voicegroup233.inc" @ BW n battle
.include "sound/voicegroups/voicegroup234.inc" @ BW plasma victory
.include "sound/voicegroups/voicegroup235.inc" @ BW gym leader victory
.include "sound/voicegroups/voicegroup236.inc" @ BW poke center
.include "sound/voicegroups/voicegroup237.inc" @ BW striaton
.include "sound/voicegroups/voicegroup238.inc" @ BW route 2
.include "sound/voicegroups/voicegroup239.inc" @ BW dreamyard
.include "sound/voicegroups/voicegroup240.inc" @ BW mart
.include "sound/voicegroups/voicegroup241.inc" @ BW gate
.include "sound/voicegroups/voicegroup242.inc" @ BW gym
.include "sound/voicegroups/voicegroup243.inc" @ BW nacrene
.include "sound/voicegroups/voicegroup244.inc" @ BW gym leader final mon
.include "sound/voicegroups/voicegroup245.inc" @ BW gym leader battle
.include "sound/voicegroups/voicegroup246.inc" @ BW follow me
.include "sound/voicegroups/voicegroup247.inc" @ BW boy encounter
.include "sound/voicegroups/voicegroup248.inc" @ BW girl encounter
.include "sound/voicegroups/voicegroup249.inc" @ BW plasma encounter
.include "sound/voicegroups/voicegroup250.inc" @ BW twins encounter
.include "sound/voicegroups/voicegroup251.inc" @ BW ace trainer encounter
.include "sound/voicegroups/voicegroup252.inc" @ BW roughneck encounter
.include "sound/voicegroups/voicegroup253.inc" @ BW lady encounter
.include "sound/voicegroups/voicegroup254.inc" @ BW cyclist encounter
.include "sound/voicegroups/voicegroup255.inc" @ BW psychic encounter
.include "sound/voicegroups/voicegroup256.inc" @ BW scientist encounter
.include "sound/voicegroups/voicegroup257.inc" @ BW pokefan encounter
.include "sound/voicegroups/voicegroup258.inc" @ BW hiker encounter
.include "sound/voicegroups/voicegroup259.inc" @ BW clerk encounter
.include "sound/voicegroups/voicegroup260.inc" @ BW gentleman encounter
.include "sound/voicegroups/voicegroup261.inc" @ BW chargestone cave
.include "sound/voicegroups/voicegroup262.inc" @ BW cold storage
.include "sound/voicegroups/voicegroup263.inc" @ BW dragonspiral tower
.include "sound/voicegroups/voicegroup264.inc" @ BW plasma battle
.include "sound/voicegroups/voicegroup265.inc" @ BW elite four battle
.include "sound/voicegroups/voicegroup266.inc" @ BW ghetsis battle
.include "sound/voicegroups/voicegroup267.inc" @ BW n final battle
.include "sound/voicegroups/voicegroup268.inc" @ BW kyurem battle
.include "sound/voicegroups/voicegroup269.inc" @ BW legend battle
.include "sound/voicegroups/voicegroup270.inc" @ BW strong wild battle
.include "sound/voicegroups/voicegroup271.inc" @ BW regi battle
.include "sound/voicegroups/voicegroup272.inc" @ BW icirrus
.include "sound/voicegroups/voicegroup273.inc" @ BW accumula
.include "sound/voicegroups/voicegroup274.inc" @ BW castelia
.include "sound/voicegroups/voicegroup275.inc" @ BW route 6
.include "sound/voicegroups/voicegroup276.inc" @ BW bicycle
.include "sound/voicegroups/voicegroup277.inc" @ BW royal unova
.include "sound/voicegroups/voicegroup278.inc" @ BW opelucid (white)
.include "sound/voicegroups/voicegroup279.inc" @ BW opelucid (black)
.include "sound/voicegroups/voicegroup280.inc" @ BW driftveil
.include "sound/voicegroups/voicegroup281.inc" @ BW plasma theme
.include "sound/voicegroups/voicegroup282.inc" @ BW nimbasa
.include "sound/voicegroups/voicegroup283.inc" @ BW n castle bridge
.include "sound/voicegroups/voicegroup284.inc" @ BW pokemon league
.include "sound/voicegroups/voicegroup285.inc" @ BW victory road
.include "sound/voicegroups/voicegroup286.inc" @ BW surf
.include "sound/voicegroups/voicegroup287.inc" @ BW hall of fame
.include "sound/voicegroups/voicegroup288.inc" @ BW n's farewell
.include "sound/voicegroups/voicegroup289.inc" @ BW someone's entralink
