	.align 2
voicegroup216::
	voice_directsound 60, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_60, 255, 242, 191, 197	@ 127/100/110/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_69, 255, 242, 191, 197	@ 127/100/110/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_77, 255, 242, 191, 197	@ 122/100/110/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_84, 255, 242, 191, 197	@ 122/100/110/118/ 64
