	.align 2
voicegroup259::
	voice_directsound 60, 0, DirectSoundWaveData_penis_saw, 255, 160, 99, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_kick, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_chh, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_ohh, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_snare, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_tri, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_square, 255, 128, 0, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_bass, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_tom, 255, 212, 0, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_crash, 255, 224, 0, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_string, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_screm, 255, 0, 255, 0
	voice_directsound 60, 0, DirectSoundWaveData_penis_saw, 255, 160, 0, 0
