	.align 2
voicegroup221::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_flute_sus_60, 255, 246, 159, 197	@ 127/ 90/100/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_flute_sus_69, 255, 246, 127, 197	@ 127/ 90/ 90/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_flute_sus_77, 255, 246, 127, 197	@ 127/ 90/ 90/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_flute_sus_84, 255, 246, 78, 197	@ 127/ 90/ 70/118/ 64
