	.align 2
voicegroup236:: @ BW poke center
	voice_keysplit BW_Electric_Piano, KeySplitTable_2oct + 22
	voice_keysplit BW_Vibraphone, KeySplitTable_2oct + 9
	voice_keysplit BW_Marimba, KeySplitTable_3oct + 16
	voice_keysplit BW_Nylon_Guitar, KeySplitTable_int_8_9 + 19
	voice_keysplit BW_Fretless_Bass, KeySplitTable_2oct + 23
	voice_keysplit BW_Strings, KeySplitTable_int_8_9_8 + 13
	voice_keysplit BW_Clarinet, KeySplitTable_int_9 + 5
	voice_keysplit BW_Akai_Flute, KeySplitTable_int_7_0 + 0
	voice_keysplit_all HGSS_Drumset_1 - 0xc * 29
