	.align 2
voicegroup194::
	voice_directsound 36, 0, DirectSoundWaveData_dp_sd90_french_accordion_36, A(127), D(127), S(127), R(118)
	voice_directsound 48, 0, DirectSoundWaveData_dp_sd90_french_accordion_48, A(127), D(127), S(127), R(118)
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_french_accordion_60, A(120), D(120), S(117), R(118)
	voice_directsound 72, 0, DirectSoundWaveData_dp_sd90_french_accordion_72, A(118), D(120), S(110), R(118)
