	.align 2
voicegroup228::
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_cello_ensemble_pizz_43, 255, 242, 25, 208	@ 127/100/ 40/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_cello_ensemble_pizz_52, 255, 242, 25, 208	@ 127/100/ 40/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_violin_ensemble_pizz_60, 255, 242, 25, 208	@ 127/100/ 40/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_violin_ensemble_pizz_69, 255, 242, 25, 208	@ 127/100/ 40/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_violin_ensemble_pizz_77, 255, 239, 25, 208	@ 127/105/ 40/116/ 64
