	.align 2
voicegroup195::
	voice_directsound 36, 0, DirectSoundWaveData_dp_sd90_strings2_36, A(127), D(100), S(120), R(116)
	voice_directsound 48, 0, DirectSoundWaveData_dp_sd90_strings2_48, A(127), D(105), S(110), R(116)
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_strings2_60, A(122), D(110), S(100), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_dp_sd90_strings2_72, A(122), D(115), S(90), R(116)
