	.align 2
voicegroup275::
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 255, 0, 255, 44 @ straight
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 255, 222, 0, 44 @ fade 1
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 255, 235, 0, 44 @ fade 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 255, 242, 0, 44 @ fade 3
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 255, 246, 0, 44 @ fade 4
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 255, 248, 0, 44 @ fade 5
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 255, 250, 0, 44 @ fade 6
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_25, 255, 251, 0, 44 @ fade 7
	voice_directsound 60, 0, DirectSoundWaveData_gbwave01,      255, 0, 255, 44
