	.align 2
voicegroup193::
	voice_directsound 60, 0, DirectSoundWaveData_smwflute, 255, 254, 0, 64
	voice_directsound 60, 0, DirectSoundWaveData_smwstring1, 255, 254, 0, 64
	voice_directsound 60, 0, DirectSoundWaveData_smwchime, 255, 240, 0, 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_SMWbrass, KeySplitTable_DPhammondorg
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_smwclar, 255, 254, 0, 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_smwbass, 255, 255, 0, 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_smwrhode, 255, 254, 0, 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_smwstring2, 255, 254, 0, 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup193
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_smwkick, 255, 0, 255, 64
	voice_directsound 60, 0, DirectSoundWaveData_smwhat, 255, 0, 255, 64
	voice_directsound 60, 0, DirectSoundWaveData_smwhatp, 255, 0, 255, 64

voicegroup_SMWbrass::
	voice_directsound 60, 0, DirectSoundWaveData_smwbrass1, 255, 254, 0, 64
	voice_directsound 60, 0, DirectSoundWaveData_smwbrass2, 255, 254, 0, 64
