	.align 2
voicegroup214::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, A(3), D(127), S(127), R(126)
	voice_directsound 60, 64, DirectSoundWaveData_dp_dance_drums_kick, A(127), D(127), S(127), R(127)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_standard2_kick, A(127), D(127), S(127), R(120)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_orchestra_snare, A(127), D(127), S(127), R(127)
	voice_directsound 60, 70, DirectSoundWaveData_dp_sd90_standard2_clap, A(127), D(127), S(120), R(125)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(127)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_zg_wet_tight_thunder, A(127), D(127), S(120), R(125)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_sne1_roop, A(127), D(0), S(110), R(125)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 48, 30, DirectSoundWaveData_dp_sd90_standard2_tom, A(127), D(127), S(127), R(125)
	voice_directsound 60, 82, DirectSoundWaveData_dp_closehight, A(127), D(127), S(120), R(125)
	voice_directsound 53, 40, DirectSoundWaveData_dp_sd90_standard2_tom, A(127), D(127), S(127), R(125)
	voice_directsound 60, 82, DirectSoundWaveData_dp_zg_panned_hats_ped3, A(127), D(127), S(120), R(125)
	voice_directsound 60, 50, DirectSoundWaveData_dp_sd90_standard2_tom, A(127), D(127), S(127), R(125)
	voice_directsound 60, 82, DirectSoundWaveData_dp_zg_panned_hats_open_closed_1, A(125), D(110), S(0), R(125)
	voice_directsound 66, 90, DirectSoundWaveData_dp_sd90_standard2_tom, A(127), D(127), S(127), R(125)
	voice_directsound 72, 100, DirectSoundWaveData_dp_sd90_standard2_tom, A(127), D(127), S(127), R(125)
	voice_directsound 57, 64, DirectSoundWaveData_dp_sd90_standard2_crash, A(127), D(90), S(0), R(114)
	voice_directsound 74, 110, DirectSoundWaveData_dp_sd90_standard2_tom, A(127), D(127), S(127), R(126)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 59, 20, DirectSoundWaveData_dp_zg_dpt_ambient_16_crash_3, A(127), D(70), S(0), R(110)
	voice_directsound 60, 30, DirectSoundWaveData_dp_dance_drums_ride_bell, A(127), D(70), S(0), R(106)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 36, DirectSoundWaveData_dp_sd90_standard2_crash, A(127), D(70), S(0), R(114)
	voice_directsound 61, 102, DirectSoundWaveData_dp_sd90_standard2_crash, A(127), D(70), S(0), R(114)
