	.align 2
voicegroup219::
	voice_directsound 36, 0, DirectSoundWaveData_hg_plugsound_pro_elastik_36, A(127), D(125), S(120), R(120)
	voice_keysplit voicegroup219_strings, KeySplitTable_BWstrings_012
	voice_directsound 43, 0, DirectSoundWaveData_hg_plugsound_pro_cello_sus_43, A(120), D(100), S(127), R(116)
	voice_directsound 55, 0, DirectSoundWaveData_hg_plugsound_pro_timpani_55, A(127), D(50), S(1), R(116)
	voice_keysplit voicegroup219_trumpet, KeySplitTable_BWtrumpet_01
	voice_keysplit voicegroup219_trombone, KeySplitTable_DPtimpani1
	voice_keysplit voicegroup219_horn, KeySplitTable_BWnylonstrguitar
	voice_directsound 60, 0, DirectSoundWaveData_bw_zg_of_tutti_hit_minor_60, A(127), D(127), S(127), R(116)
	voice_keysplit voicegroup219_choir, KeySplitTable_48_58
	voice_keysplit_all voicegroup219_drumset1 - 0xc * 31
	voice_keysplit_all voicegroup219_drumset2 - 0xc * 36
	voice_directsound 60, 0, DirectSoundWaveData_bw_unknown_suspended_cymbal_40, A(127), D(127), S(127), R(100)
	voice_directsound 60, 0, DirectSoundWaveData_bw_zg_total_drum_bass_160_leonora, A(127), D(127), S(127), R(124)

voicegroup219_strings::
	voice_directsound 60, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_60, A(127), D(100), S(110), R(116)
	voice_directsound 69, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_69, A(127), D(100), S(110), R(116)
	voice_directsound 77, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_77, A(127), D(100), S(110), R(116)

voicegroup219_trumpet::
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_trumpet_ensemble_60, A(127), D(90), S(115), R(116)
	voice_directsound 69, 0, DirectSoundWaveData_hg_kfl_trumpet_ensemble_69, A(127), D(90), S(115), R(116)

voicegroup219_trombone::
	voice_directsound 43, 0, DirectSoundWaveData_hg_kfl_trombone_ensemble_43, A(127), D(100), S(115), R(116)
	voice_directsound 52, 0, DirectSoundWaveData_hg_kfl_trombone_ensemble_52, A(127), D(100), S(115), R(116)

voicegroup219_horn::
	voice_directsound 48, 0, DirectSoundWaveData_bw_kfl_french_horn_ensemble_48, A(127), D(110), S(120), R(116)
	voice_directsound 53, 0, DirectSoundWaveData_hg_kfl_french_horn_ensemble_53, A(127), D(110), S(120), R(116)
	voice_directsound 62, 0, DirectSoundWaveData_hg_kfl_french_horn_ensemble_62, A(127), D(110), S(120), R(116)

voicegroup219_choir::
	voice_directsound 43, 0, DirectSoundWaveData_bw_ewsc_full_chorus_ah_43, A(127), D(100), S(110), R(118)
	voice_directsound 52, 0, DirectSoundWaveData_bw_ewsc_full_chorus_ah_52, A(127), D(100), S(110), R(118)
	voice_directsound 60, 0, DirectSoundWaveData_bw_ewsc_full_chorus_ah_60, A(127), D(100), S(110), R(118)

voicegroup219_drumset1::
	voice_directsound 60, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 61, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 62, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 63, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 64, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 65, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 66, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 67, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 68, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 69, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 70, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 71, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 72, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 73, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 74, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 75, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 76, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, A(127), D(127), S(120), R(116)
	voice_directsound 60, 40, DirectSoundWaveData_hg_kfl_cymbals_a_due, A(127), D(70), S(0), R(114)

voicegroup219_drumset2::
	voice_directsound 60, 64, DirectSoundWaveData_bw_unknown_synth_kick_wcs, A(127), D(127), S(120), R(116)
	voice_directsound 61, 64, DirectSoundWaveData_bw_unknown_synth_kick_wcs, A(127), D(127), S(120), R(116)
	voice_directsound 62, 64, DirectSoundWaveData_bw_unknown_synth_kick_wcs, A(127), D(127), S(120), R(116)
	voice_directsound 63, 64, DirectSoundWaveData_bw_unknown_synth_kick_wcs, A(127), D(127), S(120), R(116)
	voice_directsound 60, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare_e2, A(127), D(114), S(90), R(116)
	voice_directsound 61, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare_e2, A(127), D(114), S(90), R(116)
	voice_directsound 60, 30, DirectSoundWaveData_bw_plugsound_pro_analog_hihat_closed, A(127), D(105), S(0), R(116)
	voice_directsound 61, 30, DirectSoundWaveData_bw_plugsound_pro_analog_hihat_closed, A(127), D(105), S(0), R(116)
	voice_directsound 62, 30, DirectSoundWaveData_bw_plugsound_pro_analog_hihat_closed, A(127), D(105), S(0), R(116)
	voice_directsound 63, 30, DirectSoundWaveData_bw_plugsound_pro_analog_hihat_closed, A(127), D(105), S(0), R(116)
	voice_directsound 60, 30, DirectSoundWaveData_bw_plugsound_pro_analog_hihat_open, A(127), D(102), S(0), R(116)
