	.align 2
voicegroup198::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, A(3), D(127), S(127), R(126)
	voice_directsound 60, 64, DirectSoundWaveData_dp_zg_wet_tight_thunder, A(127), D(127), S(120), R(125)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_dance_drums_kick, A(127), D(127), S(127), R(127)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_standard2_kick, A(127), D(127), S(127), R(120)
	voice_directsound 61, 58, DirectSoundWaveData_dp_rim1_roop, A(127), D(116), S(0), R(126)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_orchestra_snare, A(127), D(127), S(127), R(127)
	voice_directsound 60, 70, DirectSoundWaveData_dp_sd90_standard2_clap, A(127), D(127), S(120), R(125)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(127)
	voice_directsound 48, 30, DirectSoundWaveData_dp_sd90_room2_tom, A(127), D(127), S(127), R(125)
	voice_directsound 60, 80, DirectSoundWaveData_dp_sd90_standard2_chh, A(127), D(127), S(120), R(125)
	voice_directsound 53, 40, DirectSoundWaveData_dp_sd90_room2_tom, A(127), D(127), S(127), R(125)
	voice_directsound 60, 80, DirectSoundWaveData_dp_zg_panned_hats_ped3, A(127), D(127), S(122), R(126)
	voice_directsound 60, 50, DirectSoundWaveData_dp_sd90_room2_tom, A(127), D(127), S(127), R(125)
	voice_directsound 60, 80, DirectSoundWaveData_dp_sd90_standard2_ohh, A(127), D(102), S(0), R(127)
	voice_directsound 66, 100, DirectSoundWaveData_dp_sd90_room2_tom, A(127), D(127), S(127), R(125)
	voice_directsound 72, 107, DirectSoundWaveData_dp_sd90_room2_tom, A(127), D(127), S(127), R(125)
	voice_directsound 57, 64, DirectSoundWaveData_dp_sd90_standard2_crash, A(127), D(90), S(0), R(114)
	voice_directsound 74, 117, DirectSoundWaveData_dp_sd90_room2_tom, A(127), D(127), S(127), R(126)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 59, 20, DirectSoundWaveData_dp_zg_dpt_ambient_16_crash_3, A(127), D(70), S(0), R(110)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 84, DirectSoundWaveData_trinity_cymbal_crash, A(127), D(70), S(0), R(110)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 36, DirectSoundWaveData_dp_sd90_standard2_crash, A(127), D(70), S(0), R(114)
	voice_directsound 61, 102, DirectSoundWaveData_dp_sd90_standard2_crash, A(127), D(70), S(0), R(114)
