	.align 2
voicegroup252::
	voice_directsound 43, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_43, 255, 251, 14, 197	@ 127/ 60/ 30/118/ 64
	voice_directsound 55, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_55, 255, 251, 14, 197	@ 127/ 60/ 30/118/ 64
	voice_directsound 64, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_64, 255, 251, 14, 197	@ 127/ 60/ 30/118/ 64
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_72, 255, 251, 14, 197	@ 127/ 60/ 30/118/ 64
