	.align 2
voicegroup223::
	voice_directsound 72, 0, DirectSoundWaveData_bw_plugsound_pro_glockenspiel_72, A(127), D(75), S(1), R(116)
	voice_keysplit voicegroup223_slapbass, KeySplitTable_47
	voice_none
	voice_directsound 60, 0, DirectSoundWaveData_b2_doublsaw_c4, A(127), D(120), S(127), R(120)
	voice_directsound 46, 0, DirectSoundWaveData_bw_sd90_orch_hit2, A(127), D(80), S(1), R(116)
	voice_keysplit voicegroup223_choir, KeySplitTable_67_72
	voice_keysplit_all voicegroup223_drumset - 0xc * 25
	voice_directsound 40, 0, DirectSoundWaveData_b2_chugpowerchord_e4, A(127), D(30), S(1), R(120)
	voice_directsound 40, 0, DirectSoundWaveData_b2_bluescrunch_e2, A(127), D(30), S(1), R(120)

voicegroup223_slapbass::
	voice_directsound 36, 0, DirectSoundWaveData_bw_plugsound_pro_fend_slap1_pull_36, A(127), D(125), S(120), R(120)
	voice_directsound 48, 0, DirectSoundWaveData_bw_plugsound_pro_fend_slap1_pull_48, A(127), D(125), S(120), R(120)

voicegroup223_choir::
	voice_directsound 62, 0, DirectSoundWaveData_b2_children_choir_d4, A(127), D(100), S(110), R(115)
	voice_directsound 69, 0, DirectSoundWaveData_b2_children_choir_a4, A(127), D(100), S(110), R(118)
	voice_directsound 77, 0, DirectSoundWaveData_b2_children_choir_f5, A(127), D(100), S(110), R(118)

voicegroup223_drumset::
	voice_directsound 60, 58, DirectSoundWaveData_b2_addictive_drums_snare2, A(127), D(127), S(120), R(116)
	voice_directsound 31, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 32, 117, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 60, 64, DirectSoundWaveData_b2_addictive_drums_kick, A(127), D(127), S(127), R(120)
	voice_directsound 34, 10, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 35, 10, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 60, 64, DirectSoundWaveData_b2_halion_t9_analog_kick, A(127), D(127), S(127), R(124)
	voice_directsound 61, 64, DirectSoundWaveData_b2_halion_t9_analog_kick, A(127), D(127), S(127), R(124)
	voice_directsound 57, 64, DirectSoundWaveData_b2_addictive_drums_snare3, A(127), D(127), S(127), R(127)
	voice_directsound 58, 64, DirectSoundWaveData_b2_addictive_drums_snare3, A(127), D(127), S(127), R(127)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(116)
	voice_directsound 61, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(116)
	voice_directsound 62, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(116)
	voice_directsound 63, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(116)
	voice_directsound 64, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(116)
	voice_directsound 65, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(116)
	voice_directsound 66, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(116)
	voice_directsound 67, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(116)
	voice_directsound 60, 38, DirectSoundWaveData_b2_addictive_drums_floortom, A(127), D(127), S(127), R(122)
	voice_directsound 59, 40, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 60, 40, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 61, 40, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 60, 46, DirectSoundWaveData_bw_ps15_hihat21, A(127), D(127), S(127), R(127)
	voice_directsound 60, 46, DirectSoundWaveData_b2_dance_open_hat_32_loop, A(127), D(90), S(0), R(127)
	voice_directsound 61, 86, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 62, 86, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 63, 86, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 64, 86, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 63, 100, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 64, 100, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 65, 100, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 66, 100, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 67, 120, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 60, 50, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 61, 50, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 62, 50, DirectSoundWaveData_b2_addictive_drums_racktom, A(127), D(127), S(127), R(116)
	voice_directsound 60, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 61, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 62, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 60, 20, DirectSoundWaveData_hg_battery3_chinese, A(127), D(80), S(0), R(110)
	voice_directsound 60, 20, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 60, 100, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 60, 100, DirectSoundWaveData_hg_battery3_chinese, A(127), D(80), S(0), R(110)
	voice_directsound 63, 84, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 64, 44, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
	voice_none
