	.align 2
voicegroup243::
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_oct_36, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_oct_48, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_oct_60, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_oct_72, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64
