	.align 2
voicegroup236::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_orchestra_hit_60, 255, 249, 25, 208	@ 127/ 80/ 40/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_orchestra_hit_72, 255, 249, 25, 208	@ 127/ 80/ 40/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_orchestra_hit_79, 255, 249, 25, 208	@ 127/ 80/ 40/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_orchestra_hit_84, 255, 249, 25, 208	@ 127/ 80/ 40/116/ 64
