	.align 2
voicegroup234::
	voice_none
	voice_keysplit voicegroup234_xylo, KeySplitTable_BWpizz_34
	voice_directsound 72, 0, DirectSoundWaveData_bw_kfl_mark_i_classic_72, A(127), D(70), S(1), R(115)
	voice_keysplit voicegroup234_strings, KeySplitTable_BWstrings
	voice_directsound 60, 0, DirectSoundWaveData_b2_ewso_suspense_string_fx, A(127), D(100), S(110), R(122)
	voice_keysplit voicegroup234_trumpet, KeySplitTable_BWtrumpet_01
	voice_keysplit voicegroup234_oboe, KeySplitTable_GSoboe
	voice_directsound 81, 0, DirectSoundWaveData_bw_ps55_flute_81_22, A(127), D(90), S(100), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_b2_ew_ra_chinese_gong_vs, A(127), D(50), S(1), R(116)
	voice_directsound 55, 0, DirectSoundWaveData_hg_plugsound_pro_timpani_55, A(127), D(50), S(1), R(116)
	voice_keysplit_all voicegroup234_drumset - 0xc * 26
	voice_keysplit voicegroup234_trombone, KeySplitTable_DPtimpani1
	voice_directsound 43, 0, DirectSoundWaveData_hg_plugsound_pro_cello_sus_43, A(120), D(100), S(127), R(116)
	voice_directsound 40, 0, DirectSoundWaveData_bw_independence_pro_khso_all_strings_spc_up, A(127), D(127), S(127), R(120)
	voice_directsound 48, 0, DirectSoundWaveData_bw_ewso_6fh_rips_s, A(127), D(80), S(1), R(116)

voicegroup234_xylo::
	voice_directsound 69, 0, DirectSoundWaveData_hg_kfl_xylophone_69, A(127), D(80), S(40), R(118)
	voice_directsound 77, 0, DirectSoundWaveData_hg_kfl_xylophone_77, A(127), D(80), S(60), R(118)

voicegroup234_strings::
	voice_directsound 60, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_60, A(127), D(100), S(110), R(116)
	voice_directsound 69, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_69, A(127), D(100), S(110), R(116)
	voice_directsound 77, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_77, A(127), D(100), S(110), R(116)
	voice_directsound 84, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_84, A(127), D(100), S(110), R(116)

voicegroup234_trumpet::
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_trumpet_ensemble_60, A(127), D(90), S(115), R(116)
	voice_directsound 69, 0, DirectSoundWaveData_hg_kfl_trumpet_ensemble_69, A(127), D(90), S(115), R(116)

voicegroup234_oboe::
	voice_directsound 64, 0, DirectSoundWaveData_hg_kfl_oboe_64, A(127), D(100), S(110), R(114)
	voice_directsound 72, 0, DirectSoundWaveData_hg_kfl_oboe_72, A(127), D(100), S(110), R(114)
	voice_directsound 81, 0, DirectSoundWaveData_hg_kfl_oboe_81, A(127), D(100), S(110), R(114)

voicegroup234_drumset::
	voice_directsound 60, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 61, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 62, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 63, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 64, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 65, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 66, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 67, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 68, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 69, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 70, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 71, 64, DirectSoundWaveData_bw_unknown_snare_roll, A(127), D(127), S(120), R(124)
	voice_directsound 60, 64, DirectSoundWaveData_b2_ewso_3_snares, A(127), D(127), S(127), R(122)
	voice_directsound 61, 64, DirectSoundWaveData_b2_ewso_3_snares, A(127), D(127), S(127), R(122)
	voice_directsound 62, 64, DirectSoundWaveData_b2_ewso_3_snares, A(127), D(127), S(127), R(122)
	voice_directsound 63, 64, DirectSoundWaveData_b2_ewso_3_snares, A(127), D(127), S(127), R(122)
	voice_directsound 64, 64, DirectSoundWaveData_b2_ewso_3_snares, A(127), D(127), S(127), R(122)
	voice_directsound 65, 64, DirectSoundWaveData_b2_ewso_3_snares, A(127), D(127), S(127), R(122)
	voice_directsound 66, 64, DirectSoundWaveData_b2_ewso_3_snares, A(127), D(127), S(127), R(122)
	voice_directsound 67, 64, DirectSoundWaveData_b2_ewso_3_snares, A(127), D(127), S(127), R(122)
	voice_directsound 68, 64, DirectSoundWaveData_b2_ewso_3_snares, A(127), D(127), S(127), R(122)
	voice_directsound 69, 64, DirectSoundWaveData_b2_ewso_3_snares, A(127), D(127), S(127), R(122)
	voice_directsound 60, 64, DirectSoundWaveData_hg_kfl_cymbals_a_due, A(127), D(70), S(0), R(114)
	voice_directsound 61, 64, DirectSoundWaveData_hg_kfl_cymbals_a_due, A(127), D(70), S(0), R(114)

voicegroup234_trombone::
	voice_directsound 43, 0, DirectSoundWaveData_hg_kfl_trombone_ensemble_43, A(127), D(100), S(115), R(116)
	voice_directsound 52, 0, DirectSoundWaveData_hg_kfl_trombone_ensemble_52, A(127), D(100), S(115), R(116)
