	.align 2
voicegroup246::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_bassoon_sus_40, 255, 242, 127, 216	@ 127/100/ 90/114/ 64
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_bassoon_sus_48, 255, 242, 127, 216	@ 127/100/ 90/114/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_bassoon_sus_57, 255, 242, 127, 216	@ 127/100/ 90/114/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
