	.align 2
voicegroup352::
@	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_flute_sus_60, 255, 246, 159, 208	@ 127/ 90/100/116/ 64	@todo: get adsr
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_flute_sus_69, 255, 246, 159, 208	@ 127/ 90/100/116/ 64	@todo: get adsr
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_flute_sus_77, 255, 246, 159, 208	@ 127/ 90/100/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_flute_sus_84, 255, 246, 159, 208	@ 127/ 90/100/116/ 64
