	.align 2
voicegroup192::
	voice_keysplit voicegroup_GSgrandpiano, KeySplitTable_GSgrandpiano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_GSoctpiano, KeySplitTable_GSoctpiano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_GSrhodes2, KeySplitTable_GSrhodes2
	voice_keysplit voicegroup_GSvibes, KeySplitTable_GSvibes
	voice_keysplit voicegroup_GSmarimba, KeySplitTable_GSmarimba
	voice_keysplit voicegroup_GSxylo, KeySplitTable_GSxylo
	voice_keysplit voicegroup_GStubbell, KeySplitTable_GStubbell
	voice_keysplit voicegroup_GSglocken, KeySplitTable_GSglocken
	voice_keysplit voicegroup_GSmusbox, KeySplitTable_GSmusbox
	voice_keysplit voicegroup_GSdrawbarorg, KeySplitTable_GSdrawbarorg
	voice_keysplit voicegroup_GSjazzorg, KeySplitTable_GSjazzorg
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_GSsteelstrgt, KeySplitTable_GSsteelstrgt
	voice_keysplit voicegroup_GSdistgt1, KeySplitTable_GSdistgt1
	voice_keysplit voicegroup_GSdistgt2, KeySplitTable_GSdistgt2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_GSacbass, KeySplitTable_GSacbass
	voice_keysplit voicegroup_GSfretlessbs, KeySplitTable_GSfretlessbs
	voice_directsound 36, 0, DirectSoundWaveData_dp_sd90_slap_bass1, A(127), D(127), S(127), R(118)
	voice_keysplit voicegroup_GSsynbass, KeySplitTable_GSsynbass
	voice_keysplit voicegroup_GSstrings, KeySplitTable_GSstrings
	voice_keysplit voicegroup_GSviolin, KeySplitTable_GSviolin
	voice_keysplit voicegroup_GScello, KeySplitTable_GScello
	voice_keysplit voicegroup_GSpizz, KeySplitTable_GSpizz
	voice_keysplit voicegroup_GSharp, KeySplitTable_GSharp
	voice_keysplit voicegroup_GStimpani, KeySplitTable_GStimpani
	voice_keysplit voicegroup_GStrumpet, KeySplitTable_GStrumpet
	voice_keysplit voicegroup_GStrombone, KeySplitTable_GStrombone
	voice_keysplit voicegroup_GSbrihorn, KeySplitTable_GSbrihorn
	voice_keysplit voicegroup_GSfhorns, KeySplitTable_GSfhorns
	voice_keysplit voicegroup_GSoboe, KeySplitTable_GSoboe
	voice_keysplit voicegroup_GSclarinet, KeySplitTable_GSclarinet
	voice_keysplit voicegroup_GSflute, KeySplitTable_GSflute
	voice_keysplit voicegroup_GSbassoon, KeySplitTable_GSbassoon
	voice_keysplit voicegroup_GSorchhit, KeySplitTable_GSorchhit
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup_GSdrumset - 0xc * 29
	voice_keysplit_all voicegroup_GStaikoset - 0xc * 48
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup_GSkoto, KeySplitTable_GSkoto
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 48, 0, DirectSoundWaveData_sc88pro_square_wave, A(127), D(70), S(0), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, A(125), D(127), S(127), R(127)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundSynthData_squ50, A(124), D(100), S(80), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 84, 0, DirectSoundWaveData_dp_sd90_whistle2, A(127), D(90), S(70), R(118)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_of_tutti_hit_major, A(127), D(120), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_of_tutti_hit_minor, A(127), D(120), S(127), R(120)
	voice_keysplit_all voicegroup_GSdancekit - 0xc * 36
	voice_keysplit voicegroup_DPtimpani1, KeySplitTable_DPtimpani1
	voice_directsound 36, 0, DirectSoundWaveData_dp_zg_bass_filter_slaps, A(127), D(125), S(127), R(118)
	voice_directsound 36, 0, DirectSoundWaveData_dp_sd90_mg303_bass, A(127), D(127), S(127), R(112)
	voice_directsound 60, 0, DirectSoundWaveData_dp_qy70_doublsaw, A(127), D(120), S(127), R(120)
	voice_keysplit voicegroup_GSshamisen, KeySplitTable_GSshamisen
	voice_directsound 60, 0, DirectSoundWaveData_hg_kaeru_cafe_hyoshigi, A(127), D(127), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_hg_kaeru_cafe_kodaiko2, A(127), D(127), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_hg_kaeru_cafe_kotsu, A(127), D(127), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_hg_discovery_japan_suzu, A(127), D(127), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_hg_machfive2_taiko, A(127), D(127), S(127), R(126)
	voice_directsound 48, 0, DirectSoundWaveData_dp_ps13_classic_choir_ahh_48, A(127), D(120), S(127), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_hg_ps13_classic_choir_ahh_60, A(127), D(120), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_reverse_cymbal, A(127), D(120), S(127), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_qy70_dance_snare, A(127), D(127), S(127), R(120)

voicegroup_GSgrandpiano::
	voice_directsound 36, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_36, A(127), D(75), S(1), R(110)
	voice_directsound 48, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_48, A(127), D(75), S(1), R(110)
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_60, A(127), D(75), S(1), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_72, A(127), D(80), S(1), R(116)
	voice_directsound 84, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_84, A(127), D(85), S(1), R(116)

voicegroup_GSoctpiano::
	voice_directsound 36, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_oct_36, A(127), D(75), S(1), R(116)
	voice_directsound 48, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_oct_48, A(127), D(75), S(1), R(116)
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_oct_60, A(127), D(75), S(1), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_oct_72, A(127), D(75), S(1), R(116)

voicegroup_GSrhodes2::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_a_suitcase_medium_60, A(127), D(70), S(1), R(125)
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_a_suitcase_medium_72, A(127), D(70), S(1), R(125)

voicegroup_GSvibes::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_vibraphone1_60, A(127), D(90), S(1), R(118)
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_vibraphone1_72, A(127), D(90), S(1), R(116)

voicegroup_GSmarimba::
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_marimba_60, A(127), D(90), S(1), R(114)
	voice_directsound 72, 0, DirectSoundWaveData_hg_kfl_marimba_72, A(127), D(90), S(1), R(114)
	voice_directsound 84, 0, DirectSoundWaveData_hg_kfl_marimba_84, A(127), D(90), S(1), R(114)

voicegroup_GSxylo::
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_xylophone_60, A(127), D(80), S(40), R(118)
	voice_directsound 69, 0, DirectSoundWaveData_hg_kfl_xylophone_69, A(127), D(80), S(40), R(118)
	voice_directsound 77, 0, DirectSoundWaveData_hg_kfl_xylophone_77, A(127), D(80), S(60), R(118)

voicegroup_GStubbell::
	voice_directsound 67, 0, DirectSoundWaveData_hg_ewso_orch_chimes_67, A(127), D(80), S(40), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_hg_ewso_orch_chimes_72, A(127), D(80), S(40), R(116)

voicegroup_GSglocken::
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_glockenspiel_60, A(127), D(90), S(1), R(118)
	voice_directsound 72, 0, DirectSoundWaveData_hg_kfl_glockenspiel_72, A(127), D(90), S(1), R(116)

voicegroup_GSmusbox::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_music_box_60, A(127), D(90), S(1), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_music_box_72, A(127), D(90), S(1), R(116)
	voice_directsound 84, 0, DirectSoundWaveData_hg_plugsound_pro_music_box_84, A(127), D(90), S(1), R(116)

voicegroup_GSdrawbarorg::
	voice_directsound 48, 0, DirectSoundWaveData_hg_plugsound_pro_full_organ_slow_48, A(127), D(120), S(120), R(116)
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_full_organ_slow_60, A(127), D(127), S(127), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_full_organ_slow_72, A(127), D(127), S(127), R(116)

voicegroup_GSjazzorg::
	voice_directsound 48, 0, DirectSoundWaveData_hg_plugsound_pro_jazz_organ_48, A(127), D(127), S(127), R(116)
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_jazz_organ_60, A(127), D(127), S(127), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_jazz_organ_72, A(127), D(127), S(127), R(116)

voicegroup_GSsteelstrgt::
	voice_directsound 43, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_43, A(127), D(60), S(30), R(118)
	voice_directsound 55, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_55, A(127), D(60), S(30), R(118)
	voice_directsound 64, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_64, A(127), D(60), S(30), R(118)
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_72, A(127), D(60), S(30), R(118)

voicegroup_GSdistgt1::
	voice_directsound 40, 0, DirectSoundWaveData_dp_ps16_dist_gtr_40, A(127), D(30), S(1), R(125)
	voice_directsound 48, 0, DirectSoundWaveData_dp_ps16_dist_gtr_48, A(127), D(30), S(1), R(125)
	voice_directsound 64, 0, DirectSoundWaveData_dp_ps16_dist_gtr_64, A(127), D(30), S(1), R(125)
	voice_directsound 76, 0, DirectSoundWaveData_dp_ps16_dist_gtr_76, A(127), D(30), S(1), R(125)

voicegroup_GSdistgt2::
	voice_directsound 40, 0, DirectSoundWaveData_dp_ps16_dist_gtr_40, A(127), D(30), S(1), R(120)
	voice_directsound 48, 0, DirectSoundWaveData_dp_ps16_dist_gtr_48, A(127), D(30), S(1), R(120)
	voice_directsound 64, 0, DirectSoundWaveData_dp_ps16_dist_gtr_64, A(127), D(30), S(1), R(120)
	voice_directsound 76, 0, DirectSoundWaveData_dp_ps16_dist_gtr_76, A(127), D(30), S(1), R(120)

voicegroup_GSacbass::
	voice_directsound 36, 0, DirectSoundWaveData_hg_plugsound_pro_jazz_double_bass_hard_36, A(127), D(60), S(1), R(118)
	voice_directsound 48, 0, DirectSoundWaveData_hg_plugsound_pro_jazz_double_bass_hard_48, A(127), D(60), S(1), R(118)

voicegroup_GSfretlessbs::
	voice_directsound 45, 0, DirectSoundWaveData_hg_plugsound_pro_ampeg_ac_bass_full_45, A(127), D(110), S(100), R(118)
	voice_directsound 57, 0, DirectSoundWaveData_hg_plugsound_pro_ampeg_ac_bass_full_57, A(127), D(110), S(100), R(118)

voicegroup_GSsynbass::
	voice_directsound 36, 0, DirectSoundWaveData_hg_plugsound_pro_elastik_36, A(127), D(125), S(120), R(120)
	voice_directsound 48, 0, DirectSoundWaveData_hg_plugsound_pro_elastik_48, A(127), D(125), S(120), R(120)

voicegroup_GSstrings::
	voice_directsound 60, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_60, A(127), D(100), S(110), R(118)
	voice_directsound 69, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_69, A(127), D(100), S(110), R(118)
	voice_directsound 77, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_77, A(122), D(100), S(110), R(118)
	voice_directsound 84, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_84, A(122), D(100), S(110), R(118)

voicegroup_GSviolin::
	voice_directsound 64, 0, DirectSoundWaveData_hg_plugsound_pro_violin_sus_64, A(120), D(100), S(127), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_violin_sus_72, A(120), D(90), S(127), R(116)
	voice_directsound 81, 0, DirectSoundWaveData_hg_plugsound_pro_violin_sus_81, A(120), D(90), S(127), R(116)

voicegroup_GScello::
	voice_directsound 43, 0, DirectSoundWaveData_hg_plugsound_pro_cello_sus_43, A(120), D(100), S(127), R(116)
	voice_directsound 52, 0, DirectSoundWaveData_hg_plugsound_pro_cello_sus_52, A(120), D(90), S(127), R(116)
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_cello_sus_60, A(120), D(90), S(127), R(116)

voicegroup_GSpizz::
	voice_directsound 43, 0, DirectSoundWaveData_hg_kfl_cello_ensemble_pizz_43, A(127), D(100), S(40), R(116)
	voice_directsound 52, 0, DirectSoundWaveData_hg_kfl_cello_ensemble_pizz_52, A(127), D(100), S(40), R(116)
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_violin_ensemble_pizz_60, A(127), D(100), S(40), R(116)
	voice_directsound 69, 0, DirectSoundWaveData_hg_kfl_violin_ensemble_pizz_69, A(127), D(100), S(40), R(116)
	voice_directsound 77, 0, DirectSoundWaveData_hg_kfl_violin_ensemble_pizz_77, A(127), D(105), S(40), R(116)

voicegroup_GSharp::
	voice_directsound 48, 0, DirectSoundWaveData_hg_kfl_harp_48, A(127), D(80), S(1), R(116)
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_harp_60, A(127), D(90), S(1), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_hg_kfl_harp_72, A(127), D(100), S(1), R(116)

voicegroup_GStimpani::
	voice_directsound 55, 0, DirectSoundWaveData_hg_plugsound_pro_timpani_55, A(127), D(60), S(40), R(118)
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_timpani_60, A(127), D(60), S(40), R(118)
	voice_directsound 67, 0, DirectSoundWaveData_hg_plugsound_pro_timpani_67, A(127), D(60), S(40), R(118)

voicegroup_GStrumpet::
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_trumpet_ensemble_60, A(127), D(100), S(110), R(116)
	voice_directsound 69, 0, DirectSoundWaveData_hg_kfl_trumpet_ensemble_69, A(127), D(100), S(110), R(116)
	voice_directsound 79, 0, DirectSoundWaveData_hg_kfl_trumpet_ensemble_79, A(127), D(110), S(110), R(116)

voicegroup_GStrombone::
	voice_directsound 43, 0, DirectSoundWaveData_hg_kfl_trombone_ensemble_43, A(127), D(100), S(100), R(116)
	voice_directsound 52, 0, DirectSoundWaveData_hg_kfl_trombone_ensemble_52, A(127), D(100), S(100), R(116)
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_trombone_ensemble_60, A(127), D(100), S(100), R(116)

voicegroup_GSbrihorn::
	voice_directsound 53, 0, DirectSoundWaveData_hg_kfl_french_horn_53, A(127), D(127), S(126), R(118)
	voice_directsound 62, 0, DirectSoundWaveData_hg_kfl_french_horn_62, A(127), D(127), S(126), R(118)
	voice_directsound 71, 0, DirectSoundWaveData_hg_kfl_french_horn_71, A(127), D(127), S(126), R(118)

voicegroup_GSfhorns::
	voice_directsound 53, 0, DirectSoundWaveData_hg_kfl_french_horn_ensemble_53, A(127), D(117), S(118), R(116)
	voice_directsound 62, 0, DirectSoundWaveData_hg_kfl_french_horn_ensemble_62, A(127), D(117), S(118), R(116)
	voice_directsound 71, 0, DirectSoundWaveData_hg_kfl_french_horn_ensemble_71, A(127), D(117), S(127), R(116)

voicegroup_GSoboe::
	voice_directsound 64, 0, DirectSoundWaveData_hg_kfl_oboe_64, A(127), D(100), S(110), R(114)
	voice_directsound 72, 0, DirectSoundWaveData_hg_kfl_oboe_72, A(127), D(100), S(110), R(114)
	voice_directsound 81, 0, DirectSoundWaveData_hg_kfl_oboe_81, A(127), D(100), S(110), R(114)

voicegroup_GSclarinet::
	voice_directsound 55, 0, DirectSoundWaveData_hg_sampletank_clarinet_55, A(127), D(100), S(90), R(114)
	voice_directsound 64, 0, DirectSoundWaveData_hg_sampletank_clarinet_64, A(127), D(100), S(90), R(114)
	voice_directsound 72, 0, DirectSoundWaveData_hg_sampletank_clarinet_72, A(127), D(100), S(90), R(114)

voicegroup_GSflute::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_flute_sus_60, A(127), D(90), S(100), R(118)
	voice_directsound 69, 0, DirectSoundWaveData_hg_plugsound_pro_flute_sus_69, A(127), D(90), S(90), R(118)
	voice_directsound 77, 0, DirectSoundWaveData_hg_plugsound_pro_flute_sus_77, A(127), D(90), S(90), R(118)
	voice_directsound 84, 0, DirectSoundWaveData_hg_plugsound_pro_flute_sus_84, A(127), D(90), S(70), R(118)

voicegroup_GSbassoon::
	voice_directsound 40, 0, DirectSoundWaveData_hg_plugsound_pro_bassoon_sus_40, A(127), D(100), S(90), R(114)
	voice_directsound 48, 0, DirectSoundWaveData_hg_plugsound_pro_bassoon_sus_48, A(127), D(100), S(90), R(114)
	voice_directsound 57, 0, DirectSoundWaveData_hg_plugsound_pro_bassoon_sus_57, A(127), D(100), S(90), R(114)

voicegroup_GSorchhit::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_orchestra_hit_60, A(127), D(80), S(40), R(116)
	voice_directsound 72, 0, DirectSoundWaveData_hg_plugsound_pro_orchestra_hit_72, A(127), D(80), S(40), R(116)
	voice_directsound 79, 0, DirectSoundWaveData_hg_plugsound_pro_orchestra_hit_79, A(127), D(80), S(40), R(116)
	voice_directsound 84, 0, DirectSoundWaveData_hg_plugsound_pro_orchestra_hit_84, A(127), D(80), S(40), R(116)

voicegroup_GSdrumset::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_zg_wet_crossfade_snare2, A(127), D(0), S(110), R(120)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_reverse_cymbal, A(3), D(127), S(120), R(120)
	voice_directsound 60, 64, DirectSoundWaveData_dp_zg_wet_tight_thunder, A(127), D(127), S(120), R(120)
	voice_directsound 61, 64, DirectSoundWaveData_dp_zg_wet_tight_thunder, A(127), D(127), S(120), R(120)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_tr808_snare, A(127), D(116), S(0), R(120)
	voice_directsound 60, 64, DirectSoundWaveData_dp_dance_drums_kick, A(127), D(127), S(127), R(120)
	voice_directsound 60, 64, DirectSoundWaveData_dp_zg_radio_compressor_kick, A(127), D(127), S(120), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_orchestra_snare, A(127), D(127), S(127), R(120)
	voice_directsound 60, 70, DirectSoundWaveData_dp_sd90_standard2_clap, A(127), D(127), S(120), R(120)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(120)
	voice_directsound 60, 30, DirectSoundWaveData_hg_battery3_rock_floor_tom2, A(127), D(127), S(127), R(120)
	voice_directsound 60, 80, DirectSoundWaveData_hg_battery3_hihat_closed, A(127), D(100), S(0), R(120)
	voice_directsound 60, 40, DirectSoundWaveData_hg_battery3_rock_floor_tom1, A(127), D(127), S(127), R(120)
	voice_directsound 61, 40, DirectSoundWaveData_hg_battery3_rock_floor_tom1, A(127), D(127), S(127), R(120)
	voice_directsound 60, 50, DirectSoundWaveData_hg_battery3_rock_rack_tom2, A(127), D(127), S(127), R(120)
	voice_directsound 60, 80, DirectSoundWaveData_hg_battery3_hihat_open, A(127), D(102), S(0), R(120)
	voice_directsound 60, 100, DirectSoundWaveData_hg_battery3_rock_rack_tom1, A(127), D(127), S(127), R(120)
	voice_directsound 60, 64, DirectSoundWaveData_hg_kfl_cymbals_a_due, A(127), D(90), S(0), R(114)
	voice_directsound 57, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(100), S(0), R(114)
	voice_directsound 58, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(100), S(0), R(114)
	voice_directsound 59, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(100), S(0), R(114)
	voice_directsound 59, 20, DirectSoundWaveData_hg_battery3_chinese, A(127), D(70), S(0), R(110)
	voice_directsound 60, 30, DirectSoundWaveData_dp_dance_drums_ride_bell, A(127), D(70), S(0), R(115)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 84, DirectSoundWaveData_hg_battery3_splash, A(127), D(70), S(0), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 36, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(80), S(0), R(114)
	voice_directsound 61, 102, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(80), S(0), R(114)
	voice_directsound 60, 86, DirectSoundWaveData_dp_dance_drums_ride, A(127), D(70), S(0), R(114)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 20, DirectSoundWaveData_dp_sd90_standard2_muted_high_conga, A(127), D(127), S(127), R(120)
	voice_directsound 60, 24, DirectSoundWaveData_dp_sd90_standard2_high_conga, A(127), D(127), S(127), R(120)
	voice_directsound 57, 26, DirectSoundWaveData_dp_sd90_standard2_high_conga, A(127), D(127), S(127), R(120)
	voice_directsound 58, 26, DirectSoundWaveData_dp_sd90_standard2_high_conga, A(127), D(127), S(127), R(120)
	voice_directsound 59, 26, DirectSoundWaveData_dp_sd90_standard2_high_conga, A(127), D(127), S(127), R(120)
	voice_directsound 60, 26, DirectSoundWaveData_dp_sd90_standard2_cabasa, A(127), D(100), S(90), R(120)
	voice_directsound 60, 105, DirectSoundWaveData_dp_sd90_standard2_muted_high_conga, A(127), D(127), S(127), R(120)
	voice_directsound 60, 105, DirectSoundWaveData_dp_sd90_standard2_high_conga, A(127), D(127), S(127), R(120)
	voice_directsound 63, 105, DirectSoundWaveData_dp_sd90_standard2_high_conga, A(127), D(127), S(127), R(120)
	voice_directsound 64, 105, DirectSoundWaveData_dp_sd90_standard2_high_conga, A(127), D(127), S(127), R(120)
	voice_directsound 65, 105, DirectSoundWaveData_dp_sd90_standard2_high_conga, A(127), D(127), S(127), R(120)
	voice_directsound 66, 105, DirectSoundWaveData_dp_sd90_standard2_high_conga, A(127), D(127), S(127), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 44, DirectSoundWaveData_dp_sd90_standard2_open_triangle, A(127), D(120), S(0), R(125)
	voice_directsound 60, 44, DirectSoundWaveData_dp_sd90_standard2_open_triangle, A(127), D(80), S(0), R(118)

voicegroup_GStaikoset::
	voice_directsound 60, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 61, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 62, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 63, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 64, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 65, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 66, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 67, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 68, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 69, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 70, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 71, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko2, A(127), D(127), S(120), R(120)
	voice_directsound 60, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 61, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 62, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 63, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 64, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 65, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 66, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 67, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 68, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 69, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 70, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 71, 40, DirectSoundWaveData_hg_kaeru_cafe_taiko3, A(127), D(127), S(120), R(120)
	voice_directsound 60, 40, DirectSoundWaveData_hg_kaeru_cafe_okedo_ohdaiko_rim, A(127), D(127), S(120), R(120)

voicegroup_GSkoto::
	voice_directsound 52, 0, DirectSoundWaveData_hg_machfive2_koto3_52, A(127), D(90), S(1), R(118)
	voice_directsound 60, 0, DirectSoundWaveData_hg_machfive2_koto3_60, A(127), D(90), S(1), R(118)
	voice_directsound 69, 0, DirectSoundWaveData_hg_machfive2_koto3_69, A(127), D(90), S(1), R(118)

voicegroup_GSdancekit::
	voice_directsound 60, 64, DirectSoundWaveData_dp_qy70_dance_kick, A(127), D(127), S(127), R(120)
	voice_directsound 61, 64, DirectSoundWaveData_dp_qy70_dance_kick, A(127), D(127), S(127), R(120)
	voice_directsound 60, 64, DirectSoundWaveData_dp_qy70_dance_snare, A(127), D(127), S(127), R(120)

voicegroup_GSshamisen::
	voice_directsound 50, 0, DirectSoundWaveData_hg_machfive2_shamisen1_50, A(127), D(75), S(1), R(116)
	voice_directsound 58, 0, DirectSoundWaveData_hg_machfive2_shamisen1_58, A(127), D(80), S(1), R(116)
	voice_directsound 67, 0, DirectSoundWaveData_hg_machfive2_shamisen1_67, A(127), D(85), S(1), R(116)
