	.align 2
voicegroup191::
	voice_directsound 48, 0, DirectSoundWaveData_dp_sd90_reverse_cymbal, A(127), D(127), S(127), R(126)
	voice_keysplit_all voicegroup198				@ drum kit 1
	voice_keysplit voicegroup196, KeySplitTable10	@ ew grand piano
	voice_keysplit voicegroup256, KeySplitTable98	@ ew grand piano low
	voice_keysplit voicegroup210, KeySplitTable22	@ sd90 soft rhodes
	voice_keysplit voicegroup257, KeySplitTable13	@ sd90 fm e.piano
	voice_keysplit_all voicegroup214				@ drum kit 2
	voice_keysplit voicegroup258, KeySplitTable99	@ sd90 fm e.piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 96, 0, DirectSoundWaveData_dp_sd90_glocken2, A(127), D(90), S(0), R(116)
	voice_directsound 60, 0, DirectSoundSynthData_squ50, A(126), D(100), S(50), R(118)
	voice_keysplit voicegroup209, KeySplitTable21	@ sd90 vibraphone 2
	voice_keysplit voicegroup197, KeySplitTable11	@ sd90 marimba 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup211, KeySplitTable23	@ sd90 tubular bell 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup213				@ qy70 dance kit
	voice_keysplit voicegroup204, KeySplitTable17	@ sd90 perky spin
	voice_keysplit voicegroup193, KeySplitTable7	@ retro sampler organ b3 ham
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_organ2, A(127), D(122), S(122), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_dp_qy70_doublsaw, A(127), D(120), S(127), R(120)
	voice_keysplit voicegroup194, KeySplitTable8	@ sd90 french accordion
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_harmonica2, A(116), D(90), S(110), R(120)
	voice_none
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_tengan_wind, A(127), D(127), S(127), R(125)
	voice_keysplit voicegroup203, KeySplitTable16	@ prosamples 16 dist gtr
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundSynthData_squ50, A(126), D(100), S(40), R(127)
	voice_keysplit voicegroup212, KeySplitTable24	@ zero-g woody bass
	voice_directsound 28, 0, DirectSoundWaveData_dp_ps16_stingray_bass_hard, A(127), D(60), S(1), R(116)
	voice_directsound 28, 0, DirectSoundWaveData_dp_zg_pick_bass, A(127), D(60), S(1), R(116)
	voice_directsound 38, 0, DirectSoundWaveData_dp_zg_woody_bass_38, A(127), D(127), S(127), R(118)
	voice_directsound 31, 0, DirectSoundWaveData_dp_slapbass_g1_16, A(127), D(127), S(127), R(112)
	voice_directsound 36, 0, DirectSoundWaveData_dp_sd90_slap_bass1, A(127), D(127), S(127), R(114)
	voice_directsound 36, 0, DirectSoundWaveData_dp_zg_bass_filter_slaps, A(127), D(125), S(127), R(118)
	voice_directsound 36, 0, DirectSoundWaveData_dp_sd90_mg303_bass, A(127), D(127), S(127), R(112)
	voice_keysplit voicegroup201, KeySplitTable14	@ sd90 violin vib
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundSynthData_squ50, A(127), D(50), S(0), R(125)
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, A(99), D(99), S(99), R(110)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup360, KeySplitTable35	@ prosamples 41 violin pizzicato forte
	voice_keysplit voicegroup202, KeySplitTable15	@ classic orchestra 2 harp long
	voice_keysplit voicegroup208, KeySplitTable18	@ classic orchestra timpani
	voice_keysplit voicegroup195, KeySplitTable9	@ sd90 strings 2
	voice_directsound 61, 0, DirectSoundWaveData_dp_ps55_cello_section_61,  A(127), D(120), S(127), R(118)
	voice_directsound 59, 0, DirectSoundWaveData_dp_ps51_french_horns_59,  A(127), D(120), S(127), R(110)
	voice_keysplit voicegroup205, KeySplitTable18	@ sd90 timpani 2
	voice_directsound 60, 0, DirectSoundSynthData_squ50,  A(127), D(70), S(0), R(110)
	voice_directsound 48, 0, DirectSoundWaveData_sc88pro_square_wave, A(127), D(70), S(0), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, A(125), D(127), S(127), R(127)
	voice_directsound 48, 0, DirectSoundWaveData_dp_trinity_pop_u_wit_dis, A(127), D(120), S(127), R(112)
	voice_keysplit voicegroup192, KeySplitTable6	@ ew pop brass 3tp sus
	voice_keysplit voicegroup199, KeySplitTable12	@ sd90 solo bone
	voice_keysplit voicegroup206, KeySplitTable19	@ sd90 tuba 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup200, KeySplitTable13	@ sd90 french horns 2
	voice_keysplit voicegroup_merodisgt, KeySplitTable42	@ mero disgt
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundSynthData_squ12, A(124), D(100), S(80), R(110)
	voice_directsound 36, 0, DirectSoundWaveData_dp_sc88pro_p5_bass, A(127), D(125), S(127), R(114)
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, A(127), D(117), S(126), R(118)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundSynthData_squ50, A(124), D(100), S(80), R(110)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_sy77_clarinet_60, A(127), D(100), S(100), R(114)
	voice_directsound 60, 0, DirectSoundSynthData_squ50, A(124), D(100), S(80), R(120)
	voice_keysplit voicegroup207, KeySplitTable20	@ sd90 flute 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 48, 0, DirectSoundWaveData_dp_ps13_classic_choir_ahh_48, A(127), D(120), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_dp_ps13_classic_choir_ahh_60, A(127), D(120), S(127), R(120)
	voice_directsound 84, 0, DirectSoundWaveData_dp_sd90_whistle2, A(127), D(90), S(70), R(118)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_of_tutti_hit_major, A(127), D(120), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_of_tutti_hit_minor, A(127), D(120), S(127), R(120)

voicegroup_merodisgt::
	voice_directsound 36, 0, DirectSoundWaveData_dp_dis_gt_c1_16, A(127), D(90), S(127), R(120)
	voice_directsound 48, 0, DirectSoundWaveData_dp_dis_gt_c2_16, A(127), D(90), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_dp_dis_gt_c3_16, A(127), D(90), S(127), R(120)
	voice_directsound 72, 0, DirectSoundWaveData_dp_dis_gt_c4_16, A(127), D(90), S(127), R(120)
