	.align 2
voicegroup202::
	voice_directsound 60, 0, DirectSoundWaveData_dp_classic_orchestra_2_harp_long_60, 255, 249, 0, 208	@ 127/ 80/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_classic_orchestra_2_harp_long_72, 255, 246, 0, 208	@ 127/ 90/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_classic_orchestra_2_harp_long_84, 255, 242, 0, 208	@ 127/100/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_classic_orchestra_2_harp_long_96, 255, 233, 0, 197	@ 127/110/  1/118/ 64
