	.align 2
voicegroup261::
	voice_directsound 48, 0, DirectSoundWaveData_pmd2_slapbass_c2, 255, 0, 255, 100
	voice_directsound 84, 0, DirectSoundWaveData_pmd1_musicbox_c5, 255, 244, 0, 210
	voice_keysplit voicegroup261_violin, KeySplitTable2 - 10
	voice_directsound 72, 0, DirectSoundWaveData_pmd1_percorgan_c4, 255, 0, 255, 100
	voice_keysplit voicegroup261_string, KeySplitTable87
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_synthbass1_c2, 255, 0, 255, 100
	voice_directsound 81, 0, DirectSoundWaveData_pmd2_square, 255, 0, 255, 0
	voice_directsound 67, 0, DirectSoundWaveData_pmd2_brassoctave_g4, 255, 0, 255, 100
	voice_directsound 84, 0, DirectSoundWaveData_pmd1_panflute2_c6, 255, 0, 255, 127
	voice_directsound 77, 0, DirectSoundWaveData_pmd1_frenchhorn_f4, 255, 0, 255, 127
	voice_keysplit_all voicegroup261_kit - 18 * 0xc

voicegroup261_violin::
	voice_directsound 73, 0, DirectSoundWaveData_pmd1_violin_cs4, 255, 0, 255, 100
	voice_directsound 79, 0, DirectSoundWaveData_pmd1_violin_g4, 255, 0, 255, 100
	voice_directsound 91, 0, DirectSoundWaveData_pmd1_violin_g5, 255, 0, 255, 100

voicegroup261_string::
	voice_directsound 60, 0, DirectSoundWaveData_pmd1_strings_c4, 255, 0, 255, 127
	voice_directsound 72, 0, DirectSoundWaveData_pmd1_strings_c5, 255, 0, 255, 127

voicegroup261_kit::
	voice_directsound 60, 16, DirectSoundWaveData_pmd1_crashcym, 255, 242, 0, 127
	voice_directsound 60, 40, DirectSoundWaveData_pmd1_crashcym, 255, 242, 0, 127
	voice_directsound 61, 45, DirectSoundWaveData_pmd1_crashcym, 255, 242, 0, 127
	voice_directsound 62, 70, DirectSoundWaveData_pmd1_crashcym, 255, 242, 0, 127
	voice_directsound 60, 75, DirectSoundWaveData_pmd1_crashcym, 255, 242, 0, 127
	voice_directsound 60, 96, DirectSoundWaveData_pmd1_crashcym, 255, 242, 0, 127
	voice_directsound 63, 108, DirectSoundWaveData_pmd1_crashcym, 255, 242, 0, 127
	voice_directsound 63, 60, DirectSoundWaveData_pmd1_crashcym2, 255, 242, 0, 127
	voice_directsound 62, 75, DirectSoundWaveData_pmd1_crashcym2, 255, 242, 0, 127
	voice_directsound 60, 96, DirectSoundWaveData_pmd1_crashcym2, 255, 242, 0, 127
	voice_directsound 60, 25, DirectSoundWaveData_pmd2_cymbal_loop, 255, 242, 0, 127
	voice_directsound 60, 40, DirectSoundWaveData_pmd2_cymbal_loop, 255, 242, 0, 127
	voice_directsound 60, 70, DirectSoundWaveData_pmd2_cymbal_loop, 255, 242, 0, 127
	voice_directsound 60, 88, DirectSoundWaveData_pmd2_cymbal_loop, 255, 242, 0, 127
	voice_directsound 62, 96, DirectSoundWaveData_pmd2_cymbal_loop, 255, 242, 0, 127
	voice_directsound 60, 100, DirectSoundWaveData_pmd2_cymbal_loop, 255, 242, 0, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_kick, 255, 242, 0, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 56, 20, DirectSoundWaveData_pmd1_tom, 255, 242, 0, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 64, DirectSoundWaveData_pmd1_snare6, 255, 242, 0, 127
	voice_directsound 63, 80, DirectSoundWaveData_pmd1_tom, 255, 242, 0, 127
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 66, 120, DirectSoundWaveData_pmd1_tom, 255, 242, 0, 127
	voice_directsound 65, 32, DirectSoundWaveData_pmd1_hihat_closed, 255, 242, 0, 127
	voice_directsound 65, 32, DirectSoundWaveData_pmd1_hihat_open, 255, 242, 0, 127
