	.align 2
voicegroup191::
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_reverse_cymbal, 255, 0, 255, 16	@ 127/127/127/126/ 64
	voice_keysplit_all voicegroup198				@ drum kit 1
	voice_keysplit voicegroup196, KeySplitTable10	@ ew grand piano
	voice_keysplit voicegroup256, KeySplitTable98	@ ew grand piano low
	voice_keysplit voicegroup210, KeySplitTable22	@ sd90 soft rhodes
	voice_keysplit voicegroup257, KeySplitTable13	@ sd90 fm e.piano
	voice_keysplit_all voicegroup214				@ drum kit 2
	voice_keysplit voicegroup258, KeySplitTable99	@ sd90 fm e.piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_glocken2, 255, 246, 0, 208	@ 127/ 90/  0/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 40, 197	@ 126/100/ 50/118/ 64
	voice_keysplit voicegroup209, KeySplitTable21	@ sd90 vibraphone 2
	voice_keysplit voicegroup197, KeySplitTable11	@ sd90 marimba 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup211, KeySplitTable23	@ sd90 tubular bell 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup213				@ qy70 dance kit
	voice_keysplit voicegroup204, KeySplitTable17	@ sd90 perky spin
	voice_keysplit voicegroup193, KeySplitTable7	@ retro sampler organ b3 ham
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_organ2, 255, 172, 235, 178	@ 127/122/122/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_qy70_doublsaw, 255, 197, 255, 178	@ 127/120/127/120/ 64
	voice_keysplit voicegroup194, KeySplitTable8	@ sd90 french accordion
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_harmonica2, 114, 246, 191, 178	@ 116/ 90/110/120/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup203, KeySplitTable16	@ prosamples 16 dist gtr
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 25, 0	@ 126/100/ 40/127/ 64
	voice_keysplit voicegroup212, KeySplitTable24	@ zero-g woody bass
	voice_directsound 60, 0, DirectSoundWaveData_dp_ps16_stingray_bass_hard, 255, 251, 0, 208	@ 127/ 60/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_pick_bass, 255, 251, 0, 208	@ 127/ 60/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_woody_bass_38, 255, 0, 255, 197	@ 127/127/127/118/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_slap_bass1, 255, 0, 255, 216	@ 127/127/127/114/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_bass_filter_slaps, 255, 64, 255, 197	@ 127/125/127/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_mg303_bass, 255, 0, 255, 221	@ 127/127/127/112/ 64
	voice_keysplit voicegroup201, KeySplitTable14	@ sd90 violin vib
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 252, 0, 48	@ 127/ 50/  0/125/ 64
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_wind, 67, 243, 155, 225	@  99/ 99/ 99/110/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup360, KeySplitTable35	@ prosamples 41 violin pizzicato forte
	voice_keysplit voicegroup202, KeySplitTable15	@ classic orchestra 2 harp long
	voice_keysplit voicegroup208, KeySplitTable18	@ classic orchestra timpani
	voice_keysplit voicegroup195, KeySplitTable9	@ sd90 strings 2
	voice_directsound 60, 0, DirectSoundWaveData_dp_ps55_cello_section_61, 255, 197, 255, 197	@ 127/120/127/118/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_ps51_french_horns_59, 255, 197, 255, 225	@ 127/120/127/110/ 64
	voice_keysplit voicegroup205, KeySplitTable18	@ sd90 timpani 2
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 250, 0, 225	@ 127/ 70/  0/110/ 64
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_square_wave, 255, 250, 0, 178	@ 127/ 70/  0/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 255, 0, 255, 0	@ 125/127/127/127/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_trinity_pop_u_wit_dis, 255, 197, 255, 221	@ 127/120/127/112/ 64
	voice_keysplit voicegroup192, KeySplitTable6	@ ew pop brass 3tp sus
	voice_keysplit voicegroup199, KeySplitTable12	@ sd90 solo bone
	voice_keysplit voicegroup206, KeySplitTable19	@ sd90 tuba 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup200, KeySplitTable13	@ sd90 french horns 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_sc88pro_p5_bass, 255, 64, 255, 216	@ 127/125/127/114/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 101, 225	@ 124/100/ 80/110/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_sy77_clarinet_60, 255, 242, 159, 216	@ 127/100/100/114/ 64
	voice_directsound 60, 0, DirectSoundWaveData_puresquare_50, 255, 242, 101, 178	@ 124/100/ 80/120/ 64
	voice_keysplit voicegroup207, KeySplitTable20	@ sd90 flute 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_ps13_classic_choir_ahh_60, 255, 197, 255, 178	@ 127/120/127/120/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_of_tutti_hit_major, 255, 197, 255, 178	@ 127/120/127/120/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_of_tutti_hit_minor, 255, 197, 255, 178	@ 127/120/127/120/ 64
