	.align 2
voicegroup278::
@	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_acoustic_grand_piano_36, 255, 249, 0, 225	@ 127/ 75/  1/110/ 64 @ todo: find actual adrs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_acoustic_grand_piano_48, 255, 249, 0, 225	@ 127/ 75/  1/110/ 64 @ todo: find actual adrs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_acoustic_grand_piano_60, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64 @ todo: find actual adrs
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_acoustic_grand_piano_72, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_acoustic_grand_piano_84, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64
