	.align 2
voicegroup209::
	voice_keysplit_all voicegroup209_drumset - 0xc * 27
	voice_directsound 72, 0, DirectSoundWaveData_bw_vibraphone_wb_c5_22, A(127), D(80), S(10), R(116)
	voice_directsound 36, 0, DirectSoundWaveData_hg_plugsound_pro_elastik_36, A(127), D(125), S(120), R(120)
	voice_keysplit voicegroup209_guitar, KeySplitTable_DPdistgt1_012
	voice_keysplit voicegroup209_flute, KeySplitTable_BWflute2_12
	voice_keysplit voicegroup209_trumpet, KeySplitTable_BWtrumpet_champ
	voice_directsound 41, 0, DirectSoundWaveData_dp_classic_orchestra_timpani_41, A(127), D(80), S(1), R(116)
	voice_keysplit voicegroup209_strings, KeySplitTable_BWstrings
	voice_directsound 37, 0, DirectSoundWaveData_bw_independence_pro_khso_trombones_stc, A(127), D(125), S(120), R(120)
	voice_keysplit voicegroup209_trombone, KeySplitTable_DPtimpani1
	voice_keysplit voicegroup209_horn, KeySplitTable_BWnylonstrguitar

voicegroup209_drumset::
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_standard2_clap, A(127), D(120), S(120), R(116)
	voice_directsound 60, 64, DirectSoundWaveData_bw_ps15_kick120, A(127), D(127), S(120), R(116)
	voice_directsound 61, 64, DirectSoundWaveData_bw_ps15_kick120, A(127), D(127), S(120), R(116)
	voice_directsound 62, 64, DirectSoundWaveData_bw_ps15_kick120, A(127), D(127), S(120), R(116)
	voice_directsound 63, 64, DirectSoundWaveData_bw_ps15_kick120, A(127), D(127), S(120), R(116)
	voice_directsound 64, 64, DirectSoundWaveData_bw_ps15_kick120, A(127), D(127), S(120), R(116)
	voice_directsound 65, 64, DirectSoundWaveData_bw_ps15_kick120, A(127), D(127), S(120), R(116)
	voice_directsound 66, 64, DirectSoundWaveData_bw_ps15_kick120, A(127), D(127), S(120), R(116)
	voice_directsound 60, 64, DirectSoundWaveData_dp_dance_drums_kick, A(127), D(127), S(127), R(127)
	voice_directsound 61, 64, DirectSoundWaveData_dp_dance_drums_kick, A(127), D(127), S(127), R(127)
	voice_directsound 62, 64, DirectSoundWaveData_dp_dance_drums_kick, A(127), D(127), S(127), R(127)
	voice_directsound 63, 64, DirectSoundWaveData_dp_dance_drums_kick, A(127), D(127), S(127), R(127)
	voice_directsound 64, 64, DirectSoundWaveData_dp_dance_drums_kick, A(127), D(127), S(127), R(127)
	voice_directsound 60, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(116)
	voice_directsound 61, 64, DirectSoundWaveData_dp_sd90_power2_snare, A(127), D(114), S(90), R(116)
	voice_directsound 60, 80, DirectSoundWaveData_dp_sd90_standard2_chh, A(127), D(127), S(120), R(125)
	voice_directsound 61, 80, DirectSoundWaveData_dp_sd90_standard2_chh, A(127), D(127), S(120), R(125)
	voice_directsound 62, 80, DirectSoundWaveData_dp_sd90_standard2_chh, A(127), D(127), S(120), R(125)
	voice_directsound 63, 80, DirectSoundWaveData_dp_sd90_standard2_chh, A(127), D(127), S(120), R(125)
	voice_directsound 60, 80, DirectSoundWaveData_dp_sd90_standard2_ohh, A(127), D(102), S(0), R(127)
	voice_directsound 61, 80, DirectSoundWaveData_dp_sd90_standard2_ohh, A(127), D(102), S(0), R(127)
	voice_directsound 62, 80, DirectSoundWaveData_dp_sd90_standard2_ohh, A(127), D(102), S(0), R(127)
	voice_directsound 63, 80, DirectSoundWaveData_dp_sd90_standard2_ohh, A(127), D(102), S(0), R(127)
	voice_directsound 64, 80, DirectSoundWaveData_dp_sd90_standard2_ohh, A(127), D(102), S(0), R(127)
	voice_directsound 65, 80, DirectSoundWaveData_dp_sd90_standard2_ohh, A(127), D(102), S(0), R(127)
	voice_directsound 66, 80, DirectSoundWaveData_dp_sd90_standard2_ohh, A(127), D(102), S(0), R(127)
	voice_directsound 60, 30, DirectSoundWaveData_dp_dance_drums_ride_bell, A(127), D(70), S(0), R(115)
	voice_directsound 61, 30, DirectSoundWaveData_dp_dance_drums_ride_bell, A(127), D(70), S(0), R(115)
	voice_directsound 62, 30, DirectSoundWaveData_dp_dance_drums_ride_bell, A(127), D(70), S(0), R(115)
	voice_directsound 63, 30, DirectSoundWaveData_dp_dance_drums_ride_bell, A(127), D(70), S(0), R(115)
	voice_directsound 64, 30, DirectSoundWaveData_dp_dance_drums_ride_bell, A(127), D(70), S(0), R(115)
	voice_directsound 65, 30, DirectSoundWaveData_dp_dance_drums_ride_bell, A(127), D(70), S(0), R(115)
	voice_directsound 66, 30, DirectSoundWaveData_dp_dance_drums_ride_bell, A(127), D(70), S(0), R(115)
	voice_directsound 67, 30, DirectSoundWaveData_dp_dance_drums_ride_bell, A(127), D(70), S(0), R(115)
	voice_directsound 60, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 61, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 62, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 63, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 64, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 65, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 66, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 67, 64, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 60, 114, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 61, 114, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 62, 114, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 63, 114, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 64, 114, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 65, 114, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 66, 114, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 67, 114, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)
	voice_directsound 60, 14, DirectSoundWaveData_hg_battery3_rock_crash_cymbal2, A(127), D(90), S(0), R(114)

voicegroup209_guitar::
	voice_directsound 40, 0, DirectSoundWaveData_dp_ps16_dist_gtr_40, A(127), D(30), S(1), R(126)
	voice_directsound 48, 0, DirectSoundWaveData_dp_ps16_dist_gtr_48, A(127), D(30), S(1), R(126)
	voice_directsound 64, 0, DirectSoundWaveData_dp_ps16_dist_gtr_64, A(127), D(30), S(1), R(126)

voicegroup209_flute::
	voice_directsound 72, 0, DirectSoundWaveData_bw_ps55_flute_72_22, A(127), D(90), S(100), R(118)
	voice_directsound 81, 0, DirectSoundWaveData_bw_ps55_flute_81_22, A(127), D(90), S(100), R(118)

voicegroup209_trumpet::
	voice_directsound 60, 0, DirectSoundWaveData_hg_kfl_trumpet_ensemble_60, A(127), D(100), S(110), R(116)
	voice_directsound 69, 0, DirectSoundWaveData_hg_kfl_trumpet_ensemble_69, A(127), D(100), S(110), R(116)
	voice_directsound 79, 0, DirectSoundWaveData_hg_kfl_trumpet_ensemble_79, A(127), D(110), S(110), R(116)

voicegroup209_strings::
	voice_directsound 60, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_60, A(127), D(100), S(110), R(116)
	voice_directsound 69, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_69, A(127), D(100), S(110), R(116)
	voice_directsound 77, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_77, A(127), D(100), S(110), R(116)
	voice_directsound 84, 0, DirectSoundWaveData_hg_sampletank_string_orchestra_84, A(127), D(100), S(110), R(116)

voicegroup209_trombone::
	voice_directsound 43, 0, DirectSoundWaveData_hg_kfl_trombone_ensemble_43, A(127), D(100), S(115), R(116)
	voice_directsound 52, 0, DirectSoundWaveData_hg_kfl_trombone_ensemble_52, A(127), D(100), S(115), R(116)

voicegroup209_horn::
	voice_directsound 48, 0, DirectSoundWaveData_bw_kfl_french_horn_ensemble_48, A(127), D(110), S(120), R(116)
	voice_directsound 53, 0, DirectSoundWaveData_hg_kfl_french_horn_ensemble_53, A(127), D(110), S(120), R(116)
	voice_directsound 62, 0, DirectSoundWaveData_hg_kfl_french_horn_ensemble_62, A(127), D(110), S(120), R(116)
