	.align 2
voicegroup340::
	voice_directsound 60, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, 255, 0, 227, 208			@ 127/127/120/116/ 64
	voice_directsound 61, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, 255, 0, 227, 208			@ 127/127/120/116/ 64
	voice_directsound 62, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, 255, 0, 227, 208			@ 127/127/120/116/ 64
	voice_directsound 63, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, 255, 0, 227, 208			@ 127/127/120/116/ 64
	voice_directsound 64, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, 255, 0, 227, 208			@ 127/127/120/116/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_unknown_synth_kick_wcs, 255, 0, 227, 208				@ 127/127/120/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_unknown_synth_kick_wcs, 255, 0, 227, 208				@ 127/127/120/116/ 64
	voice_directsound 62, 64, DirectSoundWaveData_bw_unknown_synth_kick_wcs, 255, 0, 227, 208				@ 127/127/120/116/ 64
	voice_directsound 63, 64, DirectSoundWaveData_bw_unknown_synth_kick_wcs, 255, 0, 227, 208				@ 127/127/120/116/ 64
	voice_directsound 60, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare_e2, 255, 225, 127, 208		@ 127/114/ 90/116/ 64
	voice_directsound 61, 64, DirectSoundWaveData_bw_plugsound_pro_analog_snare_e2, 255, 225, 127, 208		@ 127/114/ 90/116/ 64
	voice_directsound 60, 30, DirectSoundWaveData_bw_plugsound_pro_analog_hihat_closed, 255, 239, 0, 208	@ 127/105/  0/116/ 30
	voice_directsound 61, 30, DirectSoundWaveData_bw_plugsound_pro_analog_hihat_closed, 255, 239, 0, 208	@ 127/105/  0/116/ 30
	voice_directsound 62, 30, DirectSoundWaveData_bw_plugsound_pro_analog_hihat_closed, 255, 239, 0, 208	@ 127/105/  0/116/ 30
	voice_directsound 63, 30, DirectSoundWaveData_bw_plugsound_pro_analog_hihat_closed, 255, 239, 0, 208	@ 127/105/  0/116/ 30
	voice_directsound 60, 30, DirectSoundWaveData_bw_plugsound_pro_analog_hihat_open, 255, 241, 0, 208		@ 127/102/  0/116/ 30
	voice_directsound 76, 50, DirectSoundWaveData_bw_zg_dpt_orch_snare_16_18_02, 255, 0, 227, 208			@ 127/127/120/116/ 64
	voice_directsound 60, 40, DirectSoundWaveData_bw_kfl_cymbals_a_due, 255, 250, 0, 216					@ 127/ 70/  0/114/ 40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_elastik_36, 255, 64, 227, 178	@ 127/125/120/120/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup254, KeySplitTable102	@ sampletank 2.5 xl string orchestra
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_cello_sus_43, 188, 242, 255, 208	@ 120/100/127/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_plugsound_pro_timpani_55, 255, 252, 0, 208	@ 127/ 50/  1/116/ 64
	voice_keysplit voicegroup315, KeySplitTable71	@ kfl trumpet ensemble
	voice_keysplit voicegroup285, KeySplitTable18	@ kfl trombone ensemble
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup277, KeySplitTable66	@ kfl french horn ensemble
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_zg_of_tutti_hit_minor_60, 255, 0, 255, 208	@ 127/127/127/116/ 64
	voice_keysplit voicegroup338, KeySplitTable103	@ ew symphonic choirs full chorus ah mod
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup340 - 31 * 12				@ drum kit 1
	voice_keysplit_all voicegroup340 - 31 * 12				@ drum kit 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_bw_unknown_suspended_cymbal_40, 255, 0, 255, 237	@ 127/127/127/100/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_zg_total_drum_bass_160_leonora, 255, 0, 255, 88	@ 127/127/127/124/ 64
