	.align 2
voicegroup252::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_43, 255, 251, 14, 197	@ 127/ 60/ 30/118/ 64
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_55, 255, 251, 14, 197	@ 127/ 60/ 30/118/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_64, 255, 251, 14, 197	@ 127/ 60/ 30/118/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_martin_soft2_72, 255, 251, 14, 197	@ 127/ 60/ 30/118/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
