	.align 2
voicegroup238::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_36, 255, 249, 0, 225	@ 127/ 75/  1/110/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_48, 255, 249, 0, 225	@ 127/ 75/  1/110/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_60, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_72, 255, 249, 0, 208	@ 127/ 80/  1/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_acoustic_grand_piano_84, 255, 248, 0, 208	@ 127/ 85/  1/116/ 64
