	.align 2
voicegroup250::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_music_box_60, 255, 246, 0, 208	@ 127/ 90/  1/116/ 64
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_music_box_72, 255, 246, 0, 208	@ 127/ 90/  1/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_music_box_84, 255, 246, 0, 208	@ 127/ 90/  1/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
