	.align 2
voicegroup215::
	voice_keysplit voicegroup238, KeySplitTable43	@ plugsound pro acoustic grand piano
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup243, KeySplitTable44	@ plugsound pro acoustic grand piano (octaved)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup247, KeySplitTable13	@ plugsound pro a suitcase medium
	voice_keysplit voicegroup232, KeySplitTable39	@ plugsound pro vibraphone 1
	voice_keysplit voicegroup231, KeySplitTable38	@ kfl marimba
	voice_keysplit voicegroup229, KeySplitTable28	@ kfl xylophone
	voice_keysplit voicegroup227, KeySplitTable35	@ ewso orch chimes
	voice_keysplit voicegroup233, KeySplitTable39	@ kfl glockenspiel
	voice_keysplit voicegroup250, KeySplitTable38	@ plugsound pro music box
	voice_keysplit voicegroup240, KeySplitTable40	@ plugsound pro full organ slow
	voice_keysplit voicegroup249, KeySplitTable40	@ plugsound pro jazz organ
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup252, KeySplitTable49	@ plugsound pro martin soft 2
	voice_keysplit voicegroup239, KeySplitTable42	@ prosamples 16 dist gtr (rel 125)
	voice_keysplit voicegroup237, KeySplitTable42	@ prosamples 16 dist gtr (rel 120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup220, KeySplitTable29	@ plugsound pro jazz double bass hard
	voice_keysplit voicegroup244, KeySplitTable45	@ plugsound pro ampeg ac. bass -full
	voice_directsound 36, 0, DirectSoundWaveData_dp_sd90_slap_bass1, A(127), D(127), S(127), R(118)
	voice_keysplit voicegroup224, KeySplitTable33	@ plugsound pro elastik
	voice_keysplit voicegroup216, KeySplitTable25	@ sampletank 2.5 xl string orchestra
	voice_keysplit voicegroup226, KeySplitTable34	@ plugsound pro violin sus
	voice_keysplit voicegroup223, KeySplitTable32	@ plugsound pro cello sus
	voice_keysplit voicegroup228, KeySplitTable36	@ kfl cello/violin ensemble pizz
	voice_keysplit voicegroup242, KeySplitTable40	@ kfl harp
	voice_keysplit voicegroup234, KeySplitTable40	@ plugsound pro timpani
	voice_keysplit voicegroup219, KeySplitTable28	@ kfl trumpet ensemble
	voice_keysplit voicegroup225, KeySplitTable32	@ kfl trombone ensemble
	voice_keysplit voicegroup217, KeySplitTable26	@ kfl french horn
	voice_keysplit voicegroup218, KeySplitTable27	@ kfl french horn ensemble
	voice_keysplit voicegroup222, KeySplitTable31	@ kfl oboe
	voice_keysplit voicegroup230, KeySplitTable37	@ sampletank 2.5 xl clarinet
	voice_keysplit voicegroup221, KeySplitTable30	@ plugsound pro flute sus
	voice_keysplit voicegroup246, KeySplitTable47	@ plugsound pro bassoon sus
	voice_keysplit voicegroup236, KeySplitTable41	@ plugsound pro orchestra hit (octaved)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit_all voicegroup235				@ drum kit
	voice_keysplit_all voicegroup251				@ kaeru cafe taiko kit
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_keysplit voicegroup248, KeySplitTable48	@ machfive 2 koto 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 48, 0, DirectSoundWaveData_sc88pro_square_wave, A(127), D(70), S(0), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, A(125), D(127), S(127), R(127)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundSynthData_squ50, A(124), D(100), S(80), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 84, 0, DirectSoundWaveData_dp_sd90_whistle2, A(127), D(90), S(70), R(118)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_of_tutti_hit_major, A(127), D(120), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_dp_zg_of_tutti_hit_minor, A(127), D(120), S(127), R(120)
	voice_keysplit_all voicegroup241				@ qy70 dance kit
	voice_keysplit voicegroup208, KeySplitTable18	@ classic orchestra timpani
	voice_directsound 36, 0, DirectSoundWaveData_dp_zg_bass_filter_slaps, A(127), D(125), S(127), R(118)
	voice_directsound 36, 0, DirectSoundWaveData_dp_sd90_mg303_bass, A(127), D(127), S(127), R(112)
	voice_directsound 60, 0, DirectSoundWaveData_dp_qy70_doublsaw, A(127), D(120), S(127), R(120)
	voice_keysplit voicegroup245, KeySplitTable46	@ machfive 2 shamisen 1
	voice_directsound 60, 0, DirectSoundWaveData_hg_kaeru_cafe_hyoshigi, A(127), D(127), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_hg_kaeru_cafe_kodaiko2, A(127), D(127), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_hg_kaeru_cafe_kotsu, A(127), D(127), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_hg_discovery_japan_suzu, A(127), D(127), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_hg_machfive2_taiko, A(127), D(127), S(127), R(126)
	voice_directsound 48, 0, DirectSoundWaveData_dp_ps13_classic_choir_ahh_48, A(127), D(120), S(127), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_hg_ps13_classic_choir_ahh_60, A(127), D(120), S(127), R(120)
	voice_directsound 60, 0, DirectSoundWaveData_dp_sd90_reverse_cymbal, A(127), D(120), S(127), R(120)
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound 60, 0, DirectSoundWaveData_dp_qy70_dance_snare, A(127), D(127), S(127), R(120)
