	.align 2
voicegroup196::
	voice_directsound 43, 0, DirectSoundWaveData_dp_ew_grand_piano_43, 255, 249, 0, 225	@ 127/ 75/  1/110/ 64
	voice_directsound 48, 0, DirectSoundWaveData_dp_ew_grand_piano_48, 255, 249, 0, 225	@ 127/ 75/  1/110/ 64
	voice_directsound 60, 0, DirectSoundWaveData_dp_ew_grand_piano_60, 255, 249, 0, 208	@ 127/ 75/  1/116/ 64
	voice_directsound 67, 0, DirectSoundWaveData_dp_ew_grand_piano_67, 255, 249, 0, 208	@ 127/ 80/  1/116/ 64
	voice_directsound 72, 0, DirectSoundWaveData_dp_ew_grand_piano_72, 255, 248, 0, 208	@ 127/ 85/  1/116/ 64
	voice_directsound 77, 0, DirectSoundWaveData_dp_ew_grand_piano_77, 255, 246, 0, 208	@ 127/ 90/  1/116/ 64
	voice_directsound 84, 0, DirectSoundWaveData_dp_ew_grand_piano_84, 255, 246, 0, 208	@ 127/ 90/  1/116/ 64
	voice_directsound 96, 0, DirectSoundWaveData_dp_ew_grand_piano_96, 255, 246, 0, 208	@ 127/ 90/  1/116/ 64
