	.align 2
voicegroup254::
	voice_directsound 60, 0, DirectSoundWaveData_bw_sampletank_string_orchestra_60, 255, 242, 191, 208	@ 127/100/110/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_sampletank_string_orchestra_69, 255, 242, 191, 208	@ 127/100/110/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_sampletank_string_orchestra_77, 255, 242, 191, 208	@ 127/100/110/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_bw_sampletank_string_orchestra_84, 255, 242, 191, 208	@ 127/100/110/116/ 64
