	.align 2
voicegroup226::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_violin_sus_64, 188, 242, 255, 208	@ 120/100/127/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_violin_sus_72, 188, 246, 255, 208	@ 120/ 90/127/116/ 64
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_violin_sus_81, 188, 246, 255, 208	@ 120/ 90/127/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
