	.align 2
voicegroup249::
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_jazz_organ_48, 255, 0, 255, 208	@ 127/127/127/116/ 64
	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_jazz_organ_60, 255, 0, 255, 208	@ 127/127/127/116/ 64
@	voice_directsound 60, 0, DirectSoundWaveData_hg_plugsound_pro_jazz_organ_72, 255, 0, 255, 208	@ 127/127/127/116/ 64
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
