ViridianForest_EventScript_Sparkle_Potion::
	goto_if_set FLAG_HIDDEN_ITEM_VIRIDIAN_FOREST_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 3, 22, 0
	setvar VAR_TEMP_F, 1
	end

ViridianForest_EventScript_Sparkle_Antidote::
	goto_if_set FLAG_HIDDEN_ITEM_VIRIDIAN_FOREST_ANTIDOTE, EventScript_ReleaseEnd
	dofieldeffectsparkle 28, 57, 0
	setvar VAR_TEMP_E, 1
	end

MtMoon_B2F_EventScript_Sparkle_MoonStone::
	goto_if_set FLAG_HIDDEN_ITEM_MT_MOON_B2F_MOON_STONE, EventScript_ReleaseEnd
	dofieldeffectsparkle 20, 16, 0
	setvar VAR_TEMP_F, 1
	end

MtMoon_B2F_EventScript_Sparkle_MoonStone2::
	goto_if_set FLAG_HIDDEN_ITEM_MT_MOON_B2F_MOON_STONE, EventScript_ReleaseEnd
	dofieldeffectsparkle 20, 16, 0
	setvar VAR_TEMP_D, 1
	end

MtMoon_B2F_EventScript_Sparkle_Ether::
	goto_if_set FLAG_HIDDEN_ITEM_MT_MOON_B2F_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 39, 11, 0
	setvar VAR_TEMP_E, 1
	end

MtMoon_B1F_EventScript_Sparkle_TinyMushroom::
	goto_if_set FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM, EventScript_ReleaseEnd
	dofieldeffectsparkle 46, 2, 0
	setvar VAR_TEMP_F, 1
	end

MtMoon_B1F_EventScript_Sparkle_TinyMushroom2::
	goto_if_set FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 26, 2, 0
	setvar VAR_TEMP_F, 1
	end

MtMoon_B1F_EventScript_Sparkle_TinyMushroom3::
	goto_if_set FLAG_HIDDEN_ITEM_MT_MOON_B1F_TINY_MUSHROOM_3, EventScript_ReleaseEnd
	dofieldeffectsparkle 39, 34, 0
	setvar VAR_TEMP_F, 1
	end

MtMoon_B1F_EventScript_Sparkle_BigMushroom::
	goto_if_set FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM, EventScript_ReleaseEnd
	dofieldeffectsparkle 24, 35, 0
	setvar VAR_TEMP_E, 1
	end

MtMoon_B1F_EventScript_Sparkle_BigMushroom_2::
	goto_if_set FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 6, 12, 0
	setvar VAR_TEMP_F, 1
	end

MtMoon_B1F_EventScript_Sparkle_BigMushroom3::
	goto_if_set FLAG_HIDDEN_ITEM_MT_MOON_B1F_BIG_MUSHROOM_3, EventScript_ReleaseEnd
	dofieldeffectsparkle 25, 34, 0
	setvar VAR_TEMP_D, 1
	end

Route25_EventScript_Sparkle_Elixir::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE25_ELIXIR, EventScript_ReleaseEnd
	dofieldeffectsparkle 14, 2, 0
	setvar VAR_TEMP_F, 1
	end

Route25_EventScript_Sparkle_Ether::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE25_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 58, 6, 0
	setvar VAR_TEMP_E, 1
	end

Route25_EventScript_Sparkle_OranBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE25_ORAN_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 33, 8, 0
	setvar VAR_TEMP_D, 1
	setvar VAR_TEMP_B, 0
	end

Route25_EventScript_Sparkle_OranBerry2::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE25_ORAN_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 33, 8, 0
	setvar VAR_TEMP_B, 1
	setvar VAR_TEMP_D, 0
	end

Route25_EventScript_Sparkle_BlukBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE25_BLUK_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 40, 3, 0
	setvar VAR_TEMP_C, 1
	end

Route9_EventScript_Sparkle_Ether::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE9_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 7, 0
	setvar VAR_TEMP_F, 1
	end

Route9_EventScript_Sparkle_Ether2::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE9_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 7, 0
	setvar VAR_TEMP_C, 1
	setvar VAR_TEMP_F, 1
	end

Route9_EventScript_Sparkle_RareCandy::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE9_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 63, 2, 0
	setvar VAR_TEMP_E, 1
	end

Route9_EventScript_Sparkle_RareCandy2::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE9_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 63, 2, 0
	setvar VAR_TEMP_E, 1
	setvar VAR_TEMP_B, 1
	end

Route9_EventScript_Sparkle_ChestoBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE9_CHESTO_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 48, 2, 0
	setvar VAR_TEMP_D, 1
	end

SSAnne_B1F_Corridor_EventScript_Sparkle_HyperPotion::
	goto_if_set FLAG_HIDDEN_ITEM_SSANNE_B1F_CORRIDOR_HYPER_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 21, 5, 0
	setvar VAR_TEMP_F, 1
	end

SSAnne_Kitchen_EventScript_Sparkle_PechaBerry::
	goto_if_set FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_PECHA_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 14, 4, 0
	setvar VAR_TEMP_F, 1
	end

SSAnne_Kitchen_EventScript_Sparkle_CheriBerry::
	goto_if_set FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_CHERI_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 14, 6, 0
	setvar VAR_TEMP_E, 1
	end

SSAnne_Kitchen_EventScript_Sparkle_ChestoBerry::
	goto_if_set FLAG_HIDDEN_ITEM_SSANNE_KITCHEN_CHESTO_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 14, 8, 0
	setvar VAR_TEMP_D, 1
	end

SSAnne_Exterior_EventScript_Sparkle_LavaCookie::
	goto_if_set FLAG_HIDDEN_ITEM_SSANNE_EXTERIOR_LAVA_COOKIE, EventScript_ReleaseEnd
	dofieldeffectsparkle 58, 28, 0
	setvar VAR_TEMP_F, 1
	end

Route10_EventScript_Sparkle_SuperPotion::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE10_SUPER_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 10, 19, 0
	setvar VAR_TEMP_F, 1
	end

Route10_EventScript_Sparkle_MaxEther::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE10_MAX_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 12, 40, 0
	setvar VAR_TEMP_E, 1
	end

Route10_EventScript_Sparkle_PersimBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE10_PERSIM_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 17, 29, 0
	setvar VAR_TEMP_D, 1
	setvar VAR_TEMP_C, 1
	end

Route10_EventScript_Sparkle_PersimBerry2::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE10_PERSIM_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 17, 29, 0
	setvar VAR_TEMP_C, 1
	end

Route10_EventScript_Sparkle_CheriBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE10_CHERI_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 6, 26, 0
	setvar VAR_TEMP_B, 1
	end

Route10_EventScript_Sparkle_NanabBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE10_NANAB_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 20, 57, 0
	setvar VAR_TEMP_A, 1
	end

RocketHideout_B1F_EventScript_Sparkle_PPUp::
	goto_if_set FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B1F_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 17, 0
	setvar VAR_TEMP_F, 1
	setvar VAR_TEMP_E, 1
	end

RocketHideout_B1F_EventScript_Sparkle_PPUp2::
	goto_if_set FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B1F_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 17, 0
	setvar VAR_TEMP_E, 1
	end

RocketHideout_B3F_EventScript_Sparkle_Nugget::
	goto_if_set FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B3F_NUGGET, EventScript_ReleaseEnd
	dofieldeffectsparkle 1, 3, 0
	setvar VAR_TEMP_F, 1
	end

RocketHideout_B4F_EventScript_Sparkle_NestBall::
	goto_if_set FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B4F_NEST_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 22, 6, 0
	setvar VAR_TEMP_F, 1
	end

RocketHideout_B4F_EventScript_Sparkle_NetBall::
	goto_if_set FLAG_HIDDEN_ITEM_ROCKET_HIDEOUT_B4F_NET_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 6, 0
	setvar VAR_TEMP_E, 1
	end

PokemonTower_5F_EventScript_Sparkle_BigMushroom::
	goto_if_set FLAG_HIDDEN_ITEM_POKEMON_TOWER_5F_BIG_MUSHROOM, EventScript_ReleaseEnd
	dofieldeffectsparkle 7, 3, 0
	setvar VAR_TEMP_F, 1
	end

Route13_EventScript_Sparkle_PPUp::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE13_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 23, 14, 0
	setvar VAR_TEMP_F, 1
	setvar VAR_TEMP_E, 1
	end

Route13_EventScript_Sparkle_PPUp2::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE13_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 23, 14, 0
	setvar VAR_TEMP_E, 1
	end

Route17_EventScript_Sparkle_RareCandy::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE17_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 18, 83, 0
	setvar VAR_TEMP_F, 1
	end

Route17_EventScript_Sparkle_FullRestore::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE17_FULL_RESTORE, EventScript_ReleaseEnd
	dofieldeffectsparkle 10, 53, 0
	setvar VAR_TEMP_E, 1
	end

Route17_EventScript_Sparkle_PPUp::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE17_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 4, 68, 0
	setvar VAR_TEMP_D, 1
	end

Route17_EventScript_Sparkle_MaxRevive::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE17_MAX_REVIVE, EventScript_ReleaseEnd
	dofieldeffectsparkle 4, 125, 0
	setvar VAR_TEMP_C, 1
	end

Route17_EventScript_Sparkle_MaxElixir::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE17_MAX_ELIXIR, EventScript_ReleaseEnd
	dofieldeffectsparkle 14, 157, 0
	setvar VAR_TEMP_B, 1
	end

SafariZone_Center_EventScript_Sparkle_LeafStone::
	goto_if_set FLAG_HIDDEN_ITEM_SAFARI_ZONE_CENTER_LEAF_STONE, EventScript_ReleaseEnd
	dofieldeffectsparkle 27, 15, 0
	setvar VAR_TEMP_F, 1
	end

SafariZone_West_EventScript_Sparkle_Revive::
	goto_if_set FLAG_HIDDEN_ITEM_SAFARI_ZONE_WEST_REVIVE, EventScript_ReleaseEnd
	dofieldeffectsparkle 13, 11, 0
	setvar VAR_TEMP_F, 1
	end

SilphCo_2F_EventScript_Sparkle_UltraBall::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_2F_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 11, 21, 0
	setvar VAR_TEMP_F, 1
	setvar VAR_TEMP_E, 1
	end

SilphCo_2F_EventScript_Sparkle_UltraBall2::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_2F_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 11, 21, 0
	setvar VAR_TEMP_E, 1
	end

SilphCo_3F_EventScript_Sparkle_Protein::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_3F_PROTEIN, EventScript_ReleaseEnd
	dofieldeffectsparkle 34, 18, 0
	setvar VAR_TEMP_F, 1
	setvar VAR_TEMP_E, 1
	end

SilphCo_3F_EventScript_Sparkle_Protein2::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_3F_PROTEIN, EventScript_ReleaseEnd
	dofieldeffectsparkle 34, 18, 0
	setvar VAR_TEMP_E, 1
	end

SilphCo_4F_EventScript_Sparkle_Iron::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_4F_IRON, EventScript_ReleaseEnd
	dofieldeffectsparkle 35, 20, 0
	setvar VAR_TEMP_F, 1
	end

SilphCo_5F_EventScript_Sparkle_Elixir::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_5F_ELIXIR, EventScript_ReleaseEnd
	dofieldeffectsparkle 13, 16, 0
	setvar VAR_TEMP_F, 1
	setvar VAR_TEMP_D, 1
	end

SilphCo_5F_EventScript_Sparkle_Elixir2::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_5F_ELIXIR, EventScript_ReleaseEnd
	dofieldeffectsparkle 13, 16, 0
	setvar VAR_TEMP_D, 1
	end

SilphCo_5F_EventScript_Sparkle_PPUp::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_5F_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 32, 9, 0
	setvar VAR_TEMP_E, 1
	setvar VAR_TEMP_C, 1
	end

SilphCo_5F_EventScript_Sparkle_PPUp2::
	goto_if_set FLAG_HIDE_SILPH_ROCKETS, SilphCo_5F_EventScript_Sparkle_PPUp
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_5F_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 32, 9, 0
	setvar VAR_TEMP_C, 1
	end

SilphCo_6F_EventScript_Sparkle_Carbos::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_6F_CARBOS, EventScript_ReleaseEnd
	dofieldeffectsparkle 1, 8, 0
	setvar VAR_TEMP_F, 1
	end

SilphCo_7F_EventScript_Sparkle_Zinc::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_7F_ZINC, EventScript_ReleaseEnd
	dofieldeffectsparkle 22, 11, 0
	setvar VAR_TEMP_F, 1
	setvar VAR_TEMP_E, 1
	end

SilphCo_7F_EventScript_Sparkle_Zinc2::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_7F_ZINC, EventScript_ReleaseEnd
	dofieldeffectsparkle 22, 11, 0
	setvar VAR_TEMP_E, 1
	end

SilphCo_8F_EventScript_Sparkle_Nugget::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_8F_NUGGET, EventScript_ReleaseEnd
	dofieldeffectsparkle 29, 10, 0
	setvar VAR_TEMP_F, 1
	end

SilphCo_9F_EventScript_Sparkle_MaxPotion::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_9F_MAX_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 11, 14, 0
	setvar VAR_TEMP_F, 1
	end

SilphCo_9F_EventScript_Sparkle_Calcium::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_9F_CALCIUM, EventScript_ReleaseEnd
	dofieldeffectsparkle 5, 8, 0
	setvar VAR_TEMP_E, 1
	end

SilphCo_10F_EventScript_Sparkle_HPUp::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_10F_HP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 9, 0
	setvar VAR_TEMP_F, 1
	end

SilphCo_11F_EventScript_Sparkle_Revive::
	goto_if_set FLAG_HIDDEN_ITEM_SILPH_CO_11F_REVIVE, EventScript_ReleaseEnd
	dofieldeffectsparkle 10, 18, 0
	setvar VAR_TEMP_F, 1
	end

SaffronCity_CopycatsHouse_2F_EventScript_Sparkle_Nugget::
	goto_if_set FLAG_HIDDEN_ITEM_SAFFRON_CITY_COPYCATS_HOUSE_2F_NUGGET, EventScript_ReleaseEnd
	dofieldeffectsparkle 2, 1, 0
	setvar VAR_TEMP_F, 1
	end

PowerPlant_EventScript_Sparkle_MaxElixir::
	goto_if_set FLAG_HIDDEN_ITEM_POWER_PLANT_MAX_ELIXIR, EventScript_ReleaseEnd
	dofieldeffectsparkle 29, 16, 0
	setvar VAR_TEMP_F, 1
	setvar VAR_TEMP_D, 1
	end

PowerPlant_EventScript_Sparkle_MaxElixir2::
	goto_if_set FLAG_HIDDEN_ITEM_POWER_PLANT_MAX_ELIXIR, EventScript_ReleaseEnd
	dofieldeffectsparkle 29, 16, 0
	setvar VAR_TEMP_D, 1
	end

PowerPlant_EventScript_Sparkle_ThunderStone::
	goto_if_set FLAG_HIDDEN_ITEM_POWER_PLANT_THUNDER_STONE, EventScript_ReleaseEnd
	dofieldeffectsparkle 8, 12, 0
	setvar VAR_TEMP_E, 1
	end

SeafoamIslands_B3F_EventScript_Sparkle_Nugget::
	goto_if_set FLAG_HIDDEN_ITEM_SEAFOAM_ISLANDS_B3F_NUGGET, EventScript_ReleaseEnd
	dofieldeffectsparkle 5, 12, 0
	setvar VAR_TEMP_F, 1
	end

SeafoamIslands_B4F_EventScript_Sparkle_WaterStone::
	goto_if_set FLAG_HIDDEN_ITEM_SEAFOAM_ISLANDS_B4F_WATER_STONE, EventScript_ReleaseEnd
	dofieldeffectsparkle 13, 8, 0
	setvar VAR_TEMP_F, 1
	end

PokemonMansion_1F_EventScript_Sparkle_MoonStone::
	goto_if_set FLAG_HIDDEN_ITEM_POKEMON_MANSION_1F_MOON_STONE, EventScript_ReleaseEnd
	dofieldeffectsparkle 2, 21, 0
	setvar VAR_TEMP_F, 1
	end

PokemonMansion_3F_EventScript_Sparkle_RareCandy::
	goto_if_set FLAG_HIDDEN_ITEM_POKEMON_MANSION_3F_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 36, 13, 0
	setvar VAR_TEMP_F, 1
	end

PokemonMansion_B1F_EventScript_Sparkle_Elixir::
	goto_if_set FLAG_HIDDEN_ITEM_POKEMON_MANSION_B1F_ELIXIR, EventScript_ReleaseEnd
	dofieldeffectsparkle 35, 5, 0
	setvar VAR_TEMP_F, 1
	end

Route23_EventScript_Sparkle_FullRestore::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE23_FULL_RESTORE, EventScript_ReleaseEnd
	dofieldeffectsparkle 19, 42, 0
	setvar VAR_TEMP_F, 1
	end

Route23_EventScript_Sparkle_UltraBall::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE23_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 20, 72, 0
	setvar VAR_TEMP_E, 1
	end

Route23_EventScript_Sparkle_Max_Ether::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE23_MAX_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 11, 101, 0
	setvar VAR_TEMP_D, 1
	end

Route23_EventScript_Sparkle_LumBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE23_LUM_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 3, 18, 0
	setvar VAR_TEMP_C, 1
	end

Route23_EventScript_Sparkle_SitrusBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE23_SITRUS_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 2, 29, 0
	setvar VAR_TEMP_B, 1
	end

Route23_EventScript_Sparkle_AspearBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE23_ASPEAR_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 10, 67, 0
	setvar VAR_TEMP_A, 1
	end

Route23_EventScript_Sparkle_LeppaBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE23_LEPPA_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 3, 128, 0
	setvar VAR_TEMP_9, 1
	end

Route23_EventScript_Sparkle_MaxElixir::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE23_MAX_ELIXIR, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 8, 0
	setvar VAR_TEMP_8, 1
	end

VictoryRoad_1F_EventScript_Sparkle_UltraBall::
	goto_if_set FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 12, 12, 0
	setvar VAR_TEMP_F, 1
	end

VictoryRoad_1F_EventScript_Sparkle_FullRestore::
	goto_if_set FLAG_HIDDEN_ITEM_VICTORY_ROAD_1F_FULL_RESTORE, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 1, 0
	setvar VAR_TEMP_E, 1
	end

CeruleanCave_1F_EventScript_Sparkle_UltraBall::
	goto_if_set FLAG_HIDDEN_ITEM_CERULEAN_CAVE_1F_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 12, 2, 0
	setvar VAR_TEMP_F, 1
	end

Route11_EventScript_Sparkle_EscapeRope::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE11_ESCAPE_ROPE, EventScript_ReleaseEnd
	dofieldeffectsparkle 58, 5, 0
	setvar VAR_TEMP_F, 1
	end

Route12_EventScript_Sparkle_HyperPotion::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE12_HYPER_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 18, 57, 0
	setvar VAR_TEMP_F, 1
	end

Route12_EventScript_Sparkle_RareCandy::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE12_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 116, 0
	setvar VAR_TEMP_E, 1
	end

CeladonCity_EventScript_Sparkle_PPUp::
	goto_if_set FLAG_HIDDEN_ITEM_CELADON_CITY_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 55, 20, 0
	setvar VAR_TEMP_F, 1
	end

VermilionCity_EventScript_Sparkle_MaxEther::
	goto_if_set FLAG_HIDDEN_ITEM_VERMILION_CITY_MAX_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 14, 11, 0
	setvar VAR_TEMP_F, 1
	end

CeruleanCity_EventScript_Sparkle_RareCandy::
	goto_if_set FLAG_HIDDEN_ITEM_CERULEAN_CITY_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 18, 7, 0
	setvar VAR_TEMP_F, 1
	end

Route4_EventScript_Sparkle_GreatBall::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE4_GREAT_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 43, 2, 0
	setvar VAR_TEMP_F, 1
	end

Route4_EventScript_Sparkle_PersimBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE4_PERSIM_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 5, 4, 0
	setvar VAR_TEMP_F, 1
	end

Route4_EventScript_Sparkle_RazzBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE4_RAZZ_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 67, 17, 0
	setvar VAR_TEMP_E, 1
	end

SevenIsland_SevaultCanyon_EventScript_Sparkle_CheriBerry::
	goto_if_set FLAG_HIDDEN_ITEM_SEVEN_ISLAND_SEVAULT_CANYON_CHERI_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 66, 0
	setvar VAR_TEMP_F, 1
	end

SevenIsland_SevaultCanyon_Entrance_EventScript_Sparkle_RawstBerry::
	goto_if_set FLAG_HIDDEN_ITEM_SEVEN_ISLAND_SEVAULT_CANYON_ENTRANCE_RAWST_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 8, 29, 0
	setvar VAR_TEMP_F, 1
	end

SevenIsland_Tanoby_Ruins_EventScript_Sparkle_HeartScale::
	goto_if_set FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE, EventScript_ReleaseEnd
	dofieldeffectsparkle 33, 10, 0
	setvar VAR_TEMP_F, 1
	end

SevenIsland_Tanoby_Ruins_EventScript_Sparkle_HeartScale2::
	goto_if_set FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 86, 9, 0
	setvar VAR_TEMP_E, 1
	end

SevenIsland_Tanoby_Ruins_EventScript_Sparkle_HeartScale3::
	goto_if_set FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_3, EventScript_ReleaseEnd
	dofieldeffectsparkle 125, 5, 0
	setvar VAR_TEMP_D, 1
	end

SevenIsland_Tanoby_Ruins_EventScript_Sparkle_HeartScale4::
	goto_if_set FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TANOBY_RUINS_HEART_SCALE_4, EventScript_ReleaseEnd
	dofieldeffectsparkle 8, 2, 0
	setvar VAR_TEMP_C, 1
	end

SevenIsland_TrainerTower_EventScript_Sparkle_BigPearl::
	goto_if_set FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_BIG_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 49, 27, 0
	setvar VAR_TEMP_F, 1
	end

SevenIsland_TrainerTower_EventScript_Sparkle_Pearl::
	goto_if_set FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 47, 30, 0
	setvar VAR_TEMP_E, 1
	end

SevenIsland_TrainerTower_EventScript_Sparkle_NanabBerry::
	goto_if_set FLAG_HIDDEN_ITEM_SEVEN_ISLAND_TRAINER_TOWER_NANAB_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 59, 32, 0
	setvar VAR_TEMP_D, 1
	end

FiveIsland_RocketWarehouse_EventScript_Sparkle_NestBall::
	goto_if_set FLAG_HIDDEN_ITEM_FIVE_ISLAND_ROCKET_WAREHOUSE_NEST_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 27, 2, 0
	setvar VAR_TEMP_F, 1
	end

FiveIsland_RocketWarehouse_EventScript_Sparkle_NetBall::
	goto_if_set FLAG_HIDDEN_ITEM_FIVE_ISLAND_ROCKET_WAREHOUSE_NET_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 7, 16, 0
	setvar VAR_TEMP_E, 1
	end

FiveIsland_MemorialPillar_EventScript_Sparkle_BigPearl::
	goto_if_set FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_BIG_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 8, 52, 0
	setvar VAR_TEMP_F, 1
	end

FiveIsland_MemorialPillar_EventScript_Sparkle_RazzBerry::
	goto_if_set FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_RAZZ_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 7, 0
	setvar VAR_TEMP_E, 1
	end

FiveIsland_MemorialPillar_EventScript_Sparkle_SitrusBerry::
	goto_if_set FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_SITRUS_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 17, 22, 0
	setvar VAR_TEMP_D, 1
	end

FiveIsland_MemorialPillar_EventScript_Sparkle_BlukBerry::
	goto_if_set FLAG_HIDDEN_ITEM_FIVE_ISLAND_MEMORIAL_PILLAR_BLUK_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 14, 25, 0
	setvar VAR_TEMP_C, 1
	end

FiveIsland_ResortGorgeous_EventScript_Sparkle_NestBall::
	goto_if_set FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_NEST_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 10, 7, 0
	setvar VAR_TEMP_F, 1
	end

FiveIsland_ResortGorgeous_EventScript_Sparkle_Stardust::
	goto_if_set FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STARDUST, EventScript_ReleaseEnd
	dofieldeffectsparkle 27, 11, 0
	setvar VAR_TEMP_E, 1
	end

FiveIsland_ResortGorgeous_EventScript_Sparkle_StarPiece::
	goto_if_set FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STAR_PIECE, EventScript_ReleaseEnd
	dofieldeffectsparkle 40, 12, 0
	setvar VAR_TEMP_D, 1
	end

FiveIsland_ResortGorgeous_EventScript_Sparkle_Stardust2::
	goto_if_set FLAG_HIDDEN_ITEM_FIVE_ISLAND_RESORT_GORGEOUS_STARDUST_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 27, 5, 0
	setvar VAR_TEMP_C, 1
	end

UndergroundPath_NorthSouthTunnel_EventScript_Sparkle_Potion::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 5, 30, 0
	setvar VAR_TEMP_F, 1
	end

UndergroundPath_NorthSouthTunnel_EventScript_Sparkle_Antidote::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ANTIDOTE, EventScript_ReleaseEnd
	dofieldeffectsparkle 5, 6, 0
	setvar VAR_TEMP_E, 1
	end

UndergroundPath_NorthSouthTunnel_EventScript_Sparkle_ParalyzeHeal::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_PARALYZE_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 3, 15, 0
	setvar VAR_TEMP_D, 1
	end

UndergroundPath_NorthSouthTunnel_EventScript_Sparkle_Awakening::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_AWAKENING, EventScript_ReleaseEnd
	dofieldeffectsparkle 1, 24, 0
	setvar VAR_TEMP_C, 1
	end

UndergroundPath_NorthSouthTunnel_EventScript_Sparkle_BurnHeal::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_BURN_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 2, 57, 0
	setvar VAR_TEMP_B, 1
	end

UndergroundPath_NorthSouthTunnel_EventScript_Sparkle_IceHeal::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ICE_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 6, 53, 0
	setvar VAR_TEMP_A, 1
	end

UndergroundPath_NorthSouthTunnel_EventScript_Sparkle_Ether::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_NORTH_SOUTH_TUNNEL_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 3, 39, 0
	setvar VAR_TEMP_9, 1
	end

UndergroundPath_EastWestTunnel_EventScript_Sparkle_Potion::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_POTION, EventScript_ReleaseEnd
	dofieldeffectsparkle 7, 3, 0
	setvar VAR_TEMP_F, 1
	end

UndergroundPath_EastWestTunnel_EventScript_Sparkle_Antidote::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ANTIDOTE, EventScript_ReleaseEnd
	dofieldeffectsparkle 62, 5, 0
	setvar VAR_TEMP_E, 1
	end

UndergroundPath_EastWestTunnel_EventScript_Sparkle_ParalyzeHeal::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_PARALYZE_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 17, 5, 0
	setvar VAR_TEMP_D, 1
	end

UndergroundPath_EastWestTunnel_EventScript_Sparkle_Awakening::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_AWAKENING, EventScript_ReleaseEnd
	dofieldeffectsparkle 31, 4, 0
	setvar VAR_TEMP_C, 1
	end

UndergroundPath_EastWestTunnel_EventScript_Sparkle_BurnHeal::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_BURN_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 45, 3, 0
	setvar VAR_TEMP_B, 1
	end

UndergroundPath_EastWestTunnel_EventScript_Sparkle_IceHeal::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ICE_HEAL, EventScript_ReleaseEnd
	dofieldeffectsparkle 70, 3, 0
	setvar VAR_TEMP_A, 1
	end

UndergroundPath_EastWestTunnel_EventScript_Sparkle_Ether::
	goto_if_set FLAG_HIDDEN_ITEM_UNDERGROUND_PATH_EAST_WEST_TUNNEL_ETHER, EventScript_ReleaseEnd
	dofieldeffectsparkle 55, 2, 0
	setvar VAR_TEMP_9, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_RazzBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_RAZZ_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 31, 25, 0
	setvar VAR_TEMP_F, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_BlukBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_BLUK_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 15, 0
	setvar VAR_TEMP_E, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_NanabBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_NANAB_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 25, 24, 0
	setvar VAR_TEMP_D, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_WepearBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_WEPEAR_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 11, 24, 0
	setvar VAR_TEMP_C, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_OranBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_ORAN_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 37, 18, 0
	setvar VAR_TEMP_B, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_CheriBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_CHERI_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 14, 23, 0
	setvar VAR_TEMP_A, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_ChestoBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_CHESTO_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 47, 5, 0
	setvar VAR_TEMP_9, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_PechaBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PECHA_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 7, 30, 0
	setvar VAR_TEMP_8, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_RawstBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_RAWST_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 5, 0
	setvar VAR_TEMP_7, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_AspearBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_ASPEAR_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 25, 6, 0
	setvar VAR_TEMP_6, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_PersimBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PERSIM_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 46, 32, 0
	setvar VAR_TEMP_5, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_PinapBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_PINAP_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 43, 16, 0
	setvar VAR_TEMP_4, 1
	end

ThreeIsland_BerryForest_EventScript_Sparkle_LumBerry::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BERRY_FOREST_LUM_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 8, 5, 0
	setvar VAR_TEMP_3, 1
	end

ThreeIsland_DunsparceTunnel_EventScript_Sparkle_Nugget::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_DUNSPARCE_TUNNEL_NUGGET, EventScript_ReleaseEnd
	dofieldeffectsparkle 21, 3, 0
	setvar VAR_TEMP_F, 1
	end

ThreeIsland_EventScript_Sparkle_PPUp::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_PP_UP, EventScript_ReleaseEnd
	dofieldeffectsparkle 5, 13, 0
	setvar VAR_TEMP_F, 1
	end

ThreeIsland_BondBridge_EventScript_Sparkle_MaxRepel::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_MAX_REPEL, EventScript_ReleaseEnd
	dofieldeffectsparkle 61, 5, 0
	setvar VAR_TEMP_F, 1
	end

ThreeIsland_BondBridge_EventScript_Sparkle_Pearl::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 44, 12, 0
	setvar VAR_TEMP_E, 1
	end

ThreeIsland_BondBridge_EventScript_Sparkle_Stardust::
	goto_if_set FLAG_HIDDEN_ITEM_THREE_ISLAND_BOND_BRIDGE_STARDUST, EventScript_ReleaseEnd
	dofieldeffectsparkle 33, 7, 0
	setvar VAR_TEMP_D, 1
	end

OneIsland_TreasureBeach_EventScript_Sparkle_Stardust::
	goto_if_set FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STARDUST, EventScript_ReleaseEnd
	dofieldeffectsparkle 8, 20, 0
	setvar VAR_TEMP_F, 1
	end

OneIsland_TreasureBeach_EventScript_Sparkle_Stardust2::
	goto_if_set FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STARDUST_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 13, 27, 0
	setvar VAR_TEMP_E, 1
	end

OneIsland_TreasureBeach_EventScript_Sparkle_Pearl::
	goto_if_set FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 11, 31, 0
	setvar VAR_TEMP_D, 1
	end

OneIsland_TreasureBeach_EventScript_Sparkle_Pearl2::
	goto_if_set FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_PEARL_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 34, 0
	setvar VAR_TEMP_C, 1
	end

OneIsland_TreasureBeach_EventScript_Sparkle_UltraBall::
	goto_if_set FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 22, 0
	setvar VAR_TEMP_B, 1
	end

OneIsland_TreasureBeach_EventScript_Sparkle_UltraBall2::
	goto_if_set FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_ULTRA_BALL_2, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 33, 0
	setvar VAR_TEMP_A, 1
	end

OneIsland_TreasureBeach_EventScript_Sparkle_StarPiece::
	goto_if_set FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_STAR_PIECE, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 29, 0
	setvar VAR_TEMP_9, 1
	end

OneIsland_TreasureBeach_EventScript_Sparkle_BigPearl::
	goto_if_set FLAG_HIDDEN_ITEM_ONE_ISLAND_TREASURE_BEACH_BIG_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 8, 27, 0
	setvar VAR_TEMP_8, 1
	end

TwoIsland_CapeBrink_EventScript_Sparkle_RareCandy::
	goto_if_set FLAG_HIDDEN_ITEM_TWO_ISLAND_CAPE_BRINK_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 13, 0
	setvar VAR_TEMP_F, 1
	end

PewterCity_EventScript_Sparkle_PokeBall::
	goto_if_set FLAG_HIDDEN_ITEM_PEWTER_CITY_POKE_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 6, 3, 0
	setvar VAR_TEMP_F, 1
	end

Route3_EventScript_Sparkle_OranBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE3_ORAN_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 26, 9, 0
	setvar VAR_TEMP_F, 1
	end

Route24_EventScript_Sparkle_PechaBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE24_PECHA_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 19, 4, 0
	setvar VAR_TEMP_F, 1
	end

Route6_EventScript_Sparkle_SitrusBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE6_SITRUS_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 5, 5, 0
	setvar VAR_TEMP_F, 1
	end

Route6_EventScript_Sparkle_RareCandy::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE6_RARE_CANDY, EventScript_ReleaseEnd
	dofieldeffectsparkle 19, 5, 0
	setvar VAR_TEMP_E, 1
	end

Route8_EventScript_Sparkle_RawstBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE8_RAWST_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 42, 10, 0
	setvar VAR_TEMP_F, 1
	end

Route8_EventScript_Sparkle_LumBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE8_LUM_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 38, 11, 0
	setvar VAR_TEMP_E, 1
	end

Route8_EventScript_Sparkle_LeppaBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE8_LEPPA_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 42, 15, 0
	setvar VAR_TEMP_D, 1
	end

FuchsiaCity_EventScript_Sparkle_MaxRevive::
	goto_if_set FLAG_HIDDEN_ITEM_FUCHSIA_CITY_MAX_REVIVE, EventScript_ReleaseEnd
	dofieldeffectsparkle 33, 26, 0
	setvar VAR_TEMP_F, 1
	end

Route14_EventScript_Sparkle_Zinc::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE14_ZINC, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 20, 0
	setvar VAR_TEMP_F, 1
	end

Route14_EventScript_Sparkle_PinapBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE14_PINAP_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 19, 53, 0
	setvar VAR_TEMP_E, 1
	end

Route7_EventScript_Sparkle_WepearBerry::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE7_WEPEAR_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 15, 0
	setvar VAR_TEMP_F, 1
	end

Route20_EventScript_Sparkle_Stardust::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE20_STARDUST, EventScript_ReleaseEnd
	dofieldeffectsparkle 23, 6, 0
	setvar VAR_TEMP_F, 1
	end

Route21_North_EventScript_Sparkle_Pearl::
	goto_if_set FLAG_HIDDEN_ITEM_ROUTE21_NORTH_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 17, 42, 0
	setvar VAR_TEMP_F, 1
	end

MtEmber_Exterior_EventScript_Sparkle_FireStone::
	goto_if_set FLAG_HIDDEN_ITEM_MT_EMBER_EXTERIOR_FIRE_STONE, EventScript_ReleaseEnd
	dofieldeffectsparkle 18, 17, 0
	setvar VAR_TEMP_F, 1
	end

MtEmber_Exterior_EventScript_Sparkle_UltraBall::
	goto_if_set FLAG_HIDDEN_ITEM_MT_EMBER_EXTERIOR_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 8, 30, 0
	setvar VAR_TEMP_E, 1
	end

FourIsland_EventScript_Sparkle_Pearl::
	goto_if_set FLAG_HIDDEN_ITEM_FOUR_ISLAND_PEARL, EventScript_ReleaseEnd
	dofieldeffectsparkle 22, 34, 0
	setvar VAR_TEMP_F, 1
	end

FourIsland_EventScript_Sparkle_UltraBall::
	goto_if_set FLAG_HIDDEN_ITEM_FOUR_ISLAND_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 6, 21, 0
	setvar VAR_TEMP_E, 1
	end

SixIsland_OutcastIsland_EventScript_Sparkle_StarPiece::
	goto_if_set FLAG_HIDDEN_ITEM_SIX_ISLAND_OUTCAST_ISLAND_STAR_PIECE, EventScript_ReleaseEnd
	dofieldeffectsparkle 16, 23, 0
	setvar VAR_TEMP_F, 1
	end

SixIsland_OutcastIsland_EventScript_Sparkle_NetBall::
	goto_if_set FLAG_HIDDEN_ITEM_SIX_ISLAND_OUTCAST_ISLAND_NET_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 6, 24, 0
	setvar VAR_TEMP_E, 1
	end

SixIsland_GreenPath_EventScript_Sparkle_UltraBall::
	goto_if_set FLAG_HIDDEN_ITEM_SIX_ISLAND_GREEN_PATH_ULTRA_BALL, EventScript_ReleaseEnd
	dofieldeffectsparkle 12, 9, 0
	setvar VAR_TEMP_F, 1
	end

SixIsland_WaterPath_EventScript_Sparkle_AspearBerry::
	goto_if_set FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_ASPEAR_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 15, 76, 0
	setvar VAR_TEMP_F, 1
	end

SixIsland_WaterPath_EventScript_Sparkle_OranBerry::
	goto_if_set FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_ORAN_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 3, 8, 0
	setvar VAR_TEMP_E, 1
	end

SixIsland_WaterPath_EventScript_Sparkle_PinapBerry::
	goto_if_set FLAG_HIDDEN_ITEM_SIX_ISLAND_WATER_PATH_PINAP_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 13, 63, 0
	setvar VAR_TEMP_D, 1
	end

SixIsland_EventScript_Sparkle_LeppaBerry::
	goto_if_set FLAG_HIDDEN_ITEM_SIX_ISLAND_LEPPA_BERRY, EventScript_ReleaseEnd
	dofieldeffectsparkle 9, 7, 0
	setvar VAR_TEMP_F, 1
	end
