Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "{JPN}おれは ファーリーだ よ！\n"
    .string "みて みて！$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "{JPN}おれは ファーリーだ よ！\n"
    .string "みて みて！$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "{JPN}ファーリーズ！$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "{JPN}えっ‥ ファーリー じゃないの？\n"
    .string "まあ いいけど。$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "{JPN}えっ‥ ファーリー じゃないの？\n"
    .string "まあ いいけど。$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$"
    .string "$$$$$$$$$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "BILL: Yeehah!\n"
    .string "Thanks, bud! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You didn't?\n"
    .string "That's a bummer.\p"
    .string "I've got to thank you…\n"
    .string "Oh, here, maybe this'll do.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "BILL: Yeehah!\n"
    .string "Thanks, lady! I owe you one!\p"
    .string "So, did you come to see my\n"
    .string "POKéMON collection?\p"
    .string "You didn't?\n"
    .string "That's a bummer.\p"
    .string "I've got to thank you…\n"
    .string "Oh, here, maybe this'll do.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER} received an S.S. TICKET\n"
    .string "from BILL.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "You've got too much stuff!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "That cruise ship S.S. ANNE is in\n"
    .string "VERMILION CITY.\p"
    .string "I hear there are lots of TRAINERS\n"
    .string "on board, too.\p"
    .string "They invited me to their party, but\n"
    .string "I can't stand fancy do's.\p"
    .string "Why don't you go instead of me?\n"
    .string "Go on and have a good time.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "BILL: Feel like checking out some\n"
    .string "of my rare POKéMON on my PC?\p"
    .string "Go on, check out my PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "TELEPORTER is displayed on the PC\n"
    .string "monitor.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} initiated the TELEPORTER's\n"
    .string "Cell Separator.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "BILL's favorite POKéMON list!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "Which POKéMON do you want to see?$"

