Route10_Text_MarkIntro::
    .string "Wow, you came all the way here?\n"
    .string "Maybe you're a Poké Maniac, too?\l"
    .string "Want to see my collection?$"

Route10_Text_MarkDefeat::
    .string "Humph.\n"
    .string "I'm not angry!$"

Route10_Text_MarkPostBattle::
    .string "I have more rare Pokémon at home!$"

Route10_Text_ClarkIntro::
    .string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
    .string "Ha-haha!\n"
    .string "Not laughing!\l"
    .string "Ha-hay fever! Haha-ha-choo!$"

Route10_Text_ClarkPostBattle::
    .string "Haha-ha-choo!\n"
    .string "Ha-choo!\l"
    .string "Snort! Snivel!$"

Route10_Text_HermanIntro::
    .string "Hi, kid!\n"
    .string "Want to see my Pokémon?$"

Route10_Text_HermanDefeat::
    .string "Oh, no!\n"
    .string "My Pokémon!$"

Route10_Text_HermanPostBattle::
    .string "I don't like you.\n"
    .string "I don't like anyone better than me!$"

Route10_Text_HeidiIntro::
    .string "I've been out at a Pokémon Gym\n"
    .string "a few times.\p"
    .string "…But I always lose.$"

Route10_Text_HeidiDefeat::
    .string "Ohh!\n"
    .string "After all my training!$"

Route10_Text_HeidiPostBattle::
    .string "I noticed some Poké Maniacs\n"
    .string "prowling around.\p"
    .string "Can you imagine? Them?\n"
    .string "Up here in the mountains?$"

Route10_Text_TrentIntro::
    .string "Ah!\n"
    .string "This mountain air is delicious!$"

Route10_Text_TrentDefeat::
    .string "That cleared my head!$"

Route10_Text_TrentPostBattle::
    .string "I feel bloated on mountain air!$"

Route10_Text_CarolIntro::
    .string "I'm feeling a bit faint.\n"
    .string "I haven't hiked in some time.$"

Route10_Text_CarolDefeat::
    .string "I'm too tired.\n"
    .string "I wasn't up for it.$"

Route10_Text_CarolPostBattle::
    .string "The Pokémon here in the mountains\n"
    .string "are so chunky…\p"
    .string "I wish there were pink Pokémon\n"
    .string "with a floral pattern!$"

Route10_Text_RockTunnelDetourToLavender::
    .string "Rock Tunnel\n"
    .string "Detour to Lavender Town$"

Route10_Text_RockTunnel::
    .string "Rock Tunnel$"

Route10_Text_PowerPlant::
    .string "Power Plant$"

Route10_Text_Hiker::
	.string "Hey, you.\n"
	.string "It gets awfully dark in\l"
	.string "Rock Tunnel.\p"
	.string "Here you go, I'll pass this on\n"
    .string "to you.$"

Route10_Text_HikerExplainFlash::
	.string "Teach that hidden move Flash to\n"
	.string "a Pokémon and use it.\p"
	.string "It lights up even the inky darkness\n"
	.string "of caves.\p"
	.string "But, to use it, you need the\n"
	.string "Gym Badge from Pewter's Pokémon Gym.$"
