Route1_Text_WorkAtPokeMartTakeSample::
    .string "Take this, I quit!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Please come see us if you need\n"
    .string "Poké Balls for catching Pokémon.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the Potion away in\n"
    .string "the bag's Items pocket.$"

Route1_Text_CanJumpFromLedges::
    .string "See those ledges along the road?\p"
    .string "It's a bit scary, but you can jump\n"
    .string "from them.\p"
    .string "You can get back to Pallet Town\n"
    .string "quicker that way.$"

Route1_Text_RouteSign::
    .string "Route 1\n"
    .string "Pallet Town - Viridian City$"

