CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} obtained an Eevee!$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "The chalkboard has drawings of\n"
    .string "Pokémon you have never seen.\p"
    .string "Which one will you look at?$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "The side of the PC is covered in\n"
    .string "stickers resembling a creature with\l"
    .string "two Smeargle-like tails.$"

CeladonCity_Condominiums_RoofRoom_Text_CyanAaaah::
    .string "ah- hello?\n"
    .string "could you knock first please?$"

CeladonCity_Condominiums_RoofRoom_Text_CyanHeyWait::
    .string "hey, wait, it's okay!\p"
    .string "i suppose you're curious to know\n"
    .string "what i do here, and by extension,\l"
    .string "who i am.$"

CeladonCity_Condominiums_RoofRoom_Text_CyanIntro::
    .string "my name is cyan.\n"
    .string "i made this hack. nice to meet you!\p"
    .string "anything you wanna ask about?$"

CeladonCity_Condominiums_RoofRoom_Text_CyanIntro2::
    .string "what's up?$"

CeladonCity_Condominiums_RoofRoom_Text_CyanMusic1::
    .string "the music?\n"
    .string "i made this music!\p"
    .string "i tried to adapt it to this game's\n"
    .string "sound engine, i hope it came out\l"
    .string "well!$"

CeladonCity_Condominiums_RoofRoom_Text_CyanMusic2::
    .string "oh, the music i made only plays\n"
    .string "in this room.\p"
    .string "i didn't write any of the other\n"
    .string "music in the game…$"

CeladonCity_Condominiums_RoofRoom_Text_CyanMusic3::
    .string "i made another song, you can change\n"
    .string "it with the stereo over there…$"

CeladonCity_Condominiums_RoofRoom_Text_CyanMusic4::
    .string "i made this!$"

CeladonCity_Condominiums_RoofRoom_Text_CyanMusic5::
    .string "i didn't make this!$"

CeladonCity_Condominiums_RoofRoom_Text_CyanMusicOff::
    .string "music? what music?\n"
    .string "where's the music?\p"
    .string "did you turn my music off?$"

CeladonCity_Condominiums_RoofRoom_Text_CyanNatDex1::
    .string "nat dex 2morrow.\p"
    .string "just kidding, i don't have an eta.\n"
    .string "sorry to disappoint$"

CeladonCity_Condominiums_RoofRoom_Text_CyanNatDex2::
    .string "nat dex 2morrow :)$"

CeladonCity_Condominiums_RoofRoom_Text_CyanNatDex3::
    .string "the t in nat dex stands for\n"
    .string "transgender$"

CeladonCity_Condominiums_RoofRoom_Text_CyanGenX1::
    .string "gen 10, huh?\p"
    .string "haha…\p"
    .string "you already want those creatures\n"
    .string "in the game so bad.\p"
    .string "well, i've got good news!\p"
    .string "see those doodles on the\n"
    .string "chalkboard?\p"
    .string "i made them! take a look!\n"
    .string "they are the newly revealed\l"
    .string "first partner pokemon!$"

CeladonCity_Condominiums_RoofRoom_Text_CyanGenX2::
    .string "you saw my doodles?\n"
    .string "what did you think?$"

CeladonCity_Condominiums_RoofRoom_Text_CyanGenXHated::
    .string "oh well, i suppose it's not\n"
    .string "everyone's cup of berry juice.\p"
    .string "or, did you expect that you'd\n"
    .string "actually get to use them?\p"
    .string "haha…$"

CeladonCity_Condominiums_RoofRoom_Text_CyanGenXLoved::
    .string "oh, aren't they cute?\n"
    .string "my favourite is gecqua.\p"
    .string "that creature was designed\n"
    .string "specifically to be my friend.\p"
    .string "gecqua gang, it's tail time!\p"
    .string "…\p"
    .string "that was cringe, sorry =///=$"

CeladonCity_Condominiums_RoofRoom_Text_CyanGenXUnseen::
    .string "that's okay! take your time!$"

CeladonCity_Condominiums_RoofRoom_Text_CyanJapanese1::
    .string "okay, um…\p"
    .string "…\p"
    .string "{JPN}こんにちは！\p"
    .string "えっと…\n"
    .string "ボクは　サイアンです。\p"
    .string "この　ハックロムを　つくった。\p"
    .string "…\p"
    .string "ボクの　にほんごは…\n"
    .string "じょうず　だったの？$"

CeladonCity_Condominiums_RoofRoom_Text_CyanJapanese2::
    .string "{JPN}こんにちは！$"

CeladonCity_Condominiums_RoofRoom_Text_CyanJapanese3::
    .string "konnichiwa!$"

CeladonCity_Condominiums_RoofRoom_Text_CyanNothing1::
    .string "all good, time is precious.\n"
    .string "good luck with your endeavours!$"

CeladonCity_Condominiums_RoofRoom_Text_CyanNothing2::
    .string "understandable. good luck with\n"
    .string "the remainder of your run!$"

CeladonCity_Condominiums_RoofRoom_Text_CyanNothing3::
    .string "well then, good luck! watch out\n"
    .string "for counter and mirror coat!$"

CeladonCity_Condominiums_RoofRoom_Text_CyanNothing4::
    .string "{JPN}がんばってね！$"

CeladonCity_Condominiums_RoofRoom_Text_CyanPenisReact::
    .string "?!?!\p"
    .string "wh-h-how did you find that song?\p"
    .string "c-could you…\n"
    .string "could you change it back, please?$"

CeladonCity_Condominiums_RoofRoom_Text_Song1Playing::
    .string "A cheery electronic tune is playing\n"
    .string "on the stereo system.\p"
    .string "Change it?$"

CeladonCity_Condominiums_RoofRoom_Text_Song2Playing::
    .string "A boss fight tune is playing\n"
    .string "on the stereo system.\p"
    .string "Change it back?$"

CeladonCity_Condominiums_RoofRoom_Text_Song3Playing::
    .string "The stereo system thinks you\n"
    .string "shouldn't be listening to this.\p"
    .string "Change it back?$"

CeladonCity_Condominiums_RoofRoom_Text_SongBGMOff1::
    .string "The silence is deafening.$"

CeladonCity_Condominiums_RoofRoom_Text_SongBGMOff2::
    .string "The deafening is silent.$"

CeladonCity_Condominiums_RoofRoom_Text_CyndaquilDoll::
    .string "A Cyndaquil doll.$"

CeladonCity_Condominiums_RoofRoom_Text_SubstituteDoll::
    .string "A Substitute doll.$"
