@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach::
    .string "Ready?\n"
    .string "Boing!\p"
    .string "We're having a Body Slam match\n"
    .string "to see who wimps out first.\p"
    .string "If you were to join us, you'd be\n"
    .string "squashed like a bug, though…\p"
    .string "How about I teach Body Slam to\n"
    .string "a Pokémon of yours instead?$"

Text_BodySlamDeclined::
    .string "Come again!\n"
    .string "Boing!$"

Text_BodySlamWhichMon::
    .string "Which Pokémon wants to learn how\n"
    .string "to Body Slam?$"

Text_BodySlamTaught::
    .string "Boioing!$"

FourIsland_House1_Text_FatMan::
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "There's a rare kind of Ice Pokémon\n"
    .string "that lives in the cave.\p"
    .string "We get a lot of visitors hoping to\n"
    .string "see that Pokémon.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "Oh? A Pokémon Egg?\n"
    .string "…I have no idea.\p"
    .string "…Oh, wait. The Day-Care people\n"
    .string "in town were saying something.\p"
    .string "They said that they'd found Eggs\n"
    .string "before on their property.$"

FourIsland_PokemonCenter_1F_Text_HaveYouHeardOfGracidea::
    .string "Have you heard of the Gracidea\n"
    .string "flower?\p"
    .string "It's been a long-standing tradition\n"
    .string "in the Sinnoh region to give\l"
    .string "bouquets of them to people as a\l"
    .string "way of expressing one's appreciation!$"

FourIsland_PokemonCenter_1F_Text_WowShaymin::
    .string "Oh, wow!\n"
    .string "It's Shaymin!\p"
    .string "When I see Shaymin, the first thing\n"
    .string "that comes to mind is the Gracidea\l"
    .string "flower!\p"
    .string "And it just so happens that I have a\n"
    .string "bunch. I'd be happy to share with\l"
    .string "you!$"

FourIsland_PokemonCenter_1F_Text_ItsBeenATradition::
    .string "It's been a tradition since long ago\n"
    .string "in the Sinnoh region to give\l"
    .string "bouquets of Gracidea flowers to\l"
    .string "people as a way of expressing\l"
    .string "appreciation.\p"
    .string "Anyone who receives a bouquet of\n"
    .string "Gracidea flowers will know just how\l"
    .string "grateful you are!\p"
    .string "No words are necessary!\n"
    .string "Isn't it a delightful custom?$"
